KaotoIO/kaoto

- .yarnrc.yml
```bash
➤ YN0000: ┌ Resolution step
➤ YN0002: │ uniforms-bridge-json-schema@npm:4.0.0-alpha.0 doesn't provide react (pd4a28), requested by uniforms
➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code
➤ YN0000: └ Completed in 0s 213ms
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed
➤ YN0000: ┌ Link step
➤ YN0000: └ Completed
➤ YN0000: Done with warnings in 0s 631ms
```
```bash
➤ YN0000: ┌ Resolution step
➤ YN0000: └ Completed in 0s 219ms
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed
➤ YN0000: ┌ Link step
➤ YN0000: └ Completed in 0s 217ms
➤ YN0000: Done in 0s 741ms
```
> fix(build): Fix yarn install warnings

- packages/camel-catalog/kaoto-camel-catalog-maven-plugin/src/main/java/io/kaoto/camelcatalog/KaotoCamelCatalogMojo.java
> Remove unused deprecated `inheritBydefault` Mojo annotation attribute

- packages/camel-catalog/kaoto-camel-catalog-maven-plugin/src/main/java/io/kaoto/camelcatalog/Index.java
- packages/camel-catalog/kaoto-camel-catalog-maven-plugin/src/main/java/io/kaoto/camelcatalog/KaotoCamelCatalogMojo.java
- packages/ui/src/camel-utils/camel-schemas-processor.test.ts
- packages/ui/src/camel-utils/camel-schemas-processor.ts
- packages/ui/src/camel-utils/index.ts
- packages/ui/src/components/SchemaSelector/SchemaSelector.test.tsx
- packages/ui/src/models/camel-catalog-index.ts
- packages/ui/src/models/schema.ts
- packages/ui/src/providers/catalog-schema-loader.provider.tsx
* Add missing tests
* Refactor the `files` property from the catalog into a dedicated `file` property
* Move the `Kamelets` property into the `catalog` section of the `index.json` file
> chore: Refactor Camel Catalog index.json file

- packages/ui/src/components/Catalog/Catalog.tsx
- packages/ui/src/components/Catalog/CatalogFilter.tsx
- packages/ui/src/components/Catalog/Tile.models.ts
- packages/ui/src/components/SchemaSelector/__snapshots__/SchemaSelector.test.tsx.snap
- packages/ui/src/models/camel-components-catalog.ts
- packages/ui/src/models/camel-processors-catalog.ts
- packages/ui/src/models/kamelets-catalog.ts
e.g.: ![image](https://github.com/KaotoIO/kaoto-next/assets/16251792/a7ae7d50-65e5-4271-a1d3-e584d0262804)
Matches: 
```
aws
AwS
aws2-ec2
aws elastic compute
SDK version 2.x.
sdk version 2.X
CLOUD
4.0.0
```
> fix(gh-40): Make catalog filter case insensitive and use also title

- packages/camel-catalog/package.json
- packages/camel-catalog/src/json-schema-to-typescript.mts
- packages/camel-catalog/tsconfig.json
- packages/ui/package.json
- packages/ui/tsconfig.node.json
- yarn.lock
Currently `@kaoto-next/camel-catalog` exposes the JSON Schemas for the following Camel entities:
* YAML Dsl
* Kamelet
* KameletBinding
* Pipe
Add a new `yarn` command to export `Typescript` definitions from those schemas to aid the dev phase.
```bash
yarn workspace @kaoto-next/camel-catalog build:mvn
yarn workspace @kaoto-next/camel-catalog build:ts
yarn workspace @kaoto-next/camel-catalog build
```
> feat(camel-catalog): export Typescript definitions from Camel Schemas

- packages/ui/jest-setup.ts
- packages/ui/src/components/Visualization/Canvas/Canvas.tsx
- packages/ui/src/components/Visualization/Canvas/canvas.models.ts
- packages/ui/src/components/Visualization/Canvas/canvas.service.test.ts
- packages/ui/src/components/Visualization/Canvas/canvas.service.ts
- packages/ui/src/components/Visualization/Canvas/index.ts
- packages/ui/src/components/Visualization/Visualization.tsx
- packages/ui/src/models/visualization/visualization-node.test.ts
- packages/ui/src/models/visualization/visualization-node.ts
This pull request adds the first iteration of the Visualization component. It leverages [@patternfly/react-topology](https://www.patternfly.org/topology/getting-started) as an underlying rendering and layout library.
This pull request supersedes #63
Fixes: https://github.com/KaotoIO/kaoto-next/issues/34
Only `Camel Routes` are supported at this stage. In order to support other flow types, the transformation from said flow to `VisualizationNode` needs to be implemented.
1. Work on the Source Code editor component in order to allow multiple and different flows to test in-depth the `VisualizationComponent`.
2. Add the support for the remaining flows, f.i. `Integration`, `Kamelet`, `KameletBinding` and `Pipe`
> feat(viz): Use @patternfly/react-topology to render a route

- packages/ui/src/components/Catalog/BaseCatalog.tsx
- packages/ui/src/components/Catalog/Catalog.scss
- packages/ui/src/components/Catalog/Catalog.tsx
- packages/ui/src/layout/Shell.scss
- packages/ui/src/layout/Shell.tsx
When <Panel> is set as `isScrollable`, the MaxHeight of the panel is [hardcoded](https://www.patternfly.org/components/panel#css-variables) to `18.75rem` (none when isScrollable is false). Due to that, I set it manually in scss file.
> fix(gh-86): Background is not scrollable

- packages/camel-catalog/assembly/pom.xml
- packages/camel-catalog/pom.xml
- packages/ui/src/models/camel-entities/flows/route.ts
Fixes: #93
Also use camel-k-crds maven artifact to get Camel K CRDs
Fixes: #69
I get some type error when building locally, looking into it
```
src/models/camel-entities/flows/route.ts(13,11): error TS2430: Interface 'FromDefinition' incorrectly extends interface 'import("/home/tomo/workspace/Kaoto/kaoto-next/packages/camel-catalog/dist/types/camelYamlDsl").FromDefinition'.
Types of property 'steps' are incompatible.
Type 'CamelRouteStep[]' is not assignable to type 'ProcessorDefinition[]'.
Type 'CamelRouteStep' is not assignable to type 'ProcessorDefinition'.
Type 'Step' has no properties in common with type 'ProcessorDefinition'.
src/models/camel-entities/flows/route.ts(17,11): error TS2430: Interface 'RouteDefinition' incorrectly extends interface …
```
> chore: Use 4.1.0-SNAPSHOT Camel YAML DSL schema

- packages/camel-catalog/package.json
relates to: https://github.com/KaotoIO/kaoto-next/issues/98
> fix: Replace rm with rimraf to clean dist folder

- .github/workflows/deploy-to-gh-pages.yml
- packages/ui/vite.config.cjs
fixes https://github.com/KaotoIO/kaoto-next/issues/88
Decided to use GH pages instead of netlify, due to the netlify build env only providing java 8 (we need 17)
Edit: already tested with my fork - https://tplevko.github.io/kaoto-next/
> Add gh pages workflow

- packages/ui/src/providers/catalog-schema-loader.provider.tsx
Currently, `kaoto-next` is being deployed on GitHub pages under the following URL:
https://kaotoio.github.io/kaoto-next/
Since the `DEFAULT_CATALOG_PATH` is `/camel-catalog`, kaoto-next tries to load the catalog from:
https://kaotoio.github.io/
The fix is to provide an initial `.` to instruct to download the catalog under the current location
> fix(build): Load camel catalog in GitHub pages

- README.md
- packages/camel-catalog/package.json
Currently, there's a breaking change in node v20 that prevents ts-node to work as usual.
The workaround is to manually provide `ts-node/esm` as `custom loader` to node.
- [Node v20.0.0 release notes](https://nodejs.org/en/blog/release/v20.0.0)
- Related issue: https://github.com/TypeStrong/ts-node/issues/1997
fixes: https://github.com/KaotoIO/kaoto-next/issues/66
> fix(build): Build errors with node v20

- packages/ui/src/components/SourceCode/SourceCode.tsx
- packages/ui/src/providers/catalog-schema-loader.provider.tsx
`monaco-yaml` requires a valid `URI` to fetch the appropriate schema for the `monaco editor` and at the same time, it also uses it to determine the schema filename.
This commit uses the [resolved `URI` from the `fetch` call](https://github.com/KaotoIO/kaoto-next/pull/118/files#diff-77032d06eef9c517e8f18431ba19d26f52e6942d9e3a5a11133d07e999845e8eR53) when loading the schema to leverage relative paths when applicable, otherwise, deploying `kaoto-next` in environments like `GitHub Pages` in which the deployment is not at the root path, it will fail since it will use the wrong `URI`.
fixes: https://github.com/KaotoIO/kaoto-next/issues/109
> fix(build): Load Camel YAML schema in non root base path

- packages/camel-catalog/src/json-schema-to-typescript.mts
For Windows file path, `C:\` prefix are not supported as they get confused with a regular URI.
The fix is to write the file path with `file://` protocol.
Fixes: https://github.com/KaotoIO/kaoto-next/issues/98
Related issue: https://github.com/nodejs/node/issues/31710
> fix(build): Windows build

- packages/ui-tests/.storybook/main.ts
- packages/ui-tests/stories/Navigation.stories.tsx
- packages/ui/package.json
- packages/ui/src/public-api.ts
- packages/ui/src/testing-api.ts
- packages/ui/vite.config.lib.ts
- packages/ui/vite.config.testing-lib.ts
Currently, public and internal components are exposed through `@kaoto-next/ui` entrypoint, but this is not ideal, since there's no separation between components meant to be reused and components meant to be tested internally.
Create a new entry point for `testing`
1. For public components, the declaration should go in the `public-api.ts` file
2. For internal components that need to be exposed for testing, the `testing-api.ts` file should be used instead
The imports for testing components needs to be updated like the following:
```diff
- import { Navigation, Shell } from '@kaoto-next/ui';
+ import { Navigation, Shell } from '@kaoto-next/ui/testing';
```
> chore: Expose internal components through dedicated entrypoint

- packages/ui-tests/.storybook/preview.ts
- packages/ui-tests/package.json
- packages/ui/package.json
- packages/ui/src/components/Visualization/Visualization.tsx
- yarn.lock
Since we're using `@patternfly/react-topology` for the `Visualization` component, there's no need to keep `reactflow` at the moment.
> chore: remove reactflow

- packages/ui/src/components/Visualization/Canvas/Canvas.tsx
- packages/ui/src/components/Visualization/Canvas/canvas.service.ts
Fix for https://github.com/KaotoIO/kaoto-next/issues/119
Updated the way the diagram controller is created. The way the diagram is loaded now:
> fix(gh-119) better way to refresh the Canvas component

- packages/camel-catalog/assembly/pom.xml
- packages/camel-catalog/assembly/src/test/java/io/kaoto/camelcatalog/CamelCatalogTestSupport.java
- packages/camel-catalog/assembly/src/test/java/io/kaoto/camelcatalog/CamelYamlDslSchemaTest.java
- packages/camel-catalog/assembly/src/test/java/io/kaoto/camelcatalog/IndexTest.java
- packages/camel-catalog/kaoto-camel-catalog-maven-plugin/src/main/java/io/kaoto/camelcatalog/KaotoCamelCatalogMojo.java
- packages/camel-catalog/pom.xml
- packages/camel-catalog/src/json-schema-to-typescript.mts
> fix: Create sub schemas for each top properties

- packages/camel-catalog/assembly/src/test/java/io/kaoto/camelcatalog/IndexTest.java
- packages/camel-catalog/kaoto-camel-catalog-maven-plugin/src/main/java/io/kaoto/camelcatalog/Index.java
- packages/camel-catalog/kaoto-camel-catalog-maven-plugin/src/main/java/io/kaoto/camelcatalog/KaotoCamelCatalogMojo.java
- packages/ui/src/camel-utils/camel-schemas-processor.test.ts
- packages/ui/src/camel-utils/camel-schemas-processor.ts
- packages/ui/src/components/SourceCode/SourceCode.tsx
Fixes: #147
ATM sub schemas are not used by UI. We'll soon use for Beans editor (#8) and will be easier to identify the sub schema by its name being same as the property name - for example, `beans` to be a name for the beans sub schema. The old verbose name were moved as `description` in the index.json. We might want to generate an enum of these sub schema names and put in .d.ts.
> fix: Let UI use maven generated YAML DSL sub schema

- .github/workflows/chromatic.yml
Currently, publishing to chromatic only happens on `PRs` to the `main` branch.
* Publish to chromatic upon push to the main branch
* Build `@kaoto-next/uniforms-patternfly` prior building `@kaoto-next/ui`
> chore(build): Build chromatic upon push to main

- packages/ui/package.json
- packages/ui/src/providers/catalog-schema-loader.provider.tsx
Currently, we're using the catalog at runtime by:
```typescript
import catalogIndex from '@kaoto-next/camel-catalog/index.json?url';
```
While it works, the problem with this approach is that we're tying the @kaoto-next/camel-catalog dependency at runtime.
The change is to leverage the vite build step in which the catalog is copied to the `assets` folder.
```typescript
fetch(`.${DEFAULT_CATALOG_PATH}/index.json`)
```
Relates to: https://github.com/KaotoIO/kaoto-next/issues/131
> chore(ui): Remove direct catalog usage

- packages/ui/src/hooks/entities.ts
- packages/ui/src/layout/Shell.tsx
- packages/ui/src/models/visualization/flows/camel-component-schema.service.ts
- packages/ui/src/pages/SourceCode/SourceCodePage.tsx
Currently, there are 2 issues around configuring steps:
1. After configuring a node using the CanvasForm, there's a remaining `[]` at the end of the Source Code.
2. Upon configuring a node using the CanvasForm, the configuration fall under the wrong `properties` property.
3. After changes, the source code is not being stored in `LocalStorage`
1. Only parse the `visualEntities` or `entities` if they aren't empty
2. Place the node configuration under the `parameters` property.
3. Move the sync `useEffect` to the `Shell` component, as the `SourceCodePage`
gets deleted when switching routes.
Relates to: https://github.com/KaotoIO/kaoto-next/issues/137
> fix(code): Remove phantom array and define parameter property

- package.json
- yarn.lock
When executing the `publish` action, `lerna` is used instead, as [it is already provided in the runner nodes](https://github.com/actions/runner-images/blob/ubuntu22/20230924.1/images/linux/Ubuntu2204-Readme.md#project-management)
Provide `@lerna-lite/cli` dependency to signal which CLI we want to use.
> fix(lerna-lite) Provide @lerna-lite/cli as dependency

- packages/ui/src/models/visualization/flows/kamelet-binding.test.ts
- packages/ui/src/models/visualization/flows/kamelet-binding.ts
- packages/ui/src/models/visualization/flows/kamelet-schema.service.ts
- packages/ui/src/models/visualization/flows/pipe.test.ts
- packages/ui/src/models/visualization/visualization-node.ts
- packages/ui/src/stubs/kamelet-binding.ts
> feat: Configure KameletBinding & Pipe properties

- .github/workflows/create-pre-release-pr.yml
- .github/workflows/release-and-publish.yml
- lerna.json
- package.json
This workflow consists of 2 steps:
1. The create-pre-release-pr.yaml workflow triggers a lerna-lite version command and creates a pull request with the changes
2. Once the pull request is done, the release-and-publish.yml workflow publishes the changed packages by using the lerna-lite publish from-package command, and later on it creates a release. The latter is not working due to a lack of permissions to create the release.
Fixes: https://github.com/KaotoIO/kaoto-next/issues/77
> feat(version): Create a pull request for the release process

- packages/ui/package.json
In order for lerna-lite to be able to publish a package, we need to set the access to public.
Relates to: https://github.com/KaotoIO/kaoto-next/issues/77
> fix(publishing): Set access:public for @kaoto-next/ui

- packages/ui/src/components/Visualization/Canvas/canvas.service.ts
- packages/ui/src/components/Visualization/Custom/CustomNode.tsx
- packages/ui/src/models/visualization/base-visual-entity.ts
This CustomNode component will be the foundation for adding new nodes and for providing icons to the canvas
* https://github.com/KaotoIO/kaoto-next/issues/75
* https://github.com/KaotoIO/kaoto-next/issues/76
> chore(viz): Add CustomNode component

- packages/ui/src/components/Visualization/Canvas/CanvasForm.test.tsx
- packages/ui/src/components/Visualization/Canvas/canvas.service.test.ts
- packages/ui/src/models/visualization/flows/kamelet-binding.ts
- packages/ui/src/models/visualization/flows/route.ts
- packages/ui/src/models/visualization/visualization-node.test.ts
- packages/ui/src/models/visualization/visualization-node.ts
In some cases, we're using the VisualizationNode class directly to create a new node as `new VisualizationNode(...)`.
This is not a problem itself, but tying entity classes like `KameletBinding` with the `VisualizationNode` class is not ok, as it allows to implement functionality directly on the implementation class that other entities won't leverage.
This commit encompasses:
* Remove the usage of `new VisualizationClass(...)`
* Create a new function that returns an instance of `VisualizationNode` but using the `IVisualizationNode` type instead
> chore(viznode): Remove usage of the VisualizationNode class

- packages/ui/src/components/Catalog/Catalog.models.ts
Initially, the `ITile` interface had a `rawObject` property for holding raw information about the underlying `Tile` object.
This property is now optional and deprecated as it's better to rely on the `name` property to identify the selected `Tile` to have better isolation of concerns between the `Tile` object and its consumers.
> chore(tile): Make rawObject optional and deprecated

- packages/ui/src/components/Visualization/Custom/CustomNode.tsx
relates to https://github.com/KaotoIO/kaoto-next/issues/76
Initial work on icon resolving for the `CustomNode`. 
This for now just specifies the KB icon or selects the default icon for every other flow type.
Will add the handling for EIP icons, from [here](https://camel.apache.org/components/4.0.x/eips/enterprise-integration-patterns.html#_eip_icons)
The canvas sidebar also needs to display the selected node icon and we also need to  need to add handling for custom icons.
> feat: Improve component's icon visualization

- .github/workflows/build-lint-test.yml
- .github/workflows/deploy-to-gh-pages.yml
- packages/ui/jest-setup.ts
- packages/ui/jest.config.ts
- packages/ui/package.json
- packages/ui/src/camel-utils/camel-random-id.test.ts
- packages/ui/src/models/camel/camel-resource.ts
- packages/ui/src/store/index.ts
- yarn.lock
Currently, there are many logs regarding warnings from tests.
The changes in this pull request are:
* Clean some of the logs
* Introduce `jest-canvas-mock` dependency to properly mock `@patternfly/react-topology` `SVG` interaction
* Remove the duplicated build of `@kaoto-next/camel-catalog` package
> chore(test): Cleanup tests logs

- packages/ui/src/assets/question-mark.svg
- packages/ui/src/components/Visualization/Canvas/CanvasSideBar.scss
- packages/ui/src/components/Visualization/Canvas/CanvasSideBar.tsx
- packages/ui/src/components/Visualization/Custom/CustomNode.tsx
- packages/ui/src/models/visualization/base-visual-entity.ts
- packages/ui/src/models/visualization/flows/camel-component-schema.service.ts
- packages/ui/src/models/visualization/flows/camel-route-visual-entity.ts
- packages/ui/src/models/visualization/flows/pipe-visual-entity.ts
- packages/ui/src/models/visualization/visualization-node.ts
- packages/ui/src/utils/node-icon-resolver.ts
Added the questionmark icon - ATM only for "unknown" KameletBindings - can add this also to Camel Route.
For EIP's - there is only a log and choice ATM, for other steps there is a placeholder icon.
The current state for Camel Routes:
KameletBindings:
> feat: sidebar icon handling and EIP POC

- packages/ui/src/providers/catalog-schema-loader.provider.tsx
Currently, when downloading the Camel Catalog, we're not waiting until the process is completed, which leads to the rendering flows without icons.
The fix is to wait until the catalog is processed before rendering the content
> fix(catalog): Wait until the catalog is downloaded

- packages/camel-catalog/src/json-schema-to-typescript.mts
- packages/ui/vite.config.cjs
Currently, we're generating the Camel Catalog at build time, in a pretty fashion.
The issue with this approach is the file size increase.
This pull request minifies those files at the UI build time, but preserves them in a pretty fashion in the `dist` folder, so it can be analyzed locally for devs.
Fixes: https://github.com/KaotoIO/kaoto-next/issues/131
> feat(catalog): Minify Camel Catalog

- packages/ui/src/components/Loading/Loading.test.tsx
- packages/ui/src/components/Loading/Loading.tsx
- packages/ui/src/components/Loading/index.ts
Adding a `Loading` distractor component to use it when loading `kaoto-next`
> feat(viz): Add Loading component

- packages/ui/src/components/Visualization/ContextToolbar/FlowType/FlowTypeSelector.test.tsx
- packages/ui/src/components/Visualization/ContextToolbar/FlowType/FlowTypeSelector.tsx
- packages/ui/src/components/Visualization/ContextToolbar/FlowType/NewFlow.test.tsx
- packages/ui/src/components/Visualization/ContextToolbar/FlowType/NewFlow.tsx
- packages/ui/src/components/Visualization/ContextToolbar/Flows/FlowsList.tsx
- packages/ui/src/hooks/entities.ts
- packages/ui/src/models/camel/camel-k-resource.ts
- packages/ui/src/models/camel/camel-resource.ts
- packages/ui/src/models/camel/camel-route-resource.ts
- packages/ui/src/models/camel/integration-resource.ts
- packages/ui/src/models/camel/kamelet-binding-resource.ts
- packages/ui/src/models/camel/kamelet-resource.ts
- packages/ui/src/models/camel/pipe-resource.ts
- packages/ui/src/models/visualization/flows/flow-templates-service.ts
- packages/ui/src/models/visualization/flows/flows-visibility.ts
- packages/ui/src/providers/visible-flows.provider.tsx
Make `New Route` and Remove route functional. Also I refactored  VisibleFlowsReducer to be more readable and fixed wrong numbers. 
This PR also introduces flowTemplateService which in the future should be use to provide default yaml templates when adding new flows.
> feat(viz): Implement `New Route` and `Remove` route 

- packages/ui/src/components/Visualization/Canvas/canvas.service.test.ts
- packages/ui/src/components/Visualization/Canvas/canvas.service.ts
Currently, there's no mechanism to alter the canvas view port.
This pull request enables the Zoom and Pane functionality from `@patternfly/react-topology`
[Screencast from 2023-10-30 17-05-03.webm](https://github.com/KaotoIO/kaoto-next/assets/16512618/171cdbf2-cae4-475e-bcd7-8a182733ed86)
> feat(viz): Enable zoom and scroll for the canvas

- packages/ui/src/models/visualization/flows/camel-component-schema.service.ts
- packages/ui/src/models/visualization/flows/camel-route-visual-entity.ts
- packages/ui/src/models/visualization/flows/support/camel-component-types.ts
Currently, the Camel Route representation is broken due to the children are not placed correctly
| --- | --- |
| ![image](https://github.com/KaotoIO/kaoto-next/assets/16512618/b3bb431b-92eb-413f-8f9f-116e18a6a656) | ![image](https://github.com/KaotoIO/kaoto-next/assets/16512618/77102fee-e32c-49c9-9cf3-72a56f646b7c) |
Kudos to @pprosser-redhat for providing an example route that helped to identify the issue
> fix(viz): Fix broken Camel Route representation

- .github/workflows/e2e-tests.yml
- packages/ui-tests/cypress/e2e/beans.cy.ts
- packages/ui-tests/cypress/e2e/catalog.cy.ts
- packages/ui-tests/cypress/e2e/designer.cy.ts
- packages/ui-tests/cypress/e2e/metadata.cy.ts
- packages/ui-tests/cypress/fixtures/flows/CamelRoute.yaml
- packages/ui-tests/cypress/fixtures/flows/MetadataPipe.yaml
- packages/ui-tests/cypress/support/cypress.d.ts
- packages/ui-tests/cypress/support/e2e.ts
- packages/ui-tests/cypress/support/next-commands/default.ts
- packages/ui-tests/cypress/support/next-commands/design.ts
- packages/ui-tests/cypress/support/next-commands/metadata.ts
- packages/ui-tests/cypress/support/next-commands/sourceCode.ts
- packages/ui/src/components/Visualization/Canvas/CanvasSideBar.tsx
- packages/ui/src/providers/catalog.provider.tsx
- packages/ui/src/providers/schemas.provider.tsx
Continue with https://github.com/KaotoIO/kaoto-next/issues/168
E2E hook and test stabilization
> chore: add e2e PR hook

- packages/ui/src/camel-utils/camel-to-tile.adapter.test.ts
- packages/ui/src/camel-utils/camel-to-tile.adapter.ts
- packages/ui/src/components/Visualization/Custom/ItemReplaceNode.tsx
- packages/ui/src/models/camel/camel-route-resource.ts
- packages/ui/src/models/visualization/flows/camel-route-visual-entity.test.ts
- packages/ui/src/models/visualization/flows/camel-route-visual-entity.ts
- packages/ui/src/models/visualization/flows/support/camel-component-default.service.ts
- packages/ui/src/models/visualization/flows/support/camel-component-schema.service.ts
At this moment, only CamelK `Pipe`s supports node insite replacement.
The goal for this pull request is to add said functionality for Camel Routes as well.
* When removing the `from` node from a Camel Route, it gets replaced with a placeholder, like the `source` and `sink` nodes from CamelK `Pipe`
* When replacing the `from` node from a Camel Route, the catalog only shows components that don't contain the `producerOnly` tag.
> feat(viz) Replace Camel Route steps

- packages/ui/src/camel-utils/camel-to-tile.adapter.test.ts
- packages/ui/src/camel-utils/camel-to-tile.adapter.ts
- packages/ui/src/components/Catalog/Tags/tag-color-resolver.ts
At this moment, there's no deprecation warning for deprecated components
* Deprecated components are signaled as `Deprecated` in the catalog
relates to: #287
> feat(tiles) Add deprecation note

- packages/ui-tests/cypress/e2e/designer.cy.ts
- packages/ui-tests/cypress/support/next-commands/design.ts
- packages/ui/src/components/Visualization/Canvas/__snapshots__/Canvas.test.tsx.snap
- packages/ui/src/components/Visualization/ContextToolbar/FlowClipboard/FlowClipboard.test.tsx
- packages/ui/src/models/visualization/flows/camel-route-visual-entity.test.ts
- packages/ui/src/models/visualization/flows/camel-route-visual-entity.ts
- packages/ui/src/models/visualization/flows/support/camel-component-schema.service.ts
- packages/ui/src/models/visualization/visualization-node.test.ts
- packages/ui/src/utils/node-icon-resolver.ts
fixes https://github.com/KaotoIO/kaoto-next/issues/306
Also has following effect - nodes have name not equal to the URI, but rather to the component name - e.g. timer node with URI "timer:tutorial" is not named "timer:tutorial" in the graph, but just "timer" (can be changed back in case this was something we wanted)
The kamelet nodes names remained e.g. "kamelet:pdf-action"
> fix(306) - kamelets icons not showing in Camel Routes

- packages/ui-tests/stories/ContextToolbar.stories.tsx
- packages/ui-tests/stories/Navigation.stories.tsx
- packages/ui/src/App.tsx
- packages/ui/src/components/Visualization/Canvas/CanvasForm.tsx
- packages/ui/src/components/Visualization/Canvas/ExpressionEditor.tsx
- packages/ui/src/components/Visualization/ContextToolbar/FlowClipboard/FlowClipboard.test.tsx
- packages/ui/src/components/Visualization/ContextToolbar/FlowClipboard/FlowClipboard.tsx
- packages/ui/src/components/Visualization/ContextToolbar/FlowType/NewFlow.test.tsx
- packages/ui/src/components/Visualization/ContextToolbar/FlowType/NewFlow.tsx
- packages/ui/src/components/Visualization/ContextToolbar/Flows/FlowsList.tsx
- packages/ui/src/components/Visualization/Custom/ItemAddNode.tsx
- packages/ui/src/components/Visualization/Custom/ItemInsertChildNode.tsx
- packages/ui/src/components/Visualization/Custom/ItemRemoveNode.tsx
- packages/ui/src/components/Visualization/Custom/ItemReplaceNode.tsx
- packages/ui/src/hooks/entities.test.tsx
- packages/ui/src/hooks/entities.ts
- packages/ui/src/hooks/useEntityContext/useEntityContext.test.tsx
- packages/ui/src/hooks/useSourceCodeContext/useSourceCodeContext.test.tsx
- packages/ui/src/hooks/useSourceCodeContext/useSourceCodeContext.tsx
- packages/ui/src/layout/Shell.tsx
- packages/ui/src/pages/Beans/BeansPage.tsx
- packages/ui/src/pages/Metadata/MetadataPage.tsx
- packages/ui/src/pages/PipeErrorHandler/PipeErrorHandlerPage.tsx
- packages/ui/src/pages/SourceCode/SourceCodePage.tsx
- packages/ui/src/providers/index.ts
- packages/ui/src/providers/source-code.provider.test.tsx
- packages/ui/src/providers/source-code.provider.tsx
- packages/ui/src/providers/visible-flows.provider.tsx
- packages/ui/src/utils/event-notifier.test.ts
- packages/ui/src/utils/event-notifier.ts
Currently, when a canvas node is configured, the entities are being regenerated, causing the canvas to be re-rendered.
* Extract SourceCodeProvider from EntitiesProvider
* Regenerate the entities whenever a structural change happens.
For reference, here's a change table:
| When modifying               | Should update |
| ---                          | --- |
| Source Code                  | * Camel Resource <br> * Entities |
| Add / Remove Flows           | * Source Code (one way) <br> * Entities |
| Add / Remove / Replace Steps | * Source Code (one way) <br> * Entities |
| Add / Remove / Beans         | * Source Code (one way) <br> * Entities |
| Update Step's properties     | * Source Code (one way) |
fixes: https://github.com/KaotoIO/kaoto-next/issues/266
This pull request it's a …
> fix(canvas): Avoid rerendering the canvas component

- .github/workflows/build-lint-test.yml
- packages/ui/package.json
- packages/ui/src/utils/node-icon-resolver.ts
Currently, both `lint:code` and `lint:style` are optional as both are run with `;` syntax, meaning that if `lint:code` fails, but `stylelint` doesn't, the stage is passed as only the last exit code gets stored.
The fix is to separate both scripts and execute them in dedicated stages.
> chore(lint): Make lint mandatory for UI package

- packages/ui/scripts/copy-camel-catalog-files.cjs
- packages/ui/scripts/get-camel-catalog-files.cjs
- packages/ui/vite.config.cjs
Currently, the Camel Catalog is not exposed through Kaoto in lib mode.
Export the processed Camel Catalog through Kaoto in lib mode for VSCode.
It's possible that in the future, the `@kaoto-next/camel-catalog` package will transition into a catalog processor only and will be consumed by `VSCode` directly, meaning that every consumer could decide which catalog to bundle when building Kaoto perspectives.
> chore(build): Expose @kaoto-next/camel-catalog files through the lib

- packages/ui/src/components/Visualization/CanvasFallback/CanvasFallback.tsx
- packages/ui/src/components/Visualization/Visualization.tsx
- packages/ui/src/pages/Design/DesignPage.tsx
- packages/ui/src/pages/Design/ReturnToSourceCodeFallback/ReturnToSourceCodeFallback.test.tsx
- packages/ui/src/pages/Design/ReturnToSourceCodeFallback/ReturnToSourceCodeFallback.tsx
- packages/ui/src/pages/Design/ReturnToSourceCodeFallback/__snapshots__/ReturnToSourceCodeFallback.test.tsx.snap
- packages/ui/src/pages/Design/ReturnToSourceCodeFallback/index.ts
Currently, the canvas fallback component that is loaded when a route cannot be parsed, has a link to the SourceCode editor. The issue with this approach is that some consumers won't have said source code editor.
This commit provides a default fallback component and moves the custom fallback component to the DesignPage, which is Source Code editor aware.
| Default fallback | DesignPage fallback |
| --- | --- |
| ![image](https://github.com/KaotoIO/kaoto-next/assets/16512618/84d2b9f8-dd6d-49ee-aed5-336ae607403f) | ![image](https://github.com/KaotoIO/kaoto-next/assets/16512618/4b71f323-2d81-4923-a2ae-4760defc3cae) |
> feat(canvas): Split Canvas fallback component

- package.json
- packages/ui/package.json
- packages/ui/src/multiplying-architecture/KaotoEditor.scss
- packages/ui/src/multiplying-architecture/KaotoEditor.tsx
- packages/ui/src/multiplying-architecture/KaotoEditorApp.tsx
- packages/ui/src/multiplying-architecture/KaotoEditorFactory.ts
- packages/ui/src/multiplying-architecture/index.ts
- packages/ui/src/public-api.ts
- yarn.lock
In order to use `kaoto-next`'s public components in VSCode, we need to combine the desired components into an `Editor` and then wrap it using the `Envelope` functionality from the multiplying architecture.
This pull request provides a custom `Editor` that will be used in `VSCode`.
This pull request is a prerequisite of https://github.com/KaotoIO/vscode-kaoto/issues/400
If the new content is the same as the current one, we don't need to update the Editor,
as it will regenerate the Camel Resource, hence disconnecting the configuration form (if open).
This happens due to the multiplying architecture lifecycle, where the content is set
after saving the file.
The lifecycle is:
1. The user edits the file by either adding a new node or modifying an existing one using the form
2. The user saves …
> feat(multiplying-architecture): Provide an editor using the multiplying architecture

- packages/ui/src/models/camel/camel-route-resource.test.ts
- packages/ui/src/models/camel/camel-route-resource.ts
Fixes [#313](https://github.com/KaotoIO/kaoto-next/issues/313)
Now, when we replace the source node, the catalog page loads like this:
Similarly, the Catalog page looks like this when we replace the last node:
> fix(313) - Kamelets in Camel Routes are not handled properly

- packages/ui/src/components/Visualization/Canvas/CanvasForm.tsx
There are some EIPs that could contain children, like `choice`, `when`, `otherwise`, `filter`, and others.
At this moment, the configuration panel doesn't work for those EIPs because those properties signal where to add the children.
As this property is handled by the canvas itself, this pull request filters them out from the configuration form.
A more robust solution might be added in the future, as new EIPs are added.
Fixes:
- https://github.com/KaotoIO/kaoto-next/issues/320
- https://github.com/KaotoIO/kaoto-next/issues/321
- https://github.com/KaotoIO/kaoto-next/issues/395
Relates to:
- https://github.com/KaotoIO/kaoto-next/issues/331
> fix(viz): Configure nodes that could contain children

- packages/ui/src/models/camel/__snapshots__/camel-route-resource.test.ts.snap
- packages/ui/src/models/camel/camel-route-resource.test.ts
- packages/ui/src/models/camel/camel-route-resource.ts
- packages/ui/src/models/visualization/flows/camel-route-visual-entity.test.ts
- packages/ui/src/models/visualization/flows/camel-route-visual-entity.ts
- packages/ui/src/stubs/camel-from.ts
This commit adds support for the `from` Camel construct.
If no entity is modified, the syntax is preserved, otherwise, it gets serialized as a `route` to hold an ID.
Fixes: https://github.com/KaotoIO/kaoto-next/issues/323
> feat(viz): Add Support for `from` construct

- packages/ui/src/components/Visualization/Custom/ItemInsertChildNode.tsx
- packages/ui/src/models/camel/camel-resource.ts
- packages/ui/src/models/camel/camel-route-resource.ts
- packages/ui/src/models/visualization/flows/camel-route-visual-entity.test.ts
- packages/ui/src/models/visualization/flows/camel-route-visual-entity.ts
For some Processors like `Choice` and `DoTry`, there are properties that could contain nested processors. In case of `Choice`, it's the `otherwise` property.
This pull request checks what's already defined in the `Processor` to avoid offering it again since it might cause data loss.
[Screencast from 2023-11-22 15-22-23.webm](https://github.com/KaotoIO/kaoto-next/assets/16512618/b19d38a6-63d1-44d7-aec8-771a6cead46e)
Fixes: https://github.com/KaotoIO/kaoto-next/issues/334
> fix(catalog): Avoid offering already existing single properties.

- packages/ui/src/models/visualization/flows/support/__snapshots__/camel-component-schema.service.test.ts.snap
- packages/ui/src/models/visualization/flows/support/camel-component-schema.service.test.ts
- packages/ui/src/models/visualization/flows/support/camel-component-schema.service.ts
Currently, expressions like the following, are not supported:
```yaml
- route:
id: "foo"
from:
uri: "quartz:foo?cron={{myCron}}"
steps:
- to: "bean:myBean?method=hello"
- log: "${body}"
```
This commit adds support for string-based processors by transforming them into regular objects when edited.
```yaml
- route:
id: "foo"
from:
uri: "quartz:foo?cron={{myCron}}"
steps:
- to:
uri: "bean:myBean?method=hello"
- log: 
message: "${body}"
```
Fixes: https://github.com/KaotoIO/kaoto-next/issues/332
> fix(viz): Add support for processor's string definition

- packages/ui/src/models/camel/camel-route-resource.ts
Follow up of: https://github.com/KaotoIO/kaoto-next/pull/398#discussion_r1402249390
Fixes: https://github.com/KaotoIO/kaoto-next/issues/334
Thanks once again @tplevko for catching this up.
> fix(catalog): Avoid adding a doFinally when already exists

- packages/camel-catalog/kaoto-camel-catalog-maven-plugin/src/main/java/io/kaoto/camelcatalog/CamelCatalogProcessor.java
- packages/ui/src/components/IconResolver/IconResolver.test.tsx
- packages/ui/src/components/IconResolver/IconResolver.tsx
- packages/ui/src/models/camel-catalog-index.ts
- packages/ui/src/models/catalog-kind.ts
- packages/ui/src/providers/catalog-tiles.provider.tsx
- packages/ui/src/providers/catalog.provider.tsx
Currently, we're loading the short version of the Camel Models Catalog to not only populate the UI catalog but also as a lookup registry when building the Configuration Form.
This is not ideal since having fewer elements in the catalog also means fewer available definitions, rendering some processors not configurable.
This pull request loads both catalogs and uses the short list to build the UI Catalog and the full one for the lookup.
This pull request is a follow up of https://github.com/KaotoIO/kaoto-next/pull/404
> chore(catalog): Load both full and filtered Camel Catalog

- packages/ui/src/components/Visualization/Custom/ItemReplaceNode.tsx
- packages/ui/src/models/visualization/flows/support/camel-component-default.service.ts
Currently, when replacing the `from` node with a source `Kamelet` adds it incorrectly as it doesn't prefix the URI with the `kamelet` string.
Add `kamelet:` prefix to `Kamelets` nodes
| #### Before | #### After |
| --- | --- |
| ![image](https://github.com/KaotoIO/kaoto-next/assets/16512618/cf1a9285-434e-4f7d-b93f-9c4d03411dff) | ![image](https://github.com/KaotoIO/kaoto-next/assets/16512618/e2a056cc-a0ae-4943-8ff8-c1df424c4d37) |
Fixes: https://github.com/KaotoIO/kaoto-next/issues/409
> fix(canvas): Missing Kamelet icons in the from node

- packages/ui-tests/cypress/e2e/beans.cy.ts
- packages/ui-tests/cypress/e2e/errorHandler.cy.ts
- packages/ui-tests/cypress/fixtures/flows/ErrorHandlerPipe.yaml
- packages/ui-tests/cypress/fixtures/flows/MetadataPipe.yaml
- packages/ui-tests/cypress/support/next-commands/default.ts
Coverage for error handler.
Also reflected the beans fix in e2e test - https://github.com/KaotoIO/kaoto-next/issues/245
> e2e: add error handler e2e coverage

- packages/ui/src/models/visualization/flows/camel-route-visual-entity.ts
Currently, there's a piece of logic that checks if the node meant to be replaced has a single `step` property that can have children. This logic was causing that for some special nodes, like `doCatch`, the replace step functionality didn't work, and the intended replacement step gets appended instead.
The fix is to remove said functionality as it was already implemented in a different manner.
There are more changes to make, as an example, `doCatch` and `doFinally` shouldn't be offered as valid EIP if they are not inside of a `doTry`. Another topic is that special children shouldn't be replaced, for instance, `when`, `otherwise`, `doCatch` and `doFinally`.
Fixes: https://github.com/KaotoIO/kaoto-next/issues/370
> fix(canvas): Replace nodes that contains a single steps property don't work

- .github/workflows/build-lint-test.yml
- .github/workflows/chromatic.yml
- .github/workflows/create-pre-release-pr.yml
- .github/workflows/deploy-to-gh-pages.yml
- .github/workflows/e2e-tests.yml
- .github/workflows/release-and-publish.yml
- packages/camel-catalog/pom.xml
Java 21 is the latest LTS
Java is used internally so we can upgrade without external impact. it will allow easier maintenance and more power.
> Use Java 21 instead of Java 17

- packages/ui/src/components/Visualization/ContextToolbar/FlowType/FlowTypeSelector.test.tsx
- packages/ui/src/components/Visualization/ContextToolbar/FlowType/FlowTypeSelector.tsx
- packages/ui/src/models/camel/__snapshots__/camel-resource.test.ts.snap
- packages/ui/src/models/camel/__snapshots__/kamelet-resource.test.ts.snap
- packages/ui/src/models/camel/camel-k-resource.ts
- packages/ui/src/models/camel/camel-resource.test.ts
- packages/ui/src/models/camel/camel-resource.ts
- packages/ui/src/models/camel/camel-route-resource.test.ts
- packages/ui/src/models/camel/camel-route-resource.ts
- packages/ui/src/models/camel/kamelet-resource.test.ts
- packages/ui/src/models/camel/kamelet-resource.ts
- packages/ui/src/models/camel/pipe-resource.ts
- packages/ui/src/models/kamelets-catalog.ts
- packages/ui/src/models/visualization/flows/flow-templates-service.ts
- packages/ui/src/models/visualization/flows/support/camel-component-filter.service.test.ts
- packages/ui/src/models/visualization/flows/support/camel-component-filter.service.ts
- packages/ui/src/models/visualization/flows/templates/kamelet.ts
- packages/ui/src/stubs/beer-source-kamelet.ts
- packages/ui/src/stubs/xj-template-action.kamelet.ts
This commit adds basic support for Kamelets canvas flow.
There are still pending topics that will be handled in upcoming pull requests, such as:
* Dependency array management
* Metadata configuration (f.i. Icon, Title, Annotations, and labels)
Relates to: https://github.com/KaotoIO/kaoto-next/issues/110
> feat(kamelet): Add Flow support for Kamelets

- packages/ui/src/components/Visualization/ContextToolbar/ContextToolbar.scss
- packages/ui/src/components/Visualization/ContextToolbar/ContextToolbar.tsx
- packages/ui/src/components/Visualization/ContextToolbar/FlowType/FlowTypeSelector.tsx
- packages/ui/src/components/Visualization/ContextToolbar/FlowType/NewFlow.tsx
- packages/ui/src/components/Visualization/ContextToolbar/Flows/FlowsListEmptyState.tsx
- packages/ui/src/components/Visualization/ContextToolbar/Flows/FlowsMenu.tsx
- packages/ui/src/components/Visualization/Visualization.scss
- packages/ui/src/pages/Design/DesignPage.tsx
Improve the style of the canvas' toolbar
* Add spacing around the controls' text
* Reorder controls
* Increase the size of the current flow type
* Remove the Visualization title
| --- | --- |
| ![image](https://github.com/KaotoIO/kaoto-next/assets/16512618/264a9ee1-829c-4d86-9295-fc4b9bb9b6d8) | ![image](https://github.com/KaotoIO/kaoto-next/assets/16512618/b12a2913-3f37-4b2c-979d-4d26ec1823e8) |
Fixes: https://github.com/KaotoIO/kaoto-next/issues/428
> chore(canvas): Improve Canvas toolbar styling

- .github/workflows/create-pre-release-pr.yml
In order to build the changelogs, we need to fetch the previous git tags.
relates: https://github.com/KaotoIO/kaoto-next/issues/420
> chore(actions): Enable fetch-flags property

- packages/ui/src/multiplying-architecture/KaotoEditor.scss
- packages/ui/src/multiplying-architecture/KaotoEditorApp.tsx
- packages/ui/src/multiplying-architecture/KaotoEditorFactory.ts
Currently, the a11y labels are visible despite VSCode not being a screen reader.
This happens because some @patternfly css classes are not being loaded when building for VSCode.
The workaround is to provide the missing class into the KaotoEditor styles.
| --- | --- |
| ![image](https://github.com/KaotoIO/kaoto-next/assets/16512618/0f7a21c8-981f-4b40-936b-3d5589f5171b) | ![image](https://github.com/KaotoIO/kaoto-next/assets/16512618/19e77ccd-4b4b-4d17-a57b-aca023c41a40) |
Fixes: https://github.com/KaotoIO/kaoto-next/issues/442
> fix(vscode): Hide a11y labels

- packages/ui/jest-setup.ts
- packages/ui/jest.config.ts
- packages/ui/src/camel-utils/camel-to-tile.adapter.test.ts
- packages/ui/src/camel-utils/camel-to-tile.adapter.ts
- packages/ui/src/models/camel-catalog-index.ts
- packages/ui/src/models/catalog-kind.ts
- packages/ui/src/providers/catalog-tiles.provider.test.tsx
- packages/ui/src/providers/catalog-tiles.provider.tsx
- packages/ui/src/providers/catalog.provider.test.tsx
- packages/ui/src/providers/catalog.provider.tsx
- packages/ui/src/providers/schemas.provider.test.tsx
- packages/ui/src/providers/schemas.provider.tsx
This commit loads the Kamelet boundaries catalog, which includes `kamelet:source` and `kamelet:sink`.
Relates to: https://github.com/KaotoIO/kaoto-next/issues/110
> feat(kamelets): Load Kamelet boundaries catalog

- packages/ui/src/components/Catalog/Tile.scss
- packages/ui/src/components/Catalog/Tile.tsx
- packages/ui/src/components/Catalog/__snapshots__/Tile.test.tsx.snap
Let me know if that looks better:
fixes #453
> improved the tile information in the catalog with a name

- packages/ui/src/components/Visualization/Canvas/CanvasForm.tsx
- packages/ui/src/components/Visualization/Canvas/__snapshots__/CanvasForm.test.tsx.snap
Fixes: #385
Fixes: #319
Here is what's happening
https://github.com/KaotoIO/kaoto-next/issues/385#issuecomment-1832627798
So instead of storing model and schema as states and relying on `useEffect()` and the re-render triggered with it, make it local variable and try to cache with `useMemo()`. This way the #385 is addressed. But unfortunately #416 is not, would need to address separately.
> fix: expression property is unexpectedly added to the other step

- packages/ui/src/camel-utils/camel-to-tile.adapter.test.ts
- packages/ui/src/camel-utils/camel-to-tile.adapter.ts
- packages/ui/src/components/IconResolver/IconResolver.tsx
- packages/ui/src/models/camel-catalog-index.ts
- packages/ui/src/models/camel/camel-route-resource.test.ts
- packages/ui/src/models/camel/camel-route-resource.ts
- packages/ui/src/models/camel/kamelet-resource.test.ts
- packages/ui/src/models/camel/kamelet-resource.ts
- packages/ui/src/models/catalog-kind.ts
- packages/ui/src/models/visualization/flows/camel-catalog.service.ts
- packages/ui/src/models/visualization/flows/support/camel-component-filter.service.test.ts
- packages/ui/src/models/visualization/flows/support/camel-component-filter.service.ts
- packages/ui/src/models/visualization/flows/support/camel-component-schema.service.ts
- packages/ui/src/providers/catalog-tiles.provider.test.tsx
- packages/ui/src/providers/catalog-tiles.provider.tsx
- packages/ui/src/providers/catalog.provider.test.tsx
- packages/ui/src/providers/catalog.provider.tsx
- packages/ui/src/stubs/index.ts
- packages/ui/src/stubs/tiles.ts
- packages/ui/src/utils/node-icon-resolver.ts
Screencast updated to showcase `kamelet:source` and `kamelet:sink` inside of the `Kamelet` catalog, as the first Tile, when applicable.
[Screencast from 2023-11-30 12-53-51.webm](https://github.com/KaotoIO/kaoto-next/assets/16512618/d1a55bdf-3954-4e8e-a7b1-795d361c6cea)
Relates to: https://github.com/KaotoIO/kaoto-next/issues/110
Fixes: https://github.com/KaotoIO/kaoto-next/issues/462
> feat(kamelets): Offer kamelet:source and kamelet:sink as possible steps

- packages/ui/src/components/Visualization/Canvas/DataFormatEditor.tsx
- packages/ui/src/components/Visualization/Canvas/ExpressionEditor.tsx
Currently, the ExpressionEditor and DataFormatEditor hold stale data about the selected node, hence forcing the node to update with old data.
The issue behaves as the following:
1. The user updates the expression field using the `ExpressionEditor`
2. After that, a change in an endpoint parameter is made
3. Another update is made in the ExpressionEditor At this point, the ExpressionEditor doesn't know the latest change from the endpoint parameters, hence updating the model with stale information and ignoring the pending changes.
The fix is to refresh the data in the ExpressionEditor before making the changes.
This issue will behave the same for the `DataFormatEditor`
fix: https://github.com/KaotoIO/kaoto-next/issues/518
> fix(ExpressionEditor): Fix stale data in Expression Editor

- packages/ui/src/components/MetadataEditor/MetadataEditor.scss
- packages/ui/src/multiplying-architecture/KaotoEditor.scss
- packages/ui/src/multiplying-architecture/Tabs/DesignTab.scss
- packages/ui/src/multiplying-architecture/Tabs/DesignTab.tsx
This commit fixes a styling issue that forces the tabs header to collapse when there is much zoom in VSCode
fix: https://github.com/KaotoIO/kaoto-next/issues/530
> fix(vscode): Zoom collapse tabs

- packages/ui-tests/cypress/e2e/codeEditor/sourceCodeActions.cy.ts
On edge (saw also one case with chrome) - there were for some reason second quotation mark added in the end of the line with ` - simple: '{{?test}}'`, causing failures. Removed the quotation marks, as these are not mandatory. 
(sorry for the bad image quality - just a screen from the GH recording)
> fix(e2e) - edge failing due to multiple quotation marks

- packages/ui/src/components/Catalog/CatalogFilter.tsx
Focus on search bar when switching between catalogs
https://github.com/KaotoIO/kaoto-next/assets/16512618/c99fb75e-addc-4e4a-acc8-c2936840ad3d
https://github.com/KaotoIO/kaoto-next/assets/16512618/a950f3e1-2075-4288-8209-607249489446
> feat(catalog): Focus on search text field after switching groups

- packages/ui/src/App.tsx
- packages/ui/src/components/Visualization/Visualization.tsx
resolves https://github.com/KaotoIO/kaoto-next/issues/303
https://github.com/KaotoIO/kaoto-next/assets/4180208/736a2f9d-16d1-4caa-8ca6-c6785d23975c
> fix(303): persist visible flows when switching tabs

- packages/ui/src/components/Visualization/ContextToolbar/FlowType/NewFlow.tsx
- packages/ui/src/models/visualization/flows/templates/kamelet.ts
- packages/ui/src/models/visualization/flows/templates/pipe.ts
- packages/ui/src/models/visualization/flows/templates/route.ts
- packages/ui/src/multiplying-architecture/KaotoBridge.tsx
- packages/ui/src/providers/source-code.provider.tsx
Currently, when VSCode switch from one integration type to another, for instance, going from a Camel Route to a Kamelet, this change is not persisted until a property is changed.
This happens because the `KaotoBridge` is not subscribed to the `code:updated` event and this is used when changing from one integration type to another.
The fix is to subscribe to that envent. In addition to that, since [this PR](https://github.com/KaotoIO/kaoto-next/pull/541), the `VisibleFlowsProvider` was removed from the `Visualization` component, hence it was breaking the VSCode integration. This PR also adds it to the `KaotoBridge`
fixes: https://github.com/KaotoIO/kaoto-next/issues/402
> fix(vscode): Fix VSCode switching integration type

- packages/ui-tests/cypress/e2e/designer/stepConfiguration.cy.ts
- packages/ui-tests/cypress/support/cypress.d.ts
- packages/ui-tests/cypress/support/next-commands/design.ts
- packages/ui/src/components/Form/CustomAutoField.tsx
- packages/ui/src/components/Form/expression/ExpressionAwareNestField.test.tsx
- packages/ui/src/components/Form/expression/ExpressionAwareNestField.tsx
- packages/ui/src/components/Form/expression/ExpressionField.tsx
- packages/ui/src/components/Form/expression/ExpressionModalLauncher.test.tsx
- packages/ui/src/components/Form/expression/ExpressionModalLauncher.tsx
- packages/ui/src/components/Visualization/Canvas/StepExpressionEditor.test.tsx
- packages/ui/src/components/Visualization/Canvas/StepExpressionEditor.tsx
Fixes: #577
fix: Align Step expression configuration to be modal style
Fixes: #523
fix: Expression property: Show expression string in main config form
Fixes: #568
https://github.com/KaotoIO/kaoto-next/assets/265462/45089899-c8cf-45c9-9a2e-e7130681f0bf
> fix: Missing expression editor for setHeaders EIP

- packages/ui/scripts/get-camel-catalog-files.js
fix: https://github.com/KaotoIO/kaoto-next/issues/598
> fix(windows): Copying Catalog on Windows is not working

- CONTRIBUTING.md
Java 21 is required when building the project. It is used to create the Camel catalog at build time.
> chore: mention requirements to Java 21 in Contributing guide

- packages/camel-catalog/assembly/pom.xml
- packages/camel-catalog/kaoto-camel-catalog-maven-plugin/src/main/java/io/kaoto/camelcatalog/CamelCatalogProcessor.java
- packages/camel-catalog/kaoto-camel-catalog-maven-plugin/src/main/java/io/kaoto/camelcatalog/CamelYamlDslSchemaProcessor.java
- packages/camel-catalog/kaoto-camel-catalog-maven-plugin/src/main/java/io/kaoto/camelcatalog/KaotoCamelCatalogMojo.java
- packages/camel-catalog/kaoto-camel-catalog-maven-plugin/src/test/java/io/kaoto/camelcatalog/CamelCatalogProcessorTest.java
- packages/camel-catalog/kaoto-camel-catalog-maven-plugin/src/test/java/io/kaoto/camelcatalog/CamelYamlDslSchemaProcessorTest.java
- packages/camel-catalog/kaoto-camel-catalog-maven-plugin/src/test/java/io/kaoto/camelcatalog/K8sSchemaProcessorTest.java
- packages/camel-catalog/kaoto-camel-catalog-maven-plugin/src/test/java/io/kaoto/camelcatalog/KameletProcessorTest.java
- packages/ui/src/components/Form/bean/BeanReferenceField.test.tsx
- packages/ui/src/components/Form/bean/NewBeanModal.test.tsx
- packages/ui/src/components/Form/bean/NewBeanModal.tsx
- packages/ui/src/components/Form/expression/expression.service.test.ts
- packages/ui/src/components/Visualization/Canvas/DataFormatEditor.test.tsx
- packages/ui/src/components/Visualization/Canvas/StepExpressionEditor.test.tsx
- packages/ui/src/components/Visualization/Canvas/dataformat.service.test.ts
- packages/ui/src/models/camel-catalog-index.ts
- packages/ui/src/models/catalog-kind.ts
- packages/ui/src/models/visualization/flows/camel-catalog.service.ts
- packages/ui/src/pages/Beans/BeansPage.tsx
- packages/ui/src/providers/catalog.provider.tsx
Fixes: #564
Also
- Remove unused schema usage in ui tests
- Let beans related component use entity catalog instead of the camelYamlDsl sub schema
- Introduced a flag to disable sub schema generation
> fix: Create entity catalog

- packages/ui/jest.config.ts
- packages/ui/tsconfig.json
- packages/ui/tsconfig.node.json
Currently, the `yaml` package is written using ESM modules. This seems to cause an error in Windows environment during unit tests, requiring to transform said modules into CJS modules.
The workaround is to ignore the babel transform for the `yaml` package, effectively parsing it with babel.
> fix(windows): Fix running unit tests in Windows

- packages/ui-tests/cypress/support/next-commands/design.ts
should improve e2e stability - related to https://github.com/KaotoIO/kaoto-next/issues/603 
based on cy recommendation:
```
...
You can typically solve this by breaking up a chain. For example, rewrite:
> `cy.get('button').click().click()`
to
> `cy.get('button').as('btn').click()`
> `cy.get('@btn').click()`
...
```
> fix(603) - e2e stability improvement. cy -breaking up a chain

- packages/ui-tests/stories/canvas/NewBeanModal.stories.tsx
- packages/ui/src/components/Form/bean/index.ts
- packages/ui/src/components/Form/index.ts
- packages/ui/src/public-api.ts
Add storybook story for the new bean modal, which can be now used from the design view for adding new beans.
> add new bean modal story

- packages/ui/src/components/Form/expression/ExpressionModalLauncher.test.tsx
- packages/ui/src/components/Form/expression/ExpressionModalLauncher.tsx
fixes https://github.com/KaotoIO/kaoto-next/issues/619
> fix(619): Update onClose event handler in ExpressionModalLauncher

- packages/ui/src/components/Form/expression/ExpressionEditor.tsx
- packages/ui/src/components/Visualization/Canvas/DataFormatEditor.tsx
fixes https://github.com/KaotoIO/kaoto-next/issues/626
https://github.com/KaotoIO/kaoto-next/assets/4180208/92508826-a739-46c2-a544-1e00786d53f0
> fix(626): add dropbox handler for clicking outside the dropdown

- packages/ui/src/components/Visualization/Canvas/CanvasForm.scss
- packages/ui/src/components/Visualization/Canvas/CanvasForm.tsx
- packages/ui/src/components/Visualization/Canvas/__snapshots__/CanvasForm.test.tsx.snap
Currently, there's not much spacing between form fields for processors.
This commit adds more spacing between them by enforcing the patternfly form spacing.
| --- | --- |
| ![image](https://github.com/KaotoIO/kaoto-next/assets/16512618/3e5153e5-021a-4700-8d23-7074413f4711) | ![image](https://github.com/KaotoIO/kaoto-next/assets/16512618/6e9b21f8-0a59-48fa-a4d1-30ac8cd7c6f4) |
There's a different situation for the nested parameters (forms like `to: timer:myTimer`) since they are not individual forms but rather a child of the main one, so the layout mechanism is different. This will be improved in an upcoming PR.
fix: https://github.com/KaotoIO/kaoto-next/issues/618
> fix(form): Improve vertical spacing for form

- packages/ui/src/models/visualization/flows/abstract-camel-visual-entity.ts
- packages/ui/src/models/visualization/flows/camel-route-visual-entity.ts
- packages/ui/src/models/visualization/flows/kamelet-visual-entity.ts
After creating the AbstractCamelVisualEntiy class, the connection between the BaseVisualCamelEntity and its implementation has been lost due to the Abstract class not implementing the said interface.
This PR updates the Abstract class to implement the interface and also consolidates the `toVizNode` method since it's the same between both `CamelRouteVisualEntity` and `KameletVisualEntity`.
> chore(viz-entity): Restore class hierarchy between Abstract and implementation

- packages/ui/src/components/Visualization/Canvas/CanvasForm.tsx
- packages/ui/src/models/visualization/flows/support/__snapshots__/camel-component-schema.service.test.ts.snap
- packages/ui/src/models/visualization/flows/support/camel-component-schema.service.test.ts
- packages/ui/src/models/visualization/flows/support/camel-component-schema.service.ts
- packages/ui/src/utils/camel-uri-helper.test.ts
- packages/ui/src/utils/camel-uri-helper.ts
- packages/ui/src/utils/get-parsed-value.test.ts
- packages/ui/src/utils/get-parsed-value.ts
Currently, we're not parsing the URI field from the `from`, `to`, and the `toD` Camel processors.
This pull request adds support for the URI field in the following fashion:
Considering the following `URI`: `timer:timer-1?period=5000&delay=5&synchronous=true`, when configuring the `timer` component, we parse the `URI` using the component's syntax (in this case is `timer:timerName`) and set those values in the parameter object. After the parsing, the `URI` field is cleaned to avoid overriding the parameter's value again. The result of this parsing is: `{ timerName: 'timer-1', period: 5000, delay: 5, synchronous: true }`.
In addition to that, we're hiding the URI field to prevent the user from manipulating it for the time being. This decision needs to be revisited later to check how can …
> feat(form): Parse URI field upon configuring step

- packages/ui/src/components/Visualization/Canvas/CanvasForm.tsx
- packages/ui/src/components/Visualization/Canvas/__snapshots__/CanvasForm.test.tsx.snap
fixes https://github.com/KaotoIO/kaoto-next/issues/309
@lordrip I tried both - the `<pre>` with `<code>` and the PF `CodeBlock` - I believe using `CodeBlock` the yaml code gets more highlighted, but I can change to the originally proposed solution.
Also I wanted to ask, whether we should add some info, regarding the displayed block of code - I was thinking about, to be consistent - something like [FieldLabelIcon](https://github.com/KaotoIO/kaoto-next/blob/091655c5f92744596d96173885d34fefeab53539/packages/ui/src/components/Form/FieldLabelIcon.tsx#L17) qestionmark with popover, containing information, regarding the displayed yaml and some info, regarding the node itself - that the name is not correct and needs to be changed in source code, or replaced in the canvas. 
Let me know, what do …
> fix(309): Add codeblock to unknown node

- packages/ui-tests/cypress/e2e/designer/branchingStepAddition.cy.ts
- packages/ui/src/hooks/entities.ts
- packages/ui/src/models/camel/camel-k-resource.ts
- packages/ui/src/models/camel/camel-resource.ts
- packages/ui/src/models/camel/camel-route-resource.ts
- packages/ui/src/utils/__snapshots__/create-camel-properties-sorter.test.ts.snap
- packages/ui/src/utils/create-camel-properties-sorter.test.ts
- packages/ui/src/utils/create-camel-properties-sorter.ts
- packages/ui/src/utils/index.ts
Currently, the order assigned to the YAML output is determined through the order of the properties' definition, meaning that for an object with a single `id` property, after creating another property, the order will be:
```yaml
id: something
anotherProperty: something else
```
Ideally, we should follow a consistent order to simplify the diffing between the route's versions.
This commit adds an intermediate step that sorts the parameters in the following order:
```
*   1. `id` prop
*   2. `description` prop
*   3. `uri` prop
*   4. `parameters` prop
*   5. `steps` prop
*   6. the remaining properties in alphabetical order
```
Later on, we might want to sort the `parameters` object using the order defined in the Camel Catalog.
* Inspired by: https://github.com/eemeli/yaml/issues/44
fix: …
> feat(sourcecode): Sort Camel Routes parameters

- packages/ui/src/models/visualization/flows/pipe-visual-entity.test.ts
- packages/ui/src/models/visualization/flows/pipe-visual-entity.ts
- packages/ui/src/models/visualization/flows/support/__snapshots__/kamelet-schema.service.test.ts.snap
- packages/ui/src/models/visualization/flows/support/kamelet-schema.service.test.ts
- packages/ui/src/models/visualization/flows/support/kamelet-schema.service.ts
Currently, `Pipe`'s properties are being set inside the `ref` property, which is not correct.
This commit updates the logic to set the `properties` in the root `properties` property.
fix: https://github.com/KaotoIO/kaoto-next/issues/653
> fix(pipe): Set Pipe's properties in the right place

- packages/ui/src/models/camel/__snapshots__/camel-resource.test.ts.snap
- packages/ui/src/models/camel/__snapshots__/kamelet-resource.test.ts.snap
- packages/ui/src/models/camel/kamelet-resource.ts
- packages/ui/src/models/visualization/flows/templates/kamelet.ts
Currently, Kamelets' nodes can't be edited using the Canvas Form, causing the changes made by the user, are not serialized into the source code.
This bug was caused due to a problem in the serialization of the `KameletResource`, because despite the `Canvas Form` editing the `KameletVisualEntity` correctly, what ultimately was serialized was the original `Kamelet` without changes.
The fix is to ensure that we're serializing the
`KameletVisualEntity.from` as part of the resulting `KameletResource.toJSON()` method.
This change opens up a more broad topic about `Kamelets`, at this moment, the `KameletVisualEntity` class has knowledge about the underlying flow (`kamelet.spec.template.from`) and its metadata (`kamelet.metadata`), and this shouldn't be the case.
Ideally, `KameletVisualEntity` …
> fix(kamelets): Edit Kamelets' nodes properties

- packages/ui/src/models/visualization/flows/support/camel-component-schema.service.ts
- packages/ui/src/utils/camel-uri-helper.test.ts
- packages/ui/src/utils/camel-uri-helper.ts
There are special cases where some URI parameters are not required, so the user didn't provide them.
This is the case for the `jms`, `amqp`, and `activemq` components, where the `destinationType` is not required so that the user can provide the `destinationName` directly.
In this situation, if the values array length matches the required parameters array length, we can remove the non-required keys to match the values with the keys.
fix: https://github.com/KaotoIO/kaoto-next/issues/654
> fix(form): Ignore non-required URI parameters

- packages/camel-catalog/assembly/src/main/resources/schemas/PipeErrorHandler.json
fixes https://github.com/KaotoIO/kaoto-next/issues/656
descriptions used from `camelYamlDsl-errorHandler.json`
```
"maximumRedeliveries" : {
"type" : "number",
"title" : "Maximum Redeliveries",
"description" : "Sets the maximum redeliveries x = redeliver at most x times 0 = no redeliveries -1 = redeliver forever"
},
"maximumRedeliveryDelay" : {
"type" : "string",
"title" : "Maximum Redelivery Delay",
"description" : "Sets the maximum delay between redelivery"
```
> Add help fields for error handler

- packages/ui/package.json
- packages/ui/src/layout/Navigation.tsx
- packages/ui/src/layout/navigation.models.ts
- yarn.lock
**Fix**: https://github.com/KaotoIO/kaoto-next/issues/670
This PR adds the functionality to hide elements in the navigation bar.
The following are the screenshots showcasing the implementation:
1. Rest nav item _visible_ - current
2. Rest nav item _hidden_ - expected
**Additional**
- I also expanded the functionality to hide `NestedNavElement`
- and nested elements
I hope this helps and kindly let me know if there's another preferred approach. 🙏
> feat: Hide navigation items

- packages/ui/src/models/camel/camel-route-resource.test.ts
- packages/ui/src/models/visualization/flows/camel-catalog.service.test.ts
- packages/ui/src/models/visualization/flows/camel-catalog.service.ts
- packages/ui/src/models/visualization/flows/support/camel-component-schema.service.test.ts
- packages/ui/src/models/visualization/flows/support/camel-component-schema.service.ts
- packages/ui/src/utils/camel-uri-helper.test.ts
- packages/ui/src/utils/camel-uri-helper.ts
Currently, kamelet's are not recognized when they have parameters within URI.
This commit fixes that situation by splitting the query parameters from the name and also parses it to apply it to the parameters object.
fix: https://github.com/KaotoIO/kaoto-next/issues/657
comes from: #664
> fix(form): Improve URI parsing for Kamelets

- packages/camel-catalog/assembly/src/test/java/io/kaoto/camelcatalog/IndexTest.java
- packages/camel-catalog/kaoto-camel-catalog-maven-plugin/src/main/java/io/kaoto/camelcatalog/KaotoCamelCatalogMojo.java
- packages/camel-catalog/kaoto-camel-catalog-maven-plugin/src/main/java/io/kaoto/camelcatalog/Util.java
- packages/camel-catalog/kaoto-camel-catalog-maven-plugin/src/test/java/io/kaoto/camelcatalog/UtilTest.java
- packages/camel-catalog/kaoto-camel-catalog-maven-plugin/src/test/resources/testfile1.txt
- packages/camel-catalog/kaoto-camel-catalog-maven-plugin/src/test/resources/testfile2.txt
- packages/ui/src/components/Form/bean/BeanReferenceField.test.tsx
- packages/ui/src/components/Form/bean/NewBeanModal.test.tsx
- packages/ui/src/components/Form/expression/ExpressionAwareNestField.test.tsx
- packages/ui/src/components/Form/expression/ExpressionEditor.test.tsx
- packages/ui/src/components/Form/expression/ExpressionField.test.tsx
- packages/ui/src/components/Form/expression/ExpressionModalLauncher.test.tsx
- packages/ui/src/components/Form/expression/expression.service.test.ts
- packages/ui/src/components/MetadataEditor/PipeErrorHandlerEditor.test.tsx
- packages/ui/src/components/Visualization/Canvas/CanvasForm.test.tsx
- packages/ui/src/components/Visualization/Canvas/DataFormatEditor.test.tsx
- packages/ui/src/components/Visualization/Canvas/LoadBalancerEditor.test.tsx
- packages/ui/src/components/Visualization/Canvas/StepExpressionEditor.test.tsx
- packages/ui/src/components/Visualization/Canvas/dataformat.service.test.ts
- packages/ui/src/components/Visualization/Canvas/loadbalancer.service.test.ts
- packages/ui/src/models/visualization/flows/camel-catalog.service.test.ts
- packages/ui/src/models/visualization/flows/support/camel-component-schema.service.test.ts
- packages/ui/src/models/visualization/flows/support/kamelet-schema.service.test.ts
- packages/ui/src/models/visualization/flows/support/model-validation.service.test.ts
- packages/ui/src/providers/catalog-tiles.provider.test.tsx
- packages/ui/src/providers/catalog.provider.test.tsx
> fix: Hash Camel Catalog files

- packages/ui-tests/cypress/e2e/codeEditor/malformedFlows.cy.ts
- packages/ui/src/components/Visualization/Canvas/Canvas.test.tsx
- packages/ui/src/components/Visualization/Canvas/Canvas.tsx
- packages/ui/src/components/Visualization/Canvas/__snapshots__/Canvas.test.tsx.snap
- packages/ui/src/components/Visualization/ContextToolbar/FlowType/NewFlow.tsx
- packages/ui/src/components/Visualization/EmptyState/VisualizationEmptyState.test.tsx
- packages/ui/src/components/Visualization/EmptyState/VisualizationEmptyState.tsx
- packages/ui/src/components/Visualization/EmptyState/index.ts
- packages/ui/src/stubs/TestProvidersWrapper.tsx
- packages/ui/src/stubs/index.ts
Currently, when the canvas is empty, because there are no flows defined or because there are but hidden, we see a gray area. This might present an issue for the users, starting with a blank file in VSCode, as it's not clear what's the first step to start working with the app.
This commit introduces a placeholder in case there are no flows or there are but not visible
fix: https://github.com/KaotoIO/kaoto-next/issues/362
> feat(canvas): Show placeholder when there are no visible flows

- packages/ui-tests/cypress/fixtures/flows/ComplexKamelet.yaml
Attempt to improve e2e stability. Removed not yet supported `pipeline` nested step from the fixture. Wasn't able to reproduce locally and the failure doesn't tell much, so hope this was the cause.
The random failure occurring in branchingStepAddition test was following:
> e2e - try to remove branchingStepAddition test flakiness

- packages/ui/src/components/Visualization/Visualization.tsx
Currently, if there's an error during a flow parsing, an error message is shown to the user to explain what happens and suggest checking the source code. In the VSCode extension, the canvas doesn't refresh after an error, causing the editor to be stuck until the user closes the extension and reopens it again or switches to another tab.
This commit addresses this issue by assigning a `key` property to the error boundary component, so it gets refreshed after an entity update that happens only after editing the source code.
fix: https://github.com/KaotoIO/kaoto-next/issues/714
> fix(canvas): Refresh canvas after error

- packages/ui/src/components/Form/expression/ExpressionModalLauncher.scss
- packages/ui/src/components/Form/expression/ExpressionModalLauncher.tsx
Visual and styling improvements for `ExpressionModalLauncher` field.
fix: https://github.com/KaotoIO/kaoto-next/issues/713
> fix(expression): UI improvements for `Expression`

- packages/ui/src/components/Visualization/Canvas/CanvasForm.tsx
Currently, using the following order works:
1. Add a `setHeaders` step
2. Configure the `name` property
3. Configure the `expression` field
Now, it's not the case when going in the opposite direction.
This happens because when starting with an empty `setHeaders` step, both the `Form` and the `ExpressionField` don't have any information and they start with an empty object.
After configuring the `ExpressionField`, the `Form` still doesn't know about the recently configured expression, and since the `Form` operates in an entire-object-update fashion, it removes the already configured `expression`.
The opposite doesn't happen because the `ExpressionField` checks the latest definition before updating it.
The workaround is to perform single-property operations in the `Form`, this way, the …
> fix(Form): Expression field lose its values

- packages/ui/src/components/Visualization/Canvas/CanvasForm.tsx
After changing the way how `AutoForm` updates the node's models, nested schemas, like the one used by `setHeader` no longer work as the key of the property being changed is expressed using the `.` (dot) notation.
As an example: `headers.0.expression`
This means that we can't use the `key` as it is to set the values, as it won't achieve the expected result.
The fix is to use `lodash/set` to navigate through the path and assign the value in the right place.
fix: https://github.com/KaotoIO/kaoto-next/issues/727
> fix(setHeaders): Fix broken setHeaders processor

- packages/ui/src/components/Visualization/ContextToolbar/FlowType/NewFlow.tsx
> fix(716): X icon in New Route modal doesn't close the modal

- packages/ui/src/components/Visualization/Canvas/CanvasForm.scss
- packages/ui/src/components/Visualization/Canvas/CanvasForm.tsx
- packages/ui/src/components/Visualization/Canvas/CanvasSideBar.scss
- packages/ui/src/components/Visualization/Canvas/CanvasSideBar.tsx
- packages/ui/src/components/Visualization/Canvas/__snapshots__/CanvasForm.test.tsx.snap
Currently, the entire `CanvasForm` scrolls, forcing the title and the close icon to be lost.
This commit makes the `Title` sticky, so it can always be visible while the `CanvasForm` can be scrolled.
https://github.com/KaotoIO/kaoto-next/assets/16512618/a40b1410-0f6e-4f89-974f-9a4756859034
https://github.com/KaotoIO/kaoto-next/assets/16512618/fec8568c-341c-45a7-82c7-87c4f8cfb8e4
fix: https://github.com/KaotoIO/kaoto-next/issues/682
> feat(CanvasForm): Make title sticky

- packages/ui/src/components/Form/CustomAutoField.test.tsx
- packages/ui/src/components/Form/CustomAutoField.tsx
- packages/ui/src/components/Form/customField/CustomSelectField.tsx
- packages/ui/src/components/Form/customField/TypeaheadField.test.tsx
- packages/ui/src/components/Form/customField/TypeaheadField.tsx
fix: https://github.com/KaotoIO/kaoto-next/issues/677
fix: https://github.com/KaotoIO/kaoto-next/issues/512
With the [typeahead with create](https://www.patternfly.org/components/menus/select/react/typeahead-with-create-option/) 
https://github.com/KaotoIO/kaoto-next/assets/4180208/f6d19c26-0cb6-413e-9258-430f4898f8a0
> fix(677) enable users to enter text into drop down boxes

- packages/ui/src/components/Form/bean/BeanReferenceField.tsx
- packages/ui/src/components/Form/bean/NewBeanModal.test.tsx
- packages/ui/src/components/Form/bean/NewBeanModal.tsx
- packages/ui/src/models/camel/__snapshots__/kamelet-resource.test.ts.snap
- packages/ui/src/models/camel/camel-resource.ts
- packages/ui/src/models/camel/kamelet-resource.test.ts
- packages/ui/src/models/camel/kamelet-resource.ts
- packages/ui/src/models/kamelets-catalog.ts
- packages/ui/src/models/visualization/metadata/beans-entity-handler.test.ts
- packages/ui/src/models/visualization/metadata/beans-entity-handler.ts
- packages/ui/src/models/visualization/metadata/routeTemplateBeansEntity.ts
- packages/ui/src/multiplying-architecture/KaotoEditor.tsx
- packages/ui/src/pages/Beans/BeansPage.tsx
> feat: Support Kamelet Beans

- .github/workflows/release-pipeline.yml
> Added Release pipeline action

- packages/ui/src/components/Catalog/BaseCatalog.scss
- packages/ui/src/components/Catalog/BaseCatalog.tsx
- packages/ui/src/components/Catalog/Catalog.scss
- packages/ui/src/components/Catalog/Catalog.tsx
- packages/ui/src/providers/catalog-modal.provider.scss
- packages/ui/src/providers/catalog-modal.provider.tsx
fixes https://github.com/KaotoIO/kaoto-next/issues/702
https://github.com/KaotoIO/kaoto-next/assets/4180208/0c7edd6c-24f1-4a54-a4f7-5743d5355b96
> fix(702): static catalog filter at the top of page

- packages/ui/src/components/Visualization/Canvas/CanvasForm.scss
This change is related to fix #695. Here we moved the canvas forms field spacing related styling to uniforms-patternfly!
Check this for further details: https://github.com/KaotoIO/uniforms-patternfly/pull/73
> fix: Moved forms field spacing related styling to uniforms-patternfly

- packages/ui/src/models/catalog-kind.ts
This commit adds a brief description to the `CatalogKind` enum to understand what's available on each Catalog kind.
The advantage of doing so is the description appears when hovering over the usage
> chore(catalog): Add description to `CatalogKind`

- packages/ui/src/components/Form/schema.service.test.ts
- packages/ui/src/components/Form/schema.service.ts
- packages/ui/src/components/Visualization/Canvas/CanvasForm.tsx
Currently, if a schema field cannot be resolved by using the `$ref` keyword, `ajv` throws an exception, making the `CanvasForm` unusable.
In addition to that, the `form` field has been removed from the `CanvasForm` as is meant to be rendered by the `Canvas` itself.
> fix(ajv): Avoid ajv throw exception for unresolved fields

- packages/ui/src/utils/get-value.test.ts
- packages/ui/src/utils/get-value.ts
- packages/ui/src/utils/index.ts
- packages/ui/src/utils/node-icon-resolver.ts
- packages/ui/src/utils/set-value.test.ts
- packages/ui/src/utils/set-value.ts
This commit adds `getValue` and `setValue` utils, leveraging the existing `lodash.get` and `lodash.set` respectively in order to support `#` as a `ROOT_PATH`.
> feat(utils): Add get-value and set-value utils

- packages/ui/jest-setup.ts
- packages/ui/jest.config.ts
Currently, there are no mocks for `SVGElement`'s methods, like `getBBox`.
This commit adds a few of them and also moves the `jest-canvas-mock` package to the `setupFiles` array so it's loaded during the environment configuration.
> chore(tests): Enable SVG mocks

- packages/ui/src/components/Form/schema.service.ts
- packages/ui/src/components/Visualization/Canvas/CanvasForm.test.tsx
- packages/ui/src/components/Visualization/Canvas/CanvasForm.tsx
- packages/ui/src/components/Visualization/Canvas/__snapshots__/Canvas.test.tsx.snap
- packages/ui/src/components/Visualization/Canvas/canvas.service.test.ts
- packages/ui/src/components/Visualization/Canvas/canvas.service.ts
- packages/ui/src/components/Visualization/Custom/CustomGroup.tsx
- packages/ui/src/components/Visualization/Custom/CustomNode.tsx
- packages/ui/src/components/Visualization/Custom/index.ts
- packages/ui/src/components/Visualization/EmptyState/VisualizationEmptyState.test.tsx
- packages/ui/src/models/visualization/base-visual-entity.ts
- packages/ui/src/models/visualization/flows/abstract-camel-visual-entity.ts
- packages/ui/src/models/visualization/flows/camel-route-visual-entity.test.ts
- packages/ui/src/models/visualization/flows/kamelet-visual-entity.test.ts
- packages/ui/src/models/visualization/flows/kamelet-visual-entity.ts
- packages/ui/src/models/visualization/flows/support/__snapshots__/camel-component-schema.service.test.ts.snap
- packages/ui/src/models/visualization/flows/support/camel-component-schema.service.test.ts
- packages/ui/src/models/visualization/flows/support/camel-component-schema.service.ts
- packages/ui/src/models/visualization/visualization-node.test.ts
Currently, when rendering two routes at the same time, there's no easy way to distinguish one from the other.
This commit adds a root container to each route, with a label to identify them.
fix: https://github.com/KaotoIO/kaoto-next/issues/767
> feat(canvas): Add root containers for Camel Routes

- packages/ui/src/components/Visualization/Canvas/CanvasForm.tsx
- packages/ui/src/components/Visualization/Canvas/__snapshots__/CanvasForm.test.tsx.snap
- packages/ui/src/components/Visualization/Custom/UnknownNode.tsx
fix for https://github.com/KaotoIO/kaoto-next/issues/803
> Add  hint for unknown node type

- package.json
- packages/ui/package.json
- packages/ui/src/components/Visualization/Canvas/__snapshots__/Canvas.test.tsx.snap
- packages/ui/src/components/Visualization/Canvas/canvas.service.ts
- packages/ui/src/components/Visualization/Visualization.scss
- yarn.lock
Currently, the groups are too narrow to the routes, this PR adds padding to the groups.
It also updates `@patternfly/react-topology` to the 5.2.1 patch version which stopped using the add-ons css classes from
`@patternfly/react-core`
| Before | After | 
| --- | --- |
| ![image](https://github.com/KaotoIO/kaoto-next/assets/16512618/7d8f35da-fa53-45b1-9539-dd439403a10e) | ![image](https://github.com/KaotoIO/kaoto-next/assets/16512618/c3857424-631b-4089-a420-77581b903376) |
relates: https://github.com/KaotoIO/kaoto-next/issues/767
> chore(canvas): Add padding to Groups

- packages/ui-tests/cypress/e2e/designer/uriRouteConfig.cy.ts
- packages/ui-tests/cypress/fixtures/flows/UriConfKamelet.yaml
add coverage to URI e2e for the kamelet case - https://github.com/KaotoIO/kaoto-next/pull/672
> e2e: add kamelet URI config tests

- packages/ui/src/models/visualization/flows/pipe-visual-entity.test.ts
- packages/ui/src/models/visualization/flows/pipe-visual-entity.ts
- packages/ui/src/utils/node-icon-resolver.ts
Currently, there's no validation for `Pipe`'s nodes
This commit reuses the existing validator from Camel Routes.
fix: https://github.com/KaotoIO/kaoto-next/issues/698
> fix(canvas): Add Pipe nodes validation

- packages/ui-tests/stories/canvas/Canvas.stories.tsx
Currently, the kamelet's storybook example is using a `CamelRouteVisualEntity` class, and since the `JSON` example doesn't have an id, an automatic one is provided.
This generates a visual diff every time a new PR is created
The fix is to use the appropriate `KameletVisualEntity` class so that we could have a static Id for the example
| Kamelet's storybook example | Visual diff | Kamelet using the appropriate class |
| --- | --- | --- |
| ![image](https://github.com/KaotoIO/kaoto-next/assets/16512618/542a60dc-4bce-4c39-9208-80f4a974846b) | ![image](https://github.com/KaotoIO/kaoto-next/assets/16512618/9808cbc7-fa51-405e-baad-3e5ec35d68c7) | ![image](https://github.com/KaotoIO/kaoto-next/assets/16512618/44fccfb8-85aa-4ae6-b43d-c63f57627ba7) |
> fix(storybook): Have a static ID for Kamelet

- packages/ui/src/multiplying-architecture/KaotoEditor.scss
part of kaotoio/vscode-kaoto#465
with this PR:
so compared to before, we gain space related to highlighted in the color red, dark blue and a part of purple and light blue with this PR:
> feat(vscode): Gain space for the editor in VS Code

- packages/ui/src/multiplying-architecture/KaotoEditor.scss
- packages/ui/src/multiplying-architecture/KaotoEditor.tsx
based on https://github.com/KaotoIO/kaoto-next/pull/817
With this PR, we now have:
it takes car of the yellow, orange and green:
> 465 gain toolbar space overriding patternfly

- packages/ui/src/components/PropertiesModal/PropertiesModal.tsx
Fix for console error when opening the catalog modal:
> fix - TypeError: props.tab is undefined

- packages/ui/src/multiplying-architecture/KaotoEditor.scss
- packages/ui/src/multiplying-architecture/KaotoEditor.tsx
based on https://github.com/KaotoIO/kaoto-next/pull/818
no more space for scrollbar on design canvas:
and still available on other tabs like Beans:
> 465 Gain unused scrollbar space for design canvas

- packages/ui/src/components/Visualization/Custom/ItemRemoveNode.tsx
- packages/ui/src/components/Visualization/Custom/ItemReplaceNode.tsx
- packages/ui/src/models/visualization/base-visual-entity.ts
- packages/ui/src/models/visualization/flows/abstract-camel-visual-entity.ts
- packages/ui/src/models/visualization/flows/camel-on-exception-visual-entity.ts
- packages/ui/src/models/visualization/flows/pipe-visual-entity.ts
- packages/ui/src/models/visualization/flows/support/camel-component-schema.service.ts
- packages/ui/src/models/visualization/visualization-node.ts
Currently, all canvas nodes have the possibility to be replaced and removed.
This leads to an inconsistent situation in which empty containers can be replaced or removed.
The fix for this situation is to offer the possibility to select whether a node can be replaced or removed, this way, we have a broad range of node interactions.
| Before | After | 
| --- | --- |
| ![image](https://github.com/KaotoIO/kaoto-next/assets/16512618/c43c0ed5-af87-4d72-b7c9-75cb1d08b1b4) | ![image](https://github.com/KaotoIO/kaoto-next/assets/16512618/a6f7c7dc-912b-4102-895f-448b814449d2) |
fix: https://github.com/KaotoIO/kaoto-next/issues/561
> feat(canvas): Add additional node's interactions

- packages/ui/src/components/Form/CustomAutoForm.tsx
- packages/ui/src/components/Form/expression/ExpressionModalLauncher.tsx
- packages/ui/src/components/MetadataEditor/MetadataEditor.tsx
- packages/ui/src/components/Visualization/Canvas/CanvasForm.tsx
Currently, there are 2 different `AutoForm` instances, one from `CanvasForm` and another one from the `MetadataEditor`.
This leads to code duplication and different form behavior depending on which screen is displayed.
This commit updates the `CanvasForm` and `MetadataEditor` components to use the `CustomAutoForm`.
> feat(canvas-form): Use CustomAutoForm

- .github/workflows/build-lint-test.yml
- .github/workflows/chromatic.yml
- .github/workflows/deploy-main.yml
- .github/workflows/e2e-tests.yml
- .github/workflows/release-pipeline.yml
Currently, there's no cache enabled for the `actions/setup-java` GitHub action.
This commit enables it.
> chore(build): Enable maven cache

- packages/ui/src/components/Form/CustomAutoForm.tsx
- packages/ui/src/components/Form/bean/NewBeanModal.test.tsx
- packages/ui/src/components/Form/bean/NewBeanModal.tsx
- packages/ui/src/components/MetadataEditor/MetadataEditor.tsx
fixes https://github.com/KaotoIO/kaoto-next/issues/557
https://github.com/KaotoIO/kaoto-next/assets/4180208/1a325998-aca0-4432-ad36-c15227c6a978
> fix(557) - Enforce required name and type in beans forms

- .github/workflows/vscode-tests.yml
Requirement
- we need to add some (eg TRIGGER_VSCODE_TOKEN) token with `repo` permissions enabled and add it into project secrets. May I ask for help @lordrip ?
unfortunately we cannot use `secrets.GITHUB_TOKEN` because there are limitations for triggering jobs (https://docs.github.com/en/actions/security-guides/automatic-token-authentication#using-the-github_token-in-a-workflow)
> build: Trigger vscode-kaoto tests on push to main branch

- packages/ui/src/components/Form/schema.service.test.ts
- packages/ui/src/hooks/useEntityContext/useEntityContext.test.tsx
continue with fixes for https://github.com/KaotoIO/kaoto-next/issues/801
The rest of the noise from the jest tests is caused by the jest generated canvas DOM not setting some attributes - resulting in "Warning: Received NaN for the `y2` attribute. If this is expected, cast the value to a string."
This is harmless, even though annoying, polluting the test output, can't figure a way to suppress this warning ATM, other than suppressing the warnings altogether.
> fix(801) - remove bit more noise from jest tests

- packages/ui-tests/cypress/e2e/designer/routeBeanConf.cy.ts
- packages/ui-tests/cypress/fixtures/flows/SqlBeansCR.yaml
- packages/ui-tests/cypress/fixtures/flows/SqlBeansKamelet.yaml
- packages/ui-tests/cypress/support/next-commands/design.ts
add coverage for https://github.com/KaotoIO/kaoto-next/pull/757
> e2e(757) - add tests for support for kamelet beans

- packages/camel-catalog/kaoto-camel-catalog-maven-plugin/src/main/java/io/kaoto/camelcatalog/KaotoCamelCatalogMojo.java
Fixes #782 partially,
This change provides the JSON Schema in the Entities Catalog to be later on used by the form.
> feat(catalog): Added Kamelet Configuration schema to Entities Catalog

- packages/ui/src/components/PropertiesModal/PropertiesModal.scss
- packages/ui/src/components/PropertiesModal/PropertiesModal.tsx
Currently, the Properties Modal size is determined according to its content, meaning that a long list will occupy the entire screen while other tabs might be smaller, effectively changing the size and position of the modal.
The fix for this is to provide a fixed size for the modal, according to the User's viewport.
Ideally, in the future, we should transform the properties modal into a page, which will allow the user to share the link to a specific component and properties. Ideally, it should also contain a breadcrumb to show the user's current location.
| Long list | Short list |
| --- | --- |
| ![image](https://github.com/KaotoIO/kaoto-next/assets/16512618/12747ba4-a64e-4072-a8e2-7a5f9737c93f) | ![image](https://github.com/KaotoIO/kaoto-next/assets/16512618/e5bbde4c-19b2-47b8-a128-27cef1 …
> fix(catalog): Provide fixed size for Properties Catalog

- packages/ui-tests/cypress/e2e/catalog.cy.ts
- packages/ui/package.json
- packages/ui/src/components/Catalog/Catalog.tsx
- packages/ui/src/components/Catalog/CatalogFilter.tsx
- packages/ui/src/components/Catalog/filter-tiles.test.ts
- packages/ui/src/components/Catalog/filter-tiles.ts
- yarn.lock
Currently, when looking for a `saga` component, we see a `Saga` component, but there's also a `Saga` pattern and there's no visual feedback that it exists until we click on the `Pattern` toggle.
This PR adds counters to each toggle, so we can monitor the occurrences in other groups as well.
In addition to that, the lookup is debounced until the user stops writing, in a 500ms window. This helps when writing the first letters of the search term, it doesn't get stuck until the UI renders.
https://github.com/KaotoIO/kaoto-next/assets/16512618/e10b5349-a301-436a-9358-f859398dd47d
fix: https://github.com/KaotoIO/kaoto-next/issues/745
> feat(catalog): Add tile counters

- packages/ui/src/components/Visualization/Canvas/CanvasForm.tsx
- packages/ui/src/utils/set-value.test.ts
- packages/ui/src/utils/set-value.ts
Currently, the uniforms library, initializes object fields with empty objects when there's a required property inside them.
This is prevented by checking the value of the incoming change in the CanvasForm component, and while this works, it collides with the Kamelet's custom form, since the user might want to remove all annotations, leaving the form with an intended empty object.
The fix for this issue is to remove said check and place it in the `setValue` function instead.
The mechanism now is to check whether the value to assign is an empty object, in which case it's replaced with an `undefined` value instead.
This prevents for this value to be serialized into the Source code.
fix: https://github.com/KaotoIO/kaoto-next/issues/878
> fix(CanvasForm): Avoid adding `{}` to the Source code

- packages/camel-catalog/kaoto-camel-catalog-maven-plugin/src/main/java/io/kaoto/camelcatalog/CamelCatalogProcessor.java
- packages/camel-catalog/kaoto-camel-catalog-maven-plugin/src/main/java/io/kaoto/camelcatalog/CamelYamlDSLKeysComparator.java
- packages/camel-catalog/kaoto-camel-catalog-maven-plugin/src/test/java/io/kaoto/camelcatalog/CamelCatalogProcessorTest.java
- packages/camel-catalog/kaoto-camel-catalog-maven-plugin/src/test/java/io/kaoto/camelcatalog/CamelYamlDSLKeysComparatorTest.java
Currently, since the component's schema is generated from the Camel's components catalog, iterating over the properties dictionary, the output is written using the same sorting as well.
Ths is not the case for processors, which are extracted from the Camel YAML DSL schema first, and then decorated with elements from the Camel's catalog.
This commit changes the iteration to be performed from the Camel's processor catalog instead.
Changes:
* Move the `class:xxx` information from `$comment` to `format`
* Move the `duration` information from `$comment` to `format`
* Add `format: password` for `secret: true` fields
| --- | --- |
| ![image](https://github.com/KaotoIO/kaoto-next/assets/16512618/c9d5e6f7-253e-46b6-8f87-ddabfa3ff7d8) | …
> feat(catalog): Sort Processor's properties

- packages/ui-tests/cypress/support/next-commands/design.ts
[Step removal tests](https://github.com/KaotoIO/kaoto-next/blob/be65d340592f1dbed7cb2fd5e735014d441b8405/packages/ui-tests/cypress/e2e/designer/stepRemoval.cy.ts#L4) are flaky due to the disappearing `context-menu-item`, which can be hidden after the rerender happens, after previous node removal.
> e2e - fix flaky stepRemoval.cy.ts

- packages/ui-tests/stories/canvas/CanvasSideBar.stories.tsx
- packages/ui/package.json
- packages/ui/src/components/Form/CustomAutoForm.tsx
- packages/ui/src/components/Form/schema.service.test.ts
- packages/ui/src/components/Form/schema.service.ts
- packages/ui/src/components/MetadataEditor/MetadataEditor.tsx
- packages/ui/src/components/Visualization/Canvas/CanvasForm.tsx
- packages/ui/src/hooks/index.ts
- packages/ui/src/hooks/schema-bridge.hook.test.tsx
- packages/ui/src/hooks/schema-bridge.hook.tsx
- packages/ui/src/hooks/useEntityContext/useEntityContext.test.tsx
- packages/ui/src/models/camel/entities/base-entity.ts
- packages/ui/src/models/visualization/flows/camel-on-exception-visual-entity.ts
- packages/ui/src/models/visualization/metadata/pipeErrorHandlerEntity.ts
- packages/ui/src/providers/schema-bridge.provider.test.tsx
- packages/ui/src/providers/schema-bridge.provider.tsx
- yarn.lock
Currently, we need to create a `JSONSchemaBridge` to use a schema with uniforms.
This commit creates a new `SchemaBridgeProvider` so the handling and creation of the bridge are consolidated in a single place, leaving the consumer to provide only a desired schema to the form.
relates: https://github.com/KaotoIO/kaoto-next/issues/560
> chore(form): Add SchemaBridge provider

- packages/ui/src/models/visualization/flows/abstract-camel-visual-entity.test.ts
- packages/ui/src/models/visualization/flows/abstract-camel-visual-entity.ts
- packages/ui/src/models/visualization/flows/kamelet-visual-entity.ts
- packages/ui/src/models/visualization/flows/support/camel-component-schema.service.test.ts
- packages/ui/src/models/visualization/flows/support/camel-component-schema.service.ts
- packages/ui/src/utils/camel-uri-helper.test.ts
- packages/ui/src/utils/camel-uri-helper.ts
Currently, only the component name gets serialized into the URI string, the remaining parameters ar serialized in the parameters dictionary as follows:
```yaml
- from:
uri: timer
parameters:
period: "1000"
timerName: template
```
While this works for the Camel CLI, CamelK doesn't support this schema at the moment, causing the deployment to fail.
This commit writes the path parameters into the URI string, in order to support CamelK deployments, f.i.:
```yaml
- from:
uri: timer:template
parameters:
period: "1000"
```
fixes: https://github.com/KaotoIO/kaoto-next/issues/884
> feat(sourcecode): Serialize URI string

- .github/workflows/chromatic.yml
fixes https://github.com/KaotoIO/kaoto-next/issues/883
added `paths-ignore` for the cypress directory - based [on docs](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onpushpull_requestpull_request_targetpathspaths-ignore), this should cause ignoring additions solely to ui-tests
also should ignore while the PR is in `draft` state
> Chore - add rules to limit the chromatic action triggering

- packages/ui/src/components/SourceCode/SourceCode.tsx
After loading the SourceCode editor, a specific schema is applied to the Monaco editor.
The problem with this is that going back and forth between the SourceCode page and any other page, causes the schema to be loaded multiple times, as the workers are not disposed of.
The fix is to dispose of the workers when leaving the SourceCode page.
fix: https://github.com/KaotoIO/kaoto-next/issues/833
> fix(SourceCode): Avoid loading Schema multiple times

- .github/workflows/chromatic.yml
fixes issue with the triggering chromatic action on converting `Draft`  to `Ready for review` discovered here -https://github.com/KaotoIO/kaoto-next/pull/914
Based on discussion and recommendation from here - https://github.com/orgs/community/discussions/25722#discussioncomment-3248917
> Fix chromatic not triggering on change to "ready for review"

- packages/ui/src/components/Form/dataFormat/DataFormatEditor.scss
- packages/ui/src/components/Form/dataFormat/DataFormatEditor.tsx
- packages/ui/src/components/Form/loadBalancer/LoadBalancerEditor.scss
- packages/ui/src/components/Form/loadBalancer/LoadBalancerEditor.tsx
- packages/ui/src/pages/Metadata/MetadataPage.tsx
partial fix for https://github.com/KaotoIO/kaoto-next/issues/718
specifically fixing the part:
`there is a different vertical spacing between the drop down and the follow up fields then between all the other fields`
here is the situation before and after:
>  fix(718): Data Format and LoadBalance config field spacing

- packages/ui-tests/cypress/support/next-commands/design.ts
- packages/ui/package.json
- packages/ui/src/components/Form/CustomAutoField.tsx
- packages/ui/src/components/Form/expression/ExpressionAwareNestField.test.tsx
- packages/ui/src/components/Form/expression/ExpressionField.test.tsx
- packages/ui/src/components/Form/expression/ExpressionModalLauncher.test.tsx
- packages/ui/src/components/Visualization/Canvas/CanvasForm.test.tsx
- yarn.lock
fixes https://github.com/KaotoIO/kaoto-next/issues/892
> fix(892): use a LongTextField for Expression field

- package.json
- packages/ui/package.json
- yarn.lock
Currently, `YAML` schemas are not working when upgrading to `@patternfly/react-code-editor` 5.2.
Downgrading the library until we can provide a fix for this situation.
relates: https://github.com/KaotoIO/kaoto-next/issues/943
> fix(SourceCode): Downgrade @patternfly/react-code-editor

- packages/ui/src/components/Visualization/Custom/ItemAddNode.tsx
- packages/ui/src/components/Visualization/Custom/ItemInsertChildNode.tsx
- packages/ui/src/components/Visualization/Custom/ItemRemoveNode.tsx
- packages/ui/src/components/Visualization/Custom/ItemReplaceNode.tsx
fixes #872 
Work in progress. Points that are not yet solved in a good way:
- `Insert into` is displayed on the first node of an integration but it should only be shown if the node is branchable (can have child nodes, for instance choice, filter, route)
- we should still consider moving some of the actions directly on the nodes (for instance a plus button or minus button for adding and removing) or the connections similar to what Kaoto v1 did but less noisy.
> changed the action labels on nodes to more generic ones

- packages/ui/src/components/Visualization/Canvas/Canvas.tsx
Currently, the Canvas component is missing a property that tells whether the sideBar is open or not. Due to that, when opening the Canvas Form, the Canvas cannot be centered taking in consideration the occupied space from the Side Bar.
relates: https://github.com/KaotoIO/kaoto-next/issues/507
> fix(canvas): Add missing `sideBarOpen` prop to Canvas

- packages/camel-catalog/assembly/src/main/resources/schemas/KameletConfiguration.json
- packages/ui/src/models/kamelets-catalog.ts
- packages/ui/src/utils/get-custom-schema-from-kamelet.test.ts
- packages/ui/src/utils/get-custom-schema-from-kamelet.ts
- packages/ui/src/utils/set-value.test.ts
- packages/ui/src/utils/set-value.ts
- packages/ui/src/utils/update-kamelet-from-custom-schema.test.ts
- packages/ui/src/utils/update-kamelet-from-custom-schema.ts
Added schema for common Properties parameters i.e. 'title', 'description', 'type, 'x-descriptors'. Ref- https://camel.apache.org/camel-k/2.2.x/kamelets/kamelets-user.html#kamelets-specification-definition.
The Form looks like this:
requires: https://github.com/shivamG640/kaoto-next/pull/4
fix: https://github.com/KaotoIO/kaoto-next/issues/880
> fix(schema): Added Properties section to Kamelet Configuration Schema

- packages/ui/src/utils/get-applied-schema-index.test.ts
- packages/ui/src/utils/get-applied-schema-index.ts
- packages/ui/src/utils/get-oneof-schema-list.test.ts
- packages/ui/src/utils/get-oneof-schema-list.ts
- packages/ui/src/utils/get-resolved-schema.test.ts
- packages/ui/src/utils/get-resolved-schema.ts
- packages/ui/src/utils/set-value.test.ts
- packages/ui/src/utils/set-value.ts
- packages/ui/src/utils/weight-schema-properties.test.ts
- packages/ui/src/utils/weight-schema-properties.ts
In order to support errorHandler configuration form, a set of utils are required to handle nested schemas, like the oneOf and anyOf schemas.
relates: https://github.com/KaotoIO/kaoto-next/issues/560
> feat(CanvasForm): Add nested schema utils

- packages/camel-catalog/kaoto-camel-catalog-maven-plugin/src/main/java/io/kaoto/camelcatalog/CamelYamlDslSchemaProcessor.java
- packages/camel-catalog/kaoto-camel-catalog-maven-plugin/src/test/java/io/kaoto/camelcatalog/CamelYamlDslSchemaProcessorTest.java
Extract single OneOf definition from AnyOf definition and put it into the root definitions.
relates: https://github.com/KaotoIO/kaoto-next/issues/948
relates: https://github.com/KaotoIO/kaoto-next/issues/560
> feat(catalog): Remove single OneOf from AnyOf

- packages/ui/src/components/Visualization/Canvas/Canvas.tsx
In small viewports, when opening the `CanvasForm`, there's a chance the selected node gets hidden by it.
This pull request moves the canvas to the left side when opening the `CanvasForm`, so this way we can still see the selected node.
https://github.com/KaotoIO/kaoto-next/assets/16512618/96aa7e16-dc81-4ed2-ad53-5c03df762a72
https://github.com/KaotoIO/kaoto-next/assets/16512618/0b779662-a1af-4556-b77e-ce98e968aed4
fix: https://github.com/KaotoIO/kaoto-next/issues/507
> feat(canvas): Move Canvas to the left

- package.json
- packages/camel-catalog/package.json
- packages/ui-tests/package.json
- packages/ui/package.json
- yarn.lock
Currently, the project has 2 different versions of `typescript`, `5.2.2` and `5.0.4`:
```
├─ @kaoto-next/camel-catalog@workspace:packages/camel-catalog
│  └─ typescript@patch:typescript@npm%3A5.2.2#~builtin<compat/typescript>::version=5.2.2&hash=f3b441 (via patch:typescript@^5.0.2#~builtin<compat/typescript>)
│
├─ @kaoto-next/ui-tests@workspace:packages/ui-tests
│  └─ typescript@patch:typescript@npm%3A5.2.2#~builtin<compat/typescript>::version=5.2.2&hash=f3b441 (via patch:typescript@^5.0.2#~builtin<compat/typescript>)
│
├─ @kaoto-next/ui@workspace:packages/ui
│  └─ typescript@patch:typescript@npm%3A5.2.2#~builtin<compat/typescript>::version=5.2.2&hash=f3b441 (via patch:typescript@^5.0.2#~builtin<compat/typescript>)
│
└─ @microsoft/api-extractor@npm:7.36.4
└─ …
```
> chore(deps): Update typescript

- packages/ui-tests/cypress/fixtures/flows/errorHandlerCR.yaml
- packages/ui/src/components/Form/CustomAutoField.test.tsx
- packages/ui/src/components/Form/CustomAutoField.tsx
- packages/ui/src/components/Form/OneOf/OneOfField.test.tsx
- packages/ui/src/components/Form/OneOf/OneOfField.tsx
- packages/ui/src/components/Form/OneOf/OneOfSchemaList.test.tsx
- packages/ui/src/components/Form/OneOf/OneOfSchemaList.tsx
- packages/ui/src/components/Form/OneOf/__snapshots__/OneOfField.test.tsx.snap
- packages/ui/src/components/Form/OneOf/__snapshots__/OneOfSchemaList.test.tsx.snap
- packages/ui/src/components/Visualization/Canvas/CanvasForm.tsx
- packages/ui/src/components/Visualization/Canvas/__snapshots__/CanvasForm.test.tsx.snap
- packages/ui/src/models/camel/camel-route-resource.ts
- packages/ui/src/models/visualization/flows/camel-error-handler-visual-entity.test.ts
- packages/ui/src/models/visualization/flows/camel-error-handler-visual-entity.ts
Currently, there's partial support for `oneOf` in the `uniforms` library.
This commit adds a new `OneOfField` component that shows a selector to pick which schema should the form generate.
Also, if a model is already defined, the closest schema is selected automatically.
fix: https://github.com/KaotoIO/kaoto-next/issues/560
relates: https://github.com/KaotoIO/kaoto-next/issues/948
Reusing the internal ID will be implemented here: https://github.com/KaotoIO/kaoto-next/issues/962
> feat(CanvasForm): Add support for ErrorHandler

- packages/ui/src/models/camel/camel-route-resource.ts
- packages/ui/src/models/visualization/flows/camel-rest-configuration-visual-entity.test.ts
- packages/ui/src/models/visualization/flows/camel-rest-configuration-visual-entity.ts
- packages/ui/src/stubs/rest-configuration.ts
This commit adds support for the `RestConfiguration` entity.
1. In the source code, start with the following route:
```yaml
- restConfiguration: {}
```
2. Go to the design page
The node validation is still pending due to an issue with the JSONSchema, please see #969 for more details.
fix: https://github.com/KaotoIO/kaoto-next/issues/562
relates: https://github.com/KaotoIO/kaoto-next/issues/969
> feat(restConfiguration): Add restConfiguration entity

- packages/ui-tests/cypress/fixtures/flows/malformed/missingIdRoute.yaml
- packages/ui/src/hooks/entities.test.tsx
- packages/ui/src/models/camel/__snapshots__/camel-resource.test.ts.snap
- packages/ui/src/models/camel/__snapshots__/kamelet-resource.test.ts.snap
- packages/ui/src/models/visualization/flows/templates/kamelet.ts
- packages/ui/src/models/visualization/flows/templates/route.ts
- packages/ui/src/utils/get-custom-schema-from-kamelet.test.ts
- packages/ui/src/utils/update-kamelet-from-custom-schema.test.ts
> Update template to generate route to use path parameters in URI

- packages/ui/src/hooks/entities.test.tsx
- packages/ui/src/hooks/entities.ts
- packages/ui/src/stubs/camel-route-yaml-1.1.ts
Currently, Kaoto serializes to YAML using YAML 1.2.
This creates an edge for the Rest component since one of its parameters (`bindingMode`) accepts an `off` value which ultimately gets serialized as it is, causing it to be interpreted as `false`.
This commit changes the YAML serializing schema to 1.1 so `off` gets serialized as `"off"` avoiding this issue.
fix: https://github.com/KaotoIO/kaoto-next/issues/971
> fix(code): Use YAML 1.1 for serializing

- packages/ui/src/components/Form/customField/CustomNestField.scss
- packages/ui/src/components/Form/customField/CustomNestField.tsx
fixes https://github.com/KaotoIO/kaoto-next/issues/990
related to https://github.com/KaotoIO/kaoto-next/issues/278 
Also based on the decision from yesterdays discussion - removed the filtering for groups, so all will be showed in the sidepanel.
- Update groups filtering - enable all groups in sidepanel
- Reduce the space between the group title and the first field
- Putt Advanced always at the end
> Improvements for grouping in configuration panel

- packages/camel-catalog/kaoto-camel-catalog-maven-plugin/src/main/java/io/kaoto/camelcatalog/CamelCatalogProcessor.java
- packages/camel-catalog/kaoto-camel-catalog-maven-plugin/src/test/java/io/kaoto/camelcatalog/CamelCatalogProcessorTest.java
- packages/camel-catalog/kaoto-camel-catalog-maven-plugin/src/test/java/io/kaoto/camelcatalog/CamelYamlDSLKeysComparatorTest.java
- packages/camel-catalog/kaoto-camel-catalog-maven-plugin/src/test/java/io/kaoto/camelcatalog/CamelYamlDslSchemaProcessorTest.java
- packages/camel-catalog/pom.xml
After updating to Camel 4.5, some tokens were renamed or removed.
[Related PR](https://github.com/apache/camel/pull/13135/files#diff-9e46a8c92d107cc1b4cd595bff2e454dd984d2fe3602ed0e39c756bff1ca8f8a)
> fix(camel-catalog): Rename tokens after upgrading to Camel 4.5

- packages/ui-tests/cypress/e2e/designer/rootContainerConfig/rootContainersConf.cy.ts
- packages/ui/src/components/Visualization/Canvas/__snapshots__/Canvas.test.tsx.snap
- packages/ui/src/components/Visualization/Custom/CustomGroup.tsx
- packages/ui/src/components/Visualization/Custom/ItemRemoveGroup.tsx
Fixes #974 
The Canvas looks like this with the Context menu:
> fix: Added context menu to delete a container

- packages/ui/src/components/Visualization/Canvas/CanvasForm.tsx
- packages/ui/src/models/visualization/base-visual-entity.ts
- packages/ui/src/models/visualization/flows/abstract-camel-visual-entity.ts
- packages/ui/src/models/visualization/flows/camel-error-handler-visual-entity.ts
- packages/ui/src/models/visualization/flows/camel-on-exception-visual-entity.ts
- packages/ui/src/models/visualization/flows/camel-rest-configuration-visual-entity.ts
- packages/ui/src/models/visualization/flows/pipe-visual-entity.ts
Currently, there's a single array to omit form fields, and while this works, in some cases, we could be omitting unintended fields.
The solution is to allow for individual Entities to provide their own omit fields list.
relates to: https://github.com/KaotoIO/kaoto/issues/492
> feat(BaseEntity): Allow individual entities to omit fields

- packages/ui/src/components/Visualization/Canvas/canvas.service.test.ts
- packages/ui/src/components/Visualization/Canvas/canvas.service.ts
Currently, groups only support a single child.
This is not ideal for the `RouteConfiguration` entity since it could have multiple children.
This PR adds support for multiple children in groups.
relates: https://github.com/KaotoIO/kaoto/issues/492
> feat(Canvas): Add support for group children

- packages/ui/src/components/Visualization/Custom/CustomGroup.tsx
- packages/ui/src/components/Visualization/Custom/CustomNode.tsx
- packages/ui/src/components/Visualization/Custom/ItemRemoveGroup.tsx
- packages/ui/src/models/visualization/base-visual-entity.ts
- packages/ui/src/models/visualization/flows/__snapshots__/abstract-camel-visual-entity.test.ts.snap
- packages/ui/src/models/visualization/flows/__snapshots__/camel-on-exception-visual-entity.test.ts.snap
- packages/ui/src/models/visualization/flows/__snapshots__/pipe-visual-entity.test.ts.snap
- packages/ui/src/models/visualization/flows/abstract-camel-visual-entity.test.ts
- packages/ui/src/models/visualization/flows/abstract-camel-visual-entity.ts
- packages/ui/src/models/visualization/flows/camel-error-handler-visual-entity.test.ts
- packages/ui/src/models/visualization/flows/camel-error-handler-visual-entity.ts
- packages/ui/src/models/visualization/flows/camel-on-exception-visual-entity.test.ts
- packages/ui/src/models/visualization/flows/camel-on-exception-visual-entity.ts
- packages/ui/src/models/visualization/flows/camel-rest-configuration-visual-entity.test.ts
- packages/ui/src/models/visualization/flows/camel-rest-configuration-visual-entity.ts
- packages/ui/src/models/visualization/flows/pipe-visual-entity.test.ts
- packages/ui/src/models/visualization/flows/pipe-visual-entity.ts
- packages/ui/src/models/visualization/visualization-node.ts
Currently, expanded and collapsed groups don't have the interactions available, for instance:
* Expanded groups: Only allowed to delete the entire flow
* Collapsed groups: Only allowed to Insert step
This commit consolidates both functionalities where it makes sense, so expanded groups allow the deletion of the flow, and collapsed ones allow to insert step (which expands the group) and the deletion of the entire flow.
Use the following route
```yaml
- onException:
id: onException-2479
- onException:
id: onException-1968
steps:
- to:
id: to-5255
uri: activemq
parameters: {}
```
You should see in both expanded and collapsed groups the `Delete flow` option
relates: https://github.com/KaotoIO/kaoto/issues/492
> feat(Canvas): Consolidate groups interactions

- packages/ui/src/models/visualization/flows/support/camel-component-default.service.test.ts
- packages/ui/src/models/visualization/flows/support/camel-component-default.service.ts
Currently, there's no handling when adding a new `doCatch` element to a `doTry` processor, leading to create a wrong structure.
The fix is to handle this situation so a proper `doCatch` is created at the right position with the correct structure.
fix: https://github.com/KaotoIO/kaoto/issues/1025
> fix(SourceCode): Fix doCatch serialization

- packages/ui/src/models/camel/camel-route-resource.ts
- packages/ui/src/models/visualization/flows/__snapshots__/abstract-camel-visual-entity.test.ts.snap
- packages/ui/src/models/visualization/flows/__snapshots__/camel-intercept-from-visual-entity.test.ts.snap
- packages/ui/src/models/visualization/flows/__snapshots__/camel-intercept-send-to-endpoint-visual-entity.test.ts.snap
- packages/ui/src/models/visualization/flows/__snapshots__/camel-intercept-visual-entity.test.ts.snap
- packages/ui/src/models/visualization/flows/__snapshots__/camel-on-completion-visual-entity.test.ts.snap
- packages/ui/src/models/visualization/flows/abstract-camel-visual-entity.ts
- packages/ui/src/models/visualization/flows/camel-error-handler-visual-entity.test.ts
- packages/ui/src/models/visualization/flows/camel-intercept-from-visual-entity.test.ts
- packages/ui/src/models/visualization/flows/camel-intercept-from-visual-entity.ts
- packages/ui/src/models/visualization/flows/camel-intercept-send-to-endpoint-visual-entity.test.ts
- packages/ui/src/models/visualization/flows/camel-intercept-send-to-endpoint-visual-entity.ts
- packages/ui/src/models/visualization/flows/camel-intercept-visual-entity.test.ts
- packages/ui/src/models/visualization/flows/camel-intercept-visual-entity.ts
- packages/ui/src/models/visualization/flows/camel-on-completion-visual-entity.test.ts
- packages/ui/src/models/visualization/flows/camel-on-completion-visual-entity.ts
- packages/ui/src/models/visualization/flows/camel-route-configuration-visual-entity.ts
- packages/ui/src/models/visualization/flows/camel-route-visual-entity.ts
- packages/ui/src/models/visualization/flows/kamelet-visual-entity.ts
This commit adds support for the `RouteConfiguration` entity.
In detail, the following entities were added:
* intercept
* interceptFrom
* interceptSendToEndpoint
* onCompletion
Also the nested version of said entities were added
fix: https://github.com/KaotoIO/kaoto/issues/492
> feat(RouteConfiguration): Add support for RouteConfiguration entity

- packages/ui/src/components/Visualization/Canvas/CanvasForm.test.tsx
- packages/ui/src/components/Visualization/Canvas/CanvasForm.tsx
Currently, when a string field is touched and later on cleaned, the resulting YAML looks like the following:
```
property: ''
```
This represents an issue since many properties can't be left blank.
This commit avoids serializing empty `''` strings by replacing them with `undefined` instead.
fix: https://github.com/KaotoIO/kaoto/issues/1022
> fix(CanvasForm): Avoid serializing empty strings

- packages/ui/src/components/Visualization/Canvas/Canvas.test.tsx
- packages/ui/src/components/Visualization/Canvas/__snapshots__/Canvas.test.tsx.snap
Add missing test for delete flow functionality through the canvas.
This test was initially created by @shivamG640, it just needed a little touch in terms of the provider.
The issue was that since the `TestProvidersWrapper` provider was used, there was no real access to the underlying camel resource. The fix is to manually provide the camel resource so we can access the real object.
relates: https://github.com/KaotoIO/kaoto/issues/974
> chore(Canvas): Add missing unit test for Canvas.tsx

- packages/ui/src/models/visualization/flows/camel-error-handler-visual-entity.ts
- packages/ui/src/models/visualization/flows/camel-intercept-from-visual-entity.ts
- packages/ui/src/models/visualization/flows/camel-intercept-send-to-endpoint-visual-entity.ts
- packages/ui/src/models/visualization/flows/camel-intercept-visual-entity.ts
- packages/ui/src/models/visualization/flows/camel-on-completion-visual-entity.ts
- packages/ui/src/models/visualization/flows/camel-on-exception-visual-entity.ts
- packages/ui/src/models/visualization/flows/camel-rest-configuration-visual-entity.ts
- packages/ui/src/models/visualization/flows/camel-route-configuration-visual-entity.ts
In order to simplify the construction of new entities, we need to provide a default parameter to the constructor, so the entities can be created on its own.
Related entities:
* ErrorHandler
* Intercept
* InterceptFrom
* InterceptSendToEndpoint
* OnCompletion
* OnException
* RestConfiguration
* RouteConfiguration
relates: https://github.com/KaotoIO/kaoto/issues/1030
> chore(Entities): Add default constructor parameter

- packages/ui/src/components/Form/expression/ExpressionEditor.test.tsx
- packages/ui/src/components/Form/expression/ExpressionEditor.tsx
> fix: Typeahead expression search doesn't hit Bean Method with b

- packages/ui/src/components/Form/expression/ExpressionModalLauncher.test.tsx
- packages/ui/src/components/Form/expression/ExpressionModalLauncher.tsx
> fix: `ExpressionField` shows not configured for expressionless languages

- packages/ui/src/components/Visualization/ContextToolbar/DSLSelector/ChangeDSLModal/ChangeDSLModal.test.tsx
- packages/ui/src/components/Visualization/ContextToolbar/DSLSelector/ChangeDSLModal/ChangeDSLModal.tsx
- packages/ui/src/components/Visualization/ContextToolbar/DSLSelector/DSLSelector.test.tsx
- packages/ui/src/components/Visualization/ContextToolbar/DSLSelector/DSLSelector.tsx
- packages/ui/src/components/Visualization/ContextToolbar/DSLSelector/DSLSelectorToggle/DSLSelectorToggle.test.tsx
- packages/ui/src/components/Visualization/ContextToolbar/DSLSelector/DSLSelectorToggle/DSLSelectorToggle.tsx
- packages/ui/src/models/camel/source-schema-config.ts
In order to create new entities, a DSL Slector component needs to be added.
This commit adds said component divided into 3 sections:
1. `ChangeDSLModal`: A modal to warn the user whenever the DSL is being changed since the existing integration will be removed
2. `DSLSelectorToggle`: The DSL Button itself
3. `DSLSelector`: The main entry point for the DSL Selector, this component is in charge of combining both `DSLSelectorToggle` and the `ChangeDSLModal` components
relates: https://github.com/KaotoIO/kaoto/issues/1030
> feat(CanvasToolbar): Add DSL Selector

- packages/ui-tests/cypress/support/next-commands/design.ts
- packages/ui/src/components/Form/dataFormat/DataFormatEditor.test.tsx
- packages/ui/src/components/Form/dataFormat/DataFormatEditor.tsx
- packages/ui/src/components/Form/expression/ExpressionEditor.tsx
- packages/ui/src/components/Form/loadBalancer/LoadBalancerEditor.test.tsx
- packages/ui/src/components/Form/loadBalancer/LoadBalancerEditor.tsx
- packages/ui/src/components/Visualization/Canvas/CanvasForm.test.tsx
> fix: Use a Typeahead component for the DataFormat and LoadBalancer Field

- packages/ui-tests/cypress/e2e/designer/multiflow/multiFlowDesigner.cy.ts
- packages/ui-tests/cypress/support/next-commands/default.ts
- packages/ui-tests/stories/canvas/Canvas.stories.tsx
- packages/ui-tests/stories/canvas/CanvasSideBar.stories.tsx
- packages/ui-tests/stories/canvas/ContextToolbar.stories.tsx
- packages/ui/src/components/Visualization/Canvas/Canvas.test.tsx
- packages/ui/src/components/Visualization/Canvas/CanvasForm.test.tsx
- packages/ui/src/components/Visualization/ContextToolbar/ContextToolbar.tsx
- packages/ui/src/components/Visualization/ContextToolbar/DSLSelector/DSLSelector.test.tsx
- packages/ui/src/components/Visualization/ContextToolbar/DSLSelector/DSLSelectorToggle/DSLSelectorToggle.test.tsx
- packages/ui/src/components/Visualization/ContextToolbar/Flows/FlowsList.test.tsx
- packages/ui/src/components/Visualization/ContextToolbar/Flows/FlowsMenu.test.tsx
- packages/ui/src/components/Visualization/ContextToolbar/NewEntity/NewEntity.test.tsx
- packages/ui/src/components/Visualization/ContextToolbar/NewEntity/NewEntity.tsx
- packages/ui/src/components/Visualization/EmptyState/FlowType/NewFlow.test.tsx
- packages/ui/src/components/Visualization/EmptyState/VisualizationEmptyState.test.tsx
- packages/ui/src/hooks/entities.test.tsx
- packages/ui/src/models/camel/camel-k-resource.ts
- packages/ui/src/models/camel/camel-resource.test.ts
- packages/ui/src/models/camel/camel-resource.ts
- packages/ui/src/models/camel/camel-route-resource.test.ts
- packages/ui/src/models/camel/camel-route-resource.ts
- packages/ui/src/models/visualization/base-visual-entity.ts
- packages/ui/src/models/visualization/flows/camel-rest-configuration-visual-entity.test.ts
- packages/ui/src/models/visualization/flows/camel-route-visual-entity.test.ts
- packages/ui/src/models/visualization/flows/camel-route-visual-entity.ts
- packages/ui/src/models/visualization/flows/support/flows-visibility.ts
- packages/ui/src/models/visualization/visualization-node.test.ts
- packages/ui/src/stubs/TestProvidersWrapper.tsx
- packages/ui/src/stubs/camel-route.ts
Currently, setting the current DSL and creating a new entity are tied together in a single step in the NewFlow component.
This commit split that functionality into two separate buttons:
1. DSL Selector: Meant to choose the current DSL and therefore determine which type of entities can be added to the Canvas
2. NewEntity: This is for adding new entities, supported by the current DSL, or said differently, allowing to add entities from the current CamelResource registry.
The existing functionality from the CanvasEmptyState is preserved for now.
In addition to that, when removing all routes, a new route won't be created by default.
fix: https://github.com/KaotoIO/kaoto/issues/1030
> feat(Canvas): Add new entities to the Canvas

- packages/ui-tests/stories/canvas/CanvasSideBar.stories.tsx
- packages/ui/src/components/IconResolver/IconResolver.tsx
- packages/ui/src/models/visualization/flows/abstract-camel-visual-entity.ts
- packages/ui/src/models/visualization/flows/camel-error-handler-visual-entity.ts
- packages/ui/src/models/visualization/flows/camel-intercept-from-visual-entity.ts
- packages/ui/src/models/visualization/flows/camel-intercept-send-to-endpoint-visual-entity.ts
- packages/ui/src/models/visualization/flows/camel-intercept-visual-entity.ts
- packages/ui/src/models/visualization/flows/camel-on-completion-visual-entity.ts
- packages/ui/src/models/visualization/flows/camel-on-exception-visual-entity.ts
- packages/ui/src/models/visualization/flows/camel-rest-configuration-visual-entity.ts
- packages/ui/src/models/visualization/flows/camel-route-configuration-visual-entity.ts
- packages/ui/src/models/visualization/flows/support/camel-steps.service.ts
- packages/ui/src/utils/node-icon-resolver.ts
```yaml
- route:
id: route-2934
from:
id: from-3609
uri: timer:template
parameters:
period: "1000"
steps:
- to:
id: to-1548
uri: log:MyLogger
parameters: {}
- log:
id: log-6283
message: template message
- routeConfiguration:
id: routeConfiguration-4029
- onCompletion:
id: onCompletion-1387
mode: AfterConsumer
- onException:
id: onException-3063
```
> feat(Canvas): Pass Icon type to better find appropriate icons

- packages/ui-tests/cypress/e2e/designer/rootContainerConfig/rootContainersConf.cy.ts
- packages/ui-tests/cypress/e2e/designer/specialCamelRoutes/rootOnException.cy.ts
- packages/ui-tests/cypress/e2e/designer/specialStepConfiguration/loadBalancerConfig.cy.ts
- packages/ui/package.json
- packages/ui/src/components/Form/CustomAutoField.tsx
- packages/ui/src/components/Form/customField/CustomLongTextField.scss
- packages/ui/src/components/Form/customField/CustomLongTextField.test.tsx
- packages/ui/src/components/Form/customField/CustomLongTextField.tsx
- packages/ui/src/components/Visualization/Canvas/CanvasForm.test.tsx
- packages/ui/src/components/Visualization/Canvas/__snapshots__/CanvasForm.test.tsx.snap
- yarn.lock
Fixes #1043 
However there are some issues with this new CustomLongTextField listed Following:
The new field is interacting with the CSS of CustomNestField's ExpandableSection. Hence it doesn't load correctly for Kafka's Sasl Jaas Config:
Note that once the field is click and you start adding some text, the field automatically corrects. Also the field loads correctly if we load the ExpandableSection as Expanded by adding the isExpanded attribute always.
> fix: Added CustomLongTextField and using it for 'Expression', 'Sasl Jaas Config' fields

- packages/ui/src/components/Visualization/Custom/CustomNode.scss
- packages/ui/src/components/Visualization/Custom/CustomNode.tsx
- packages/ui/src/components/Visualization/Custom/ItemDisableStep.tsx
- packages/ui/src/models/visualization/base-visual-entity.ts
- packages/ui/src/models/visualization/flows/__snapshots__/abstract-camel-visual-entity.test.ts.snap
- packages/ui/src/models/visualization/flows/__snapshots__/camel-intercept-from-visual-entity.test.ts.snap
- packages/ui/src/models/visualization/flows/__snapshots__/camel-intercept-send-to-endpoint-visual-entity.test.ts.snap
- packages/ui/src/models/visualization/flows/__snapshots__/camel-intercept-visual-entity.test.ts.snap
- packages/ui/src/models/visualization/flows/__snapshots__/camel-on-completion-visual-entity.test.ts.snap
- packages/ui/src/models/visualization/flows/__snapshots__/camel-on-exception-visual-entity.test.ts.snap
- packages/ui/src/models/visualization/flows/__snapshots__/pipe-visual-entity.test.ts.snap
- packages/ui/src/models/visualization/flows/abstract-camel-visual-entity.ts
- packages/ui/src/models/visualization/flows/camel-error-handler-visual-entity.test.ts
- packages/ui/src/models/visualization/flows/camel-error-handler-visual-entity.ts
- packages/ui/src/models/visualization/flows/camel-intercept-from-visual-entity.ts
- packages/ui/src/models/visualization/flows/camel-intercept-send-to-endpoint-visual-entity.ts
- packages/ui/src/models/visualization/flows/camel-intercept-visual-entity.ts
- packages/ui/src/models/visualization/flows/camel-on-completion-visual-entity.ts
- packages/ui/src/models/visualization/flows/camel-on-exception-visual-entity.ts
- packages/ui/src/models/visualization/flows/camel-rest-configuration-visual-entity.test.ts
- packages/ui/src/models/visualization/flows/camel-rest-configuration-visual-entity.ts
- packages/ui/src/models/visualization/flows/camel-route-configuration-visual-entity.ts
- packages/ui/src/models/visualization/flows/pipe-visual-entity.ts
- packages/ui/src/models/visualization/flows/support/camel-component-schema.service.ts
- packages/ui/src/models/visualization/visualization-node.ts
This PR is still a draft because the disabling effect should be more explicit
Some EIPs provide a `disabled` property to ignore them during the runtime.
This commit adds quick access to that property, so users can easily enable/disable nodes in the canvas. In addition to that, the step is grayed out when disabled.
| Disabled | Enabled |
| --- | --- |
| ![image](https://github.com/KaotoIO/kaoto/assets/16512618/d5cd6f4c-3bb7-4026-9793-f38440c07f14) | ![image](https://github.com/KaotoIO/kaoto/assets/16512618/70d2fe4a-aeaf-4d3a-8d5e-470af5958fa1) |
fix: https://github.com/KaotoIO/kaoto/issues/758
fix: https://github.com/KaotoIO/kaoto/issues/699
> feat(Canvas): Disable steps

- packages/ui-tests/cypress/support/next-commands/default.ts
- packages/ui-tests/cypress/support/next-commands/design.ts
- packages/ui/src/components/Visualization/Canvas/Canvas.test.tsx
- packages/ui/src/components/Visualization/ContextToolbar/Flows/FlowsList.tsx
- packages/ui/src/components/Visualization/Custom/CustomNode.tsx
- packages/ui/src/components/Visualization/Custom/ItemDeleteGroup.tsx
- packages/ui/src/components/Visualization/Custom/ItemDeleteStep.tsx
- packages/ui/src/multiplying-architecture/KaotoBridge.tsx
- packages/ui/src/pages/Design/DesignPage.tsx
- packages/ui/src/providers/__snapshots__/delete-modal.provider.test.tsx.snap
- packages/ui/src/providers/delete-modal.provider.test.tsx
- packages/ui/src/providers/delete-modal.provider.tsx
- packages/ui/src/providers/index.ts
> fix: Warn users when trying to delete a container

- packages/ui/src/models/visualization/flows/support/camel-component-default.service.test.ts
- packages/ui/src/models/visualization/flows/support/camel-component-default.service.ts
When a new expression-aware step is generated, the expression property is created as follows:
```yaml
setHeader:
id: setHeader-1234
expression:
simple:
expression: {}
```
Notice the `expression: {}` bit which causes for the expression TextField to render `[object Object]`
Replace the autogenerated step with an empty `simple: {}`, so there's the feedback that a property is left to be configured. In the future, there will be the same feedback in the Canvas as well. https://github.com/KaotoIO/kaoto/issues/705
```yaml
setHeader:
id: setHeader-1234
expression:
simple: {}
```
This comes from this PR https://github.com/KaotoIO/kaoto/pull/1068, in which I suggested using `expression: {}` for the newly created step.
fix: https://github.com/KaotoIO/kaoto/issues/1076
> fix(CanvasForm): Expression field shows `[object Object]`

- packages/ui/src/components/Catalog/BaseCatalog.scss
- packages/ui/src/components/Catalog/Catalog.scss
- packages/ui/src/components/Catalog/CatalogFilter.scss
- packages/ui/src/components/Catalog/CatalogFilter.tsx
Currently, we're using the `numLabels` property of the `LabelGroup` component to show just a few `Labels`.
When the user clicks on the `n more` label, a navigation is performed and the UI is reloaded, causing the VSCode extension to fail.
This happens because `LabelGroup` is a child of the `Form` component, causing to execute the default Form behavior when selecting a `Label`
The fix is to move the Label bar outside of the `Form` component.
| --- | --- |
| ![image](https://github.com/KaotoIO/kaoto/assets/16512618/d1fb0b05-1f4c-4b74-bb8b-b64199ca5a83) | ![image](https://github.com/KaotoIO/kaoto/assets/16512618/f54fa584-9bc9-454e-927f-c74de208990f) |
fix: https://github.com/KaotoIO/kaoto/issues/1073
fix: https://github.com/KaotoIO/kaoto/issues/1074
> fix(Catalog): Using labels causes unintended navigation

- packages/ui-tests/cypress/support/next-commands/sourceCode.ts
Currently, there are a few tests that seem to randomly fail:
* branchingStepActions.cy.ts
* branchingStepAddition.cy.ts
This commit adds another validation to ensure the source code has been loaded with the aim of stabilizing them.
> chore(e2e): Add another validation for uploadFixture

- packages/camel-catalog/assembly/pom.xml
- packages/camel-catalog/assembly/src/main/resources/schemas/PipeConfiguration.json
- packages/camel-catalog/kaoto-camel-catalog-maven-plugin/src/main/java/io/kaoto/camelcatalog/KaotoCamelCatalogMojo.java
- packages/ui/src/models/camel/camel-resource.test.ts
- packages/ui/src/models/camel/kamelet-binding-resource.test.ts
- packages/ui/src/models/camel/pipe-resource.test.ts
- packages/ui/src/models/camel/pipe-resource.ts
- packages/ui/src/models/visualization/flows/pipe-visual-entity.test.ts
- packages/ui/src/models/visualization/flows/pipe-visual-entity.ts
- packages/ui/src/stubs/kamelet-binding-route.ts
- packages/ui/src/utils/index.ts
- packages/ui/src/utils/pipe-custom-schema.test.ts
- packages/ui/src/utils/pipe-custom-schema.ts
Fixes: #1031
Description### 
- Loads container for Pipes.
- Loads the Configuration form when a user clicks on the Pipe Container.
- Manage the sync between source-code and form.
> feat(canvas): Add a container for Pipes

- packages/ui-tests/stories/canvas/Canvas.stories.tsx
After merging https://github.com/KaotoIO/kaoto/pull/1086, Storybook needs to be updated to accommodate for the new `Pipe` constructor
> fix(Storybook): Fix Pipe stories

- packages/camel-catalog/assembly/src/test/java/io/kaoto/camelcatalog/CamelYamlDslSchemaTest.java
- packages/camel-catalog/kaoto-camel-catalog-maven-plugin/src/main/java/io/kaoto/camelcatalog/CamelCatalogProcessor.java
- packages/camel-catalog/kaoto-camel-catalog-maven-plugin/src/main/java/io/kaoto/camelcatalog/CamelYamlDslSchemaProcessor.java
- packages/camel-catalog/kaoto-camel-catalog-maven-plugin/src/test/java/io/kaoto/camelcatalog/CamelCatalogProcessorTest.java
- packages/camel-catalog/kaoto-camel-catalog-maven-plugin/src/test/java/io/kaoto/camelcatalog/CamelYamlDSLKeysComparatorTest.java
- packages/camel-catalog/kaoto-camel-catalog-maven-plugin/src/test/java/io/kaoto/camelcatalog/CamelYamlDslSchemaProcessorTest.java
- packages/camel-catalog/pom.xml
- packages/ui-tests/cypress/e2e/designer/rootContainerConfig/rootContainersConf.cy.ts
- packages/ui-tests/cypress/e2e/designer/specialStepConfiguration/dataFormatStepConfig.cy.ts
- packages/ui/src/components/Form/bean/BeanReferenceField.tsx
- packages/ui/src/components/Form/bean/NewBeanModal.tsx
- packages/ui/src/models/kamelets-catalog.ts
- packages/ui/src/models/visualization/flows/camel-error-handler-visual-entity.test.ts
- packages/ui/src/models/visualization/flows/camel-error-handler-visual-entity.ts
- packages/ui/src/models/visualization/flows/support/__snapshots__/camel-component-schema.service.test.ts.snap
- packages/ui/src/models/visualization/metadata/beans-entity-handler.test.ts
- packages/ui/src/models/visualization/metadata/beans-entity-handler.ts
- packages/ui/src/models/visualization/metadata/routeTemplateBeansEntity.ts
- packages/ui/src/pages/Beans/BeansPage.tsx
- packages/ui/src/stubs/rest-configuration.ts
Update camel to `4.6.0` and fix compilation errors
> chore: Update Camel and fix compilation issues

- packages/ui/src/models/visualization/flows/camel-catalog.service.test.ts
- packages/ui/src/models/visualization/flows/camel-catalog.service.ts
- packages/ui/src/models/visualization/flows/support/camel-component-schema.service.test.ts
- packages/ui/src/utils/camel-uri-helper.test.ts
Currently, when using the `kamelet` component, providing an unknown Kamelet to Kaoto, this renders the basic `To` EIP configuration form.
This is not useful since then we can't provide the Kamelet's TemplateId nor RouteId.
| --- | --- |
| ![image](https://github.com/KaotoIO/kaoto/assets/16512618/5bc86777-bf63-48f9-9d4c-0396c2e89140) | ![image](https://github.com/KaotoIO/kaoto/assets/16512618/94f6abf9-d7bb-4be5-b8df-c9335b100fb1) |
The fix is to fallback to the standard `Kamelet` component when passing an unknown Kamelet to Kaoto.
fix: https://github.com/KaotoIO/kaoto/issues/1004
> fix(CanvasForm): Provide basic schema for unknown Kamelets

- packages/ui/src/components/Form/customField/TypeaheadEditor.test.tsx
- packages/ui/src/components/Form/customField/TypeaheadEditor.tsx
- packages/ui/src/components/Form/dataFormat/DataFormatEditor.scss
- packages/ui/src/components/Form/dataFormat/DataFormatEditor.tsx
- packages/ui/src/components/Form/dataFormat/dataformat.service.ts
- packages/ui/src/components/Form/expression/ExpressionEditor.scss
- packages/ui/src/components/Form/expression/ExpressionEditor.tsx
- packages/ui/src/components/Form/loadBalancer/LoadBalancerEditor.scss
- packages/ui/src/components/Form/loadBalancer/LoadBalancerEditor.tsx
- packages/ui/src/components/Form/loadBalancer/loadbalancer.service.ts
Fixes #1055,
Creating this PR for initial review on the TypeaheadEditor reusable component, currently used with DataFormatEditor. Once reviewed, we can reuse the new componet with loadbalancer and ExpressionEditor as well.
This set of new changes can be tested here: https://shivamg640.github.io/kaoto/
> fix(1055): Added TypeaheadEditor and reusing it with DataFormatEditor

- .github/workflows/e2e-tests.yml
- packages/ui-tests/cypress/support/next-commands/sourceCode.ts
- packages/ui-tests/package.json
- yarn.lock
There is constantly failing GH workflow with e2e tests. This fixes these constant failures
> e2e - fix failing e2e workflow

- packages/ui-tests/cypress/e2e/designer/basicNodeActions/stepDisable.cy.ts
- packages/ui-tests/cypress/e2e/designer/sidepanelConfig/modelineConf.cy.ts
- packages/ui-tests/cypress/fixtures/flows/pipe/modeline.yaml
- packages/ui-tests/cypress/support/cypress.d.ts
- packages/ui-tests/cypress/support/next-commands/design.ts
e2e for https://github.com/KaotoIO/kaoto/issues/937 and https://github.com/KaotoIO/kaoto/issues/699
> e2e - preserving modeline after pipe config and disable step 

- packages/ui-tests/cypress/e2e/designer/basicNodeActions/stepRemoval.cy.ts
- packages/ui-tests/cypress/support/next-commands/design.ts
- packages/ui/src/components/Visualization/Canvas/Canvas.tsx
- packages/ui/src/components/Visualization/Canvas/CanvasSideBar.scss
- packages/ui/src/components/Visualization/Canvas/CanvasSideBar.tsx
- packages/ui/src/components/Visualization/Canvas/__snapshots__/Canvas.test.tsx.snap
fixes https://github.com/KaotoIO/kaoto/issues/835
can be seen at https://tplevko.github.io/kaoto-next/
> fix(835) - make the config panel resizable

- packages/ui/src/components/Form/CustomAutoFields.tsx
- packages/ui/src/components/Form/customField/CustomNestField.tsx
- packages/ui/src/components/Visualization/Canvas/__snapshots__/CanvasForm.test.tsx.snap
This PR is related to a previous [PR](https://github.com/KaotoIO/kaoto/pull/1141), where I added the following two changes:
1. Removed the useMemo() calls as I found out that it is unnecessarily used and the underlying code is getting executed all the time the component is re-executed as we inject an object as it dependency. I might be incorrect on this so please let me know if we need a discussion over this.
2. Modified the id to make it unique for all the groups in the expandable section.
> fix(991): Removing useMemo() from the code

- packages/catalog-generator/src/main/java/io/kaoto/camelcatalog/commands/GenerateCommandOptions.java
- packages/catalog-generator/src/main/java/io/kaoto/camelcatalog/generator/CamelCatalogProcessor.java
- packages/catalog-generator/src/main/java/io/kaoto/camelcatalog/maven/CamelCatalogVersionLoader.java
- packages/catalog-generator/src/main/java/io/kaoto/camelcatalog/maven/KaotoMavenVersionManager.java
this PR addresses the latest feedback on https://github.com/KaotoIO/kaoto/pull/1169
> addressing PR review feedback

- packages/ui/src/components/Visualization/Canvas/CanvasForm.test.tsx
- packages/ui/src/components/Visualization/Canvas/CanvasForm.tsx
Changes with this PR is related to avoiding the serialization of empty strings with whitespaces.
Fixes #1022
Please test here: https://shivamg640.github.io/kaoto/
> fix(1022): Avoid serializing empty strings

- packages/ui-tests/cypress/e2e/designer/sidepanelConfig/propertiesFilter.cy.ts
- packages/ui-tests/cypress/support/cypress.d.ts
- packages/ui-tests/cypress/support/next-commands/nodeConfiguration.ts
- packages/ui/src/components/Visualization/Canvas/CanvasForm.tsx
- packages/ui/src/components/Visualization/Canvas/__snapshots__/CanvasForm.test.tsx.snap
e2e coverage for https://github.com/KaotoIO/kaoto/pull/1174
> e2e(1174): add coverage for parameters filter in canvas form

- packages/ui/src/components/Form/bean/BeanReferenceField.tsx
- packages/ui/src/components/Form/dataFormat/DataFormatEditor.tsx
- packages/ui/src/components/Form/expression/ExpressionAwareNestField.tsx
- packages/ui/src/components/Form/expression/ExpressionField.tsx
- packages/ui/src/components/Form/loadBalancer/LoadBalancerEditor.tsx
- packages/ui/src/components/Form/stepExpression/StepExpressionEditor.tsx
- packages/ui/src/utils/get-serialized-model.test.ts
- packages/ui/src/utils/get-serialized-model.ts
- packages/ui/src/utils/index.ts
> fix(1022): Avoid serializing empty strings for Expressions, Loadbalancers, and dataformat fields

- packages/ui/src/components/Form/customField/TypeaheadEditor.test.tsx
- packages/ui/src/components/Form/customField/TypeaheadEditor.tsx
fixes https://github.com/KaotoIO/kaoto/issues/1200
> fix(1200): disable typeahead dropdown field on unknown value

- packages/ui/src/multiplying-architecture/KaotoEditor.tsx
Remove VSCode Kaoto warning
```
Warning: React does not recognize the `isHidden` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `ishidden` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
```
fixes: https://github.com/KaotoIO/vscode-kaoto/issues/436
> fix(vscode): Remove isHidden warning from KaotoEditor component

- packages/ui/src/models/visualization/flows/support/camel-component-default.service.test.ts
- packages/ui/src/models/visualization/flows/support/camel-component-default.service.ts
> fix(1100): Use '${body}' as default for Log's EIP message

- packages/ui/src/multiplying-architecture/KaotoEditorFactory.ts
The lifecycle of a VSCode setting is as follows:
1. It starts with `null`
2. When the user updates it, it stores that value
3. When the user clears it, the value gets to be an empty string '""'
In case the `catalogUrl` is an empty string, we provide a fallback to use the embedded catalog.
fix: https://github.com/KaotoIO/kaoto/issues/1109
relates: https://github.com/KaotoIO/kaoto/issues/1204
> fix(vscode): Provide fallback for VSCode catalog

- packages/catalog-generator/.gitignore
- packages/catalog-generator/.vscode/settings.json
- packages/catalog-generator/README.md
- packages/catalog-generator/src/main/java/io/kaoto/camelcatalog/generator/CamelCatalogProcessor.java
- packages/catalog-generator/src/main/java/io/kaoto/camelcatalog/generator/CatalogGeneratorBuilder.java
- packages/catalog-generator/src/main/java/io/kaoto/camelcatalog/maven/CamelCatalogVersionLoader.java
- packages/catalog-generator/src/main/java/io/kaoto/camelcatalog/maven/KaotoMavenVersionManager.java
fix: https://github.com/KaotoIO/kaoto/issues/1109
> fix(catalog): Build Red Hat build of CEQ 

- packages/ui/src/camel-utils/camel-to-tile.adapter.test.ts
- packages/ui/src/camel-utils/camel-to-tile.adapter.ts
- packages/ui/src/components/Catalog/Catalog.models.ts
- packages/ui/src/components/Catalog/Catalog.tsx
- packages/ui/src/components/Catalog/CatalogFilter.tsx
- packages/ui/src/components/Catalog/DataListItem.scss
- packages/ui/src/components/Catalog/DataListItem.tsx
- packages/ui/src/components/Catalog/ProviderFilter/ProviderFilter.scss
- packages/ui/src/components/Catalog/ProviderFilter/ProviderFilter.tsx
- packages/ui/src/components/Catalog/Tile.scss
- packages/ui/src/components/Catalog/Tile.tsx
- packages/ui/src/components/Catalog/__snapshots__/DataListItem.test.tsx.snap
- packages/ui/src/components/Catalog/filter-tiles.test.ts
- packages/ui/src/components/Catalog/filter-tiles.ts
- packages/ui/src/models/camel-components-catalog.ts
When generating a catalog, there are Camel components that are provided by a specific build while others are simply upstream.
This commit displays that information in the catalog, to make it easier to distinguish them.
fix: https://github.com/KaotoIO/kaoto/issues/1109
> feat(catalog): Display `Provided by` information

- packages/ui/src/layout/Navigation.tsx
- packages/ui/src/layout/TopBar.tsx
There is a disabled settings page option in the top bar kebab menu.
This commit removes the existing settings navigation link and places it under the existing kebab menu.
fix: https://github.com/KaotoIO/kaoto/issues/1224
> fix(settings): Move settings link to the kebab menu

- packages/ui-tests/cypress/e2e/designer/specialCamelRoutes/onException.cy.ts
- packages/ui-tests/cypress/e2e/designer/specialStepConfiguration/expressionStepConfig.cy.ts
- packages/ui-tests/cypress/e2e/designer/specialStepConfiguration/setHeadersStepConfig.cy.ts
- packages/ui-tests/cypress/support/cypress.d.ts
- packages/ui-tests/cypress/support/next-commands/nodeConfiguration.ts
- packages/ui/src/components/Form/customField/TypeaheadField.tsx
- packages/ui/src/components/Form/expression/ExpressionEditor.test.tsx
- packages/ui/src/components/Form/expression/ExpressionEditor.tsx
- packages/ui/src/components/Form/expression/expression.service.ts
fixes https://github.com/KaotoIO/kaoto/issues/1108
> fix(1108): Provide common expression result types

- packages/ui/package.json
- packages/ui/src/models-api.ts
- packages/ui/src/models/camel/kamelet-resource.ts
- packages/ui/src/models/index.ts
- packages/ui/src/models/visualization/flows/camel-route-configuration-visual-entity.ts
- packages/ui/src/providers/schema-bridge.provider.test.tsx
- packages/ui/tsconfig.esm.json
Currently, the `models` folder is not exposed through the npm package.
This commit adds a new export to make it available to consumers.
> feat(exports): Expose models through npm package

- packages/ui/src/models-api.ts
- packages/ui/src/models/settings/abstract-settings-adapter.ts
- packages/ui/src/models/settings/default-settings-adapter.ts
- packages/ui/src/models/settings/index.ts
- packages/ui/src/models/settings/localstorage-settings-adapter.test.ts
- packages/ui/src/models/settings/localstorage-settings-adapter.ts
- packages/ui/src/models/settings/settings.model.ts
- packages/ui/src/multiplying-architecture/KaotoBridge.tsx
- packages/ui/src/multiplying-architecture/KaotoEditorApp.tsx
- packages/ui/src/multiplying-architecture/KaotoEditorChannelApi.ts
- packages/ui/src/multiplying-architecture/KaotoEditorFactory.ts
At the moment, the Kaoto settings are passed individually to VSCode, meaning that in case we want to add new settings, we need to pass individual parameters to the `KaotoEditorApp` class.
This commit provides a SettingsAdapter so every new setting will be added directly to the adapter.
relates: https://issues.redhat.com/browse/KTO-441
relates: https://github.com/KaotoIO/kaoto/pull/1221
> feat(vscode): Provide SettingsAdapter for VSCode

- packages/ui/src/components/Form/CustomAutoFields.tsx
- packages/ui/src/components/Form/customField/CustomNestField.tsx
fixes https://github.com/KaotoIO/kaoto/issues/1207
make the filter ignore empty spaces, to facilitate filtering both on spaced and unspaced strings
https://github.com/user-attachments/assets/7075dbbc-6308-4501-b4f9-a8c04be6de7f
> fix(1207): filtering string with empty space

- packages/ui/src/multiplying-architecture/KaotoEditorFactory.test.ts
- packages/ui/src/multiplying-architecture/KaotoEditorFactory.ts
- packages/ui/src/utils/index.ts
- packages/ui/src/utils/promise-timeout.test.ts
- packages/ui/src/utils/promise-timeout.ts
Currently, VSCode Kaoto build with the main branch is broken due to a missing API implementation that causes for a `promise` to hold forever, preventing the extension from loading.
The fix is to provide a `timeout` mechanism to unblock the promise, plus a `fallback` mechanism to get sensitive settings default to continue the extension bootstrap process.
> fix(VSCode): Provide timeout and fallback for `KaotoEditorFactory`

- packages/ui-tests/cypress/e2e/designer/settings/switchDescriptionId.cy.ts
- packages/ui-tests/cypress/fixtures/flows/camelRoute/idDescriptionSettings.yaml
related to https://issues.redhat.com/browse/KTO-450
> e2e(KTO-450): add test for settings switch for node label

- packages/ui/src/components/Visualization/Canvas/Canvas.tsx
When opening and closing the configuration tab, mobx warnings are thrown from the @patternfly/react-topology library.
The fix is to wrap any operation to the canvas inside of an `action` callback, so mobx can notify the consumers that something changed.
fix: https://github.com/KaotoIO/kaoto/issues/1294
> fix(Canvas): Remove mobx warnings from @patternfly/react-topology

- packages/ui/package.json
- packages/ui/src/components/Visualization/Canvas/canvas.models.ts
- packages/ui/src/components/Visualization/Custom/Layout/DagreGroupsExtendedLayout.ts
- packages/ui/src/components/Visualization/Custom/Layout/DagreLink.ts
- packages/ui/src/components/Visualization/Custom/Layout/DagreNode.ts
- yarn.lock
Currently, `DagreLayout` is used to render the graph, and while it does work, it doesn't support nested groups properly due to a limitation in Dagre itself.
In the `@patternfly/react-topology` there's another layout called `DagreGroupsLayout` that performs individual layout inside each group, providing a better result when the graph contains nested groups.
This commit brings that class over and uses the initial node index for sorting the graph node, this way the order is kept when expanding/collapsing nodes in the Canvas.
fix: https://github.com/KaotoIO/kaoto/issues/368
related: https://github.com/patternfly/react-topology/issues/230
> feate(Canvas): Extend DagreGroupsLayout

- packages/ui-tests/cypress/support/next-commands/design.ts
- packages/ui/src/components/Visualization/Canvas/CanvasFormTabs.test.tsx
- packages/ui/src/components/Visualization/Canvas/__snapshots__/Canvas.test.tsx.snap
- packages/ui/src/components/Visualization/Canvas/__snapshots__/CanvasForm.test.tsx.snap
- packages/ui/src/components/Visualization/Canvas/__snapshots__/canvas.service.test.ts.snap
- packages/ui/src/components/Visualization/Canvas/canvas.models.ts
- packages/ui/src/components/Visualization/Canvas/canvas.service.test.ts
- packages/ui/src/components/Visualization/Canvas/canvas.service.ts
- packages/ui/src/components/Visualization/Custom/Group/CollapseButton.test.tsx
- packages/ui/src/components/Visualization/Custom/Group/CollapseButton.tsx
- packages/ui/src/components/Visualization/Custom/Group/ContextMenuButton.test.tsx
- packages/ui/src/components/Visualization/Custom/Group/ContextMenuButton.tsx
- packages/ui/src/components/Visualization/Custom/Group/CustomGroupExpanded.tsx
- packages/ui/src/components/Visualization/Custom/Layout/DagreGroupsExtendedLayout.ts
- packages/ui/src/components/Visualization/Custom/NoBendingEdge.tsx
- packages/ui/src/components/Visualization/Custom/index.ts
- packages/ui/src/models/visualization/flows/abstract-camel-visual-entity.ts
- packages/ui/src/models/visualization/flows/camel-route-visual-entity.test.ts
- packages/ui/src/models/visualization/flows/pipe-visual-entity.test.ts
- packages/ui/src/models/visualization/flows/pipe-visual-entity.ts
- packages/ui/src/models/visualization/flows/support/camel-steps.service.ts
- packages/ui/src/models/visualization/visualization-node.test.ts
- packages/ui/src/stubs/camel-route-branch.ts
- packages/ui/src/tests/__snapshots__/nodes-edges.test.ts.snap
- packages/ui/src/tests/nodes-edges.test.ts
Currently, all children are rendered as individual nodes in the Canvas, making it complicated to understand when a step belongs to a parent EIP or if it comes as a next step in the Camel Route.
This commit adds support for rendering EIP branches as containers.
| --- | --- |
| ![image](https://github.com/user-attachments/assets/8f01f3db-90b4-4d5b-9587-ecf03b457c17) | ![image](https://github.com/user-attachments/assets/1940caba-7d70-4948-adf7-8c057617e40f) |
fix: https://github.com/KaotoIO/kaoto/issues/368
> feat(Canvas): Add containers for branches

- packages/ui/package.json
- yarn.lock
After upgrading [`@patternfly/react-topology`](https://github.com/KaotoIO/kaoto/pull/1302), calculating the layout inside of Kaoto is not needed anymore, so `@dagre/dagrejs` is also not needed.
relates: https://github.com/patternfly/react-topology/issues/230
> chore: Remove  since is not needed

- packages/ui/src/models/visualization/base-visual-entity.ts
- packages/ui/src/models/visualization/visualization-node.test.ts
- packages/ui/src/models/visualization/visualization-node.ts
With the introduction of containers for branches (https://github.com/KaotoIO/kaoto/pull/1300), connecting leaf nodes with the previous elements are different.
The use of this method [was removed here](https://github.com/KaotoIO/kaoto/pull/1300/files#diff-3efb01a9b66d3cdfa36a64cf79ca88d897711024f496b0ba1285ba642f82fa3eL215)
fix: https://github.com/KaotoIO/kaoto/issues/368
fix: https://github.com/KaotoIO/kaoto/issues/1329
> chore(viz): Remove unused `populateLeafNodesIds` method

- packages/ui/src/components/Visualization/Canvas/Canvas.tsx
- packages/ui/src/components/Visualization/Canvas/CanvasForm.test.tsx
- packages/ui/src/components/Visualization/Canvas/__snapshots__/flow.service.test.ts.snap
- packages/ui/src/components/Visualization/Canvas/canvas.service.test.ts
- packages/ui/src/components/Visualization/Canvas/canvas.service.ts
- packages/ui/src/components/Visualization/Canvas/controller.service.test.ts
- packages/ui/src/components/Visualization/Canvas/controller.service.ts
- packages/ui/src/components/Visualization/Canvas/flow.service.test.ts
- packages/ui/src/components/Visualization/Canvas/flow.service.ts
- packages/ui/src/tests/nodes-edges.test.ts
Split `CanvasService` for better separation of concerns.
fix: https://github.com/KaotoIO/kaoto/issues/1329
> chore(Canvas): Split `CanvasService` in `ControllerService` and `FlowService`

- packages/ui/src/components/Visualization/Canvas/Canvas.tsx
- packages/ui/src/components/Visualization/Canvas/canvas.defaults.ts
- packages/ui/src/models/local-storage-keys.ts
Store the user specified sidebar width in local storage persisting the width even when switching tabs in the UI.
https://github.com/user-attachments/assets/79e1f796-37c9-4e46-a62e-5d178697fa27
> Add sidebar width preserve in local storage

- packages/catalog-generator/src/main/java/io/kaoto/camelcatalog/generator/CamelCatalogProcessor.java
Currently, the `parameters` property is only added for `ToDynamicDefinition` EIP.
This represents a problem for Camel 4.8.0 since there's a new `poll` EIP that requires it.
> fix(catalog-generator): Add "parameters" property

- packages/catalog-generator/src/main/java/io/kaoto/camelcatalog/generator/CamelYamlDslSchemaProcessor.java
- packages/catalog-generator/src/main/java/io/kaoto/camelcatalog/generator/CatalogGeneratorBuilder.java
- packages/catalog-generator/src/main/resources/schemas/KameletConfiguration.json
- packages/catalog-generator/src/main/resources/schemas/PipeConfiguration.json
- packages/ui/package.json
- packages/ui/src/components/Form/schema.service.ts
- packages/ui/src/models/visualization/flows/camel-rest-configuration-visual-entity.ts
- packages/ui/src/models/visualization/flows/camel-route-configuration-visual-entity.ts
- packages/ui/src/models/visualization/flows/support/__snapshots__/camel-component-schema.service.test.ts.snap
- packages/ui/src/stubs/rest-configuration.ts
- yarn.lock
> Fix(schema): Migrate all JSON Schemas to draft-07

- packages/ui/src/models/visualization/flows/__snapshots__/pipe-visual-entity.test.ts.snap
- packages/ui/src/models/visualization/flows/pipe-visual-entity.ts
fixes https://github.com/KaotoIO/kaoto/issues/1390
removed the unnecessary context buttons:
> fix(1390): Pipe contextual menu broken buttons removed

- packages/ui/jest-setup.ts
- packages/ui/src/multiplying-architecture/EditService.test.ts
- packages/ui/src/multiplying-architecture/EditService.ts
- packages/ui/src/multiplying-architecture/KaotoBridge.tsx
- packages/ui/src/multiplying-architecture/KaotoEditorApp.test.tsx
- packages/ui/src/multiplying-architecture/KaotoEditorApp.tsx
Currently, an MA edit lifecycle looks like the following:
1. The Kaoto editor makes an edit and notifies the MA.
2. After a quiet period (debounce), MA processes the edit and sends it back to the Kaoto editor.
3. If the content is the same, this last call is ignored by Kaoto, as the editor content is the same, so there's no need to recreate the UI. If the contrary, the current state gets discarded and the UI is regenerated with the incoming content.
This process opens the case for an edit happening a few milliseconds before the MA sends the content back, meaning that at this stage, the Kaoto content has changed but is receiving stale content, causing the UI to be regenerated with the stale content.
The fix for this situation is to implement a hash for each content and validate whether the …
> fix(MultiplyingArchitecture): Avoid setting stale edits

- packages/ui-tests/cypress/support/next-commands/design.ts
- packages/ui/src/components/Visualization/Canvas/Canvas.tsx
- packages/ui/src/components/Visualization/Canvas/Form/CanvasFormHeader.scss
- packages/ui/src/components/Visualization/Canvas/__snapshots__/Canvas.test.tsx.snap
fix(1422) 
overlay solved with toggle group wrapping:
https://github.com/user-attachments/assets/e2f88ce0-a583-4d4d-927e-b9e7ba564583
> fix(1422) Config panel buttons overlay - add toggleGroup wrapping

- packages/ui/src/components/Form/CustomAutoFields.tsx
- packages/ui/src/components/Form/customField/CustomNestField.scss
- packages/ui/src/components/Form/customField/CustomNestField.tsx
- packages/ui/src/components/Visualization/Canvas/Canvas.scss
- packages/ui/src/components/Visualization/Canvas/Canvas.tsx
- packages/ui/src/components/Visualization/Canvas/CanvasSideBar.scss
- packages/ui/src/components/Visualization/Canvas/Form/CanvasForm.scss
- packages/ui/src/components/Visualization/Canvas/Form/CanvasForm.tsx
- packages/ui/src/components/Visualization/Canvas/Form/__snapshots__/CanvasForm.test.tsx.snap
- packages/ui/src/components/Visualization/Canvas/__snapshots__/Canvas.test.tsx.snap
- packages/ui/src/components/Visualization/Canvas/__snapshots__/CanvasSideBar.test.tsx.snap
- packages/ui/src/components/Visualization/Custom/Group/CollapseButton.tsx
- packages/ui/src/components/Visualization/Custom/Group/ContextMenuButton.tsx
- packages/ui/src/components/Visualization/Custom/Group/CustomGroup.scss
- packages/ui/src/components/Visualization/Custom/Group/__snapshots__/CollapseButton.test.tsx.snap
- packages/ui/src/components/Visualization/Custom/Group/__snapshots__/ContextMenuButton.test.tsx.snap
- packages/ui/src/components/Visualization/Visualization.scss
I made custom groups to use rounded edges and tweaked the colours. Also styling for the side panel was changed to use flat cards with rounded edges that looks similar to PF6. 
before:
after:
fix: https://github.com/KaotoIO/kaoto/issues/472
> Visualization's look and feel tweaks

- packages/catalog-generator/src/main/java/io/kaoto/camelcatalog/generator/CamelCatalogProcessor.java
In Camel 4.8.0, there's an enum property over a multiValue parameter, making the configuration form to render a selector instead of a metadata editor.
> fix(CatalogGenerator): Ignore 'enum' property for multiValue param

- .github/workflows/e2e-tests.yml
the limit of storage is not far. Most of the place is took by the videos and screenshots of the e2e tests. We are usually looking at them only on failure. This should save a lot of space.
> chore: saving videos and screenshots for e2e tests only on failure

- packages/ui-tests/cypress/e2e/designer/sidepanelConfig/multiValueSerialization.cy.ts
- packages/ui-tests/cypress/fixtures/flows/camelRoute/multiValue.yaml
- packages/ui-tests/cypress/support/next-commands/nodeConfiguration.ts
- packages/ui/src/models/camel-properties-common.ts
- packages/ui/src/models/visualization/flows/abstract-camel-visual-entity.ts
- packages/ui/src/models/visualization/flows/support/__snapshots__/camel-component-schema.service.test.ts.snap
- packages/ui/src/models/visualization/flows/support/camel-component-schema.service.test.ts
- packages/ui/src/models/visualization/flows/support/camel-component-schema.service.ts
fixes https://github.com/KaotoIO/kaoto/issues/1428
> fix(1428): add support for multiValue

- packages/ui/src/components/PropertiesModal/PropertiesModal.scss
- packages/ui/src/components/PropertiesModal/PropertiesModal.tsx
- packages/ui/src/utils/node-icon-resolver.ts
fixes https://github.com/KaotoIO/kaoto/issues/787
Added icon:
> fix(787): Display connector icon in catalog detail modal

- packages/catalog-generator/src/main/java/io/kaoto/camelcatalog/generator/CatalogGeneratorBuilder.java
- packages/catalog-generator/src/main/java/io/kaoto/camelcatalog/model/CatalogLibrary.java
- packages/catalog-generator/src/main/java/io/kaoto/camelcatalog/model/CatalogLibraryEntry.java
- packages/catalog-generator/src/main/java/io/kaoto/camelcatalog/model/CatalogRuntime.java
- packages/ui-tests/cypress/e2e/designer/catalogs/springBootCatalog.cy.ts
- packages/ui/src/components/Visualization/ContextToolbar/RuntimeSelector/RuntimeSelector.tsx
fixes https://github.com/KaotoIO/kaoto/issues/1391
> fix(1391): Wrong speling of SpringBoot in Catalog

- packages/ui-tests/cypress/e2e/designer/sidepanelConfig/propertiesFilter.cy.ts
- packages/ui-tests/stories/canvas/CanvasSideBar.stories.tsx
- packages/ui/src/components/Form/CustomAutoFields.test.tsx
- packages/ui/src/components/Form/CustomAutoFields.tsx
- packages/ui/src/components/Form/NoFieldFound.test.tsx
- packages/ui/src/components/Form/NoFieldFound.tsx
- packages/ui/src/components/Form/OneOf/OneOfField.test.tsx
- packages/ui/src/components/Form/__snapshots__/CustomAutoFields.test.tsx.snap
- packages/ui/src/components/Form/properties/AddPropertyButtons.tsx
- packages/ui/src/components/Form/properties/PropertiesField.scss
- packages/ui/src/components/Form/properties/PropertiesField.tsx
- packages/ui/src/components/Form/properties/PropertiesFieldEmptyState.tsx
- packages/ui/src/components/Form/properties/PropertyRow.scss
- packages/ui/src/components/Form/properties/PropertyRow.tsx
- packages/ui/src/components/Form/properties/PropetiesField.test.tsx
- packages/ui/src/components/Form/properties/properties-field.models.ts
- packages/ui/src/components/Visualization/Canvas/CanvasSideBar.test.tsx
- packages/ui/src/components/Visualization/Canvas/Form/CanvasForm.test.tsx
- packages/ui/src/components/Visualization/Canvas/Form/CanvasFormBody.tsx
- packages/ui/src/components/Visualization/Canvas/Form/CanvasFormHeader.test.tsx
- packages/ui/src/components/Visualization/Canvas/Form/CanvasFormHeader.tsx
- packages/ui/src/providers/canvas-form-tabs.provider.test.tsx
- packages/ui/src/providers/canvas-form-tabs.provider.tsx
- packages/ui/src/stubs/TestUniformsWrapper.tsx
- packages/ui/src/stubs/timer.component.schema.ts
- packages/ui/src/utils/get-field-groups.test.ts
- packages/ui/src/utils/index.ts
- packages/ui/src/utils/join-path.test.ts
- packages/ui/src/utils/join-path.ts
This handles styling topics around the `PropertiesField`.
* When the PropertiesField contains properties, the expandable section is expanded by default
* Reduced the left and right padding
* Changes the containing `Td` so it can limit the overflow
* Add a few missing tests
| --- | --- |
| ![image](https://github.com/user-attachments/assets/b3c03f22-94cc-4ccc-8cf3-60685fc2fcba) | ![image](https://github.com/user-attachments/assets/7ebaf553-d13f-467c-a18d-b5e58c0a4d34) |
| ![image](https://github.com/user-attachments/assets/0ea9429a-2d40-46e3-9a99-2bf7a41f89f1) | ![image](https://github.com/user-attachments/assets/19057a25-3732-451e-94a0-7770dad22bc9) |
fix: https://github.com/KaotoIO/kaoto/issues/1473
> fix(CanvasForm): Improvements over the `ParametersField` component

- CONTRIBUTING.md
- README.md
- packages/catalog-generator/pom.xml
- packages/catalog-generator/src/main/java/io/kaoto/camelcatalog/generator/CamelCatalogProcessor.java
- packages/catalog-generator/src/test/java/io/kaoto/camelcatalog/commands/GenerateCommandTest.java
Currently, the `catalog-generator` requires Java 21.
While that enables modern syntax, not all users have it installed in their machines, so in order to lower the contribution requirements, we're lowering the required version to be Java 17.
By default, in RHEL 9.0, Java 17 is preinstalled.
Here is an extract of the available Java version per RHEL version
| RHEL Version | Java version | Release date |
| --- | --- | --- |
| RHEL 7 | Java 8  | June 10, 2014 |
| RHEL 8 | Java 11 | May 7, 2019   |
| RHEL 9 :point_left: we're here | Java 17 | May 17, 2022  |
fix: https://github.com/KaotoIO/kaoto/issues/1476
> chore(catalog-generator): Lower the required Java version to 17

- packages/catalog-generator/src/main/java/io/kaoto/camelcatalog/generator/CamelCatalogProcessor.java
fixes https://github.com/KaotoIO/kaoto/issues/440
Expression:
|--------|--------|
| ![Screenshot from 2024-10-02 12-45-33](https://github.com/user-attachments/assets/9b2514b5-f921-405a-885a-3d8ecb678681) | ![Screenshot from 2024-10-02 12-46-18](https://github.com/user-attachments/assets/d492408d-c962-466e-bab2-dc40e09c5dc9) | 
| ![image](https://github.com/user-attachments/assets/159b6ebc-9b5b-4e8f-a79a-3a30908b0416) | ![image](https://github.com/user-attachments/assets/75c39b48-3f7c-4766-8101-5b08bb9a0977) | 
Dataformat:
|--------|--------|
| ![Screenshot from 2024-10-02 12-49-38](https://github.com/user-attachments/assets/0bda8165-3107-4e7b-9fef-e17983c3ac79) | ![Screenshot from 2024-10-02 12-50-02](https://github.com/user-attachments/assets/35b6813c …
> fix(440): Sort language/dataformat properties with catalog index order

- packages/ui/src/multiplying-architecture/KaotoEditorChannelApi.ts
relates to kaotoio/vscode-kaoto#681
> Define deleteContent API in ChannelEditor

- packages/ui/src/layout/TopBar.tsx
Adding the link to the kaoto-examples repository
> chore: Add kaoto examples link

- packages/catalog-generator/pom.xml
- packages/catalog-generator/src/main/java/io/kaoto/camelcatalog/generator/CamelCatalogProcessor.java
Starting from Camel 4.5.0, the `label` property from EIP was renamed to `group`.
This PR handles that change and uses whatever is available at the moment of creating the catalog. In addition to that, it changed the scope of the `camel-yaml-dsl` dependency because it was forcing the catalog generator to use the latest YAML DSL schema, failing to generate older catalog versions.
| --- | --- |
| ![image](https://github.com/user-attachments/assets/c551119b-e3fb-42c8-be29-533d963e70de) | ![image](https://github.com/user-attachments/assets/8e4ed582-4f67-48cf-9905-5295bf7ea0ec) |
fix: https://github.com/KaotoIO/kaoto/issues/1381
> fix(catalog-generator): Use Label or Group for the EIP parameters grouping

- packages/catalog-generator/package.json
On CI, the log cannot be correctly displayed and parsed in the GitHub default UI due to the large amount of it, mainly due to the download transfer progress of Maven components. Consequently, using `--no-transfer-progress` on the first Maven build to reduce the amount of logs.
Also updated Maven lifecycle phase, removed the verify phase as it is included in the install phase. See
https://maven.apache.org/guides/introduction/introduction-to-the-lifecycle.html#a-build-lifecycle-is-made-up-of-phases for reference
> Reduce Maven download log

- packages/catalog-generator/package.json
- keep a separate `build:mvn` for ease of read
- currently there is no integration test and no need to install locally the generated artifact, so using `package` phase only (and not install or verify)
- the impact of the change is that there will be `mvn clean` called also when calling directly `yarn run build:default:catalog`, which I think is acceptable
- it is saving ~30 seconds of build time on CI
> chore: Avoid double Maven build

- packages/catalog-generator/pom.xml
this is the version aligned with Camel 4.8.0
> feat: Update default Camel Quarkus catalog version from 3.14.0 to 3.15.0

- packages/catalog-generator/src/main/java/io/kaoto/camelcatalog/generator/CamelCatalogProcessor.java
- packages/catalog-generator/src/test/java/io/kaoto/camelcatalog/generator/CamelCatalogProcessorTest.java
Fixes #1443,
- Before 
- After
> Fix(catalog): Load required fields for Expressions, Data-formats and Load-balancers

- packages/catalog-generator/src/main/java/io/kaoto/camelcatalog/generator/CamelYamlDslSchemaProcessor.java
- packages/catalog-generator/src/test/java/io/kaoto/camelcatalog/generator/CamelCatalogProcessorTest.java
- packages/catalog-generator/src/test/java/io/kaoto/camelcatalog/generator/CamelYamlDSLKeysComparatorTest.java
- packages/catalog-generator/src/test/java/io/kaoto/camelcatalog/generator/CamelYamlDslSchemaProcessorTest.java
- packages/catalog-generator/src/test/java/io/kaoto/camelcatalog/generator/K8sSchemaProcessorTest.java
- packages/catalog-generator/src/test/java/io/kaoto/camelcatalog/generator/KameletProcessorTest.java
- packages/catalog-generator/src/test/java/io/kaoto/camelcatalog/generator/UtilTest.java
- packages/catalog-generator/src/test/resources/camel-4.9.0-tokenizer-schema.json
- packages/ui/src/components/Form/CustomAutoField.test.tsx
- packages/ui/src/components/Form/CustomAutoField.tsx
- packages/ui/src/components/Form/CustomAutoFields.test.tsx
- packages/ui/src/components/Form/CustomAutoFields.tsx
- packages/ui/src/components/Form/OneOf/OneOfField.test.tsx
- packages/ui/src/components/Form/OneOf/OneOfField.tsx
- packages/ui/src/components/Form/OneOf/OneOfSchemaList.scss
- packages/ui/src/components/Form/OneOf/OneOfSchemaList.tsx
- packages/ui/src/components/Form/OneOf/__snapshots__/OneOfField.test.tsx.snap
- packages/ui/src/components/Form/OneOf/__snapshots__/OneOfSchemaList.test.tsx.snap
- packages/ui/src/components/Form/customField/CustomNestField.test.tsx
- packages/ui/src/components/Form/customField/CustomNestField.tsx
Currently, we have partial support for the `oneOf` schemas.
This commit cleans up the generated schemas, by removing the `not` definition from `oneOf` and also removing the empty properties like:
```
{
property: { }
}
```
Test the changes live: https://lordrip.github.io/kaoto/
```yaml
- errorHandler: {}
```
fix: https://github.com/KaotoIO/kaoto/issues/1550
fix: https://github.com/KaotoIO/kaoto/issues/948
> feat(ConfigForm): Add support for oneOf fields

- packages/ui/src/components/Catalog/Catalog.tsx
- packages/ui/src/components/Catalog/filter-tiles.test.ts
- packages/ui/src/components/Catalog/filter-tiles.ts
- Implement scoring logic based on search term matches in name, title, and description
- Filter tiles by score, selected tags, and providers
- Sort filtered tiles by descending score
- Group the sorted tiles by their type
| --- | --- |
| ![image](https://github.com/user-attachments/assets/1831e676-fdb5-44cb-85ea-6c05233d111d) | ![image](https://github.com/user-attachments/assets/2a5ec13b-c18b-4814-bae8-b92572b148fe) |
> Enhance filterTiles with scoring, filtering, and sorting

- packages/ui-tests/cypress/e2e/designer/sidepanelConfig/producerConsumerConf.cy.ts
- packages/ui-tests/cypress/fixtures/flows/camelRoute/consumerProducer.yaml
e2e coverage for https://github.com/KaotoIO/kaoto/issues/992
> e2e(992): test for consumer/producer properties in the CanvasForm

- packages/ui/src/components/Visualization/Canvas/Canvas.tsx
fix: https://github.com/KaotoIO/kaoto/issues/606
> Auto-close sidebar and unselect node on canvas click

- packages/catalog-generator/src/main/java/io/kaoto/camelcatalog/generator/Util.java
- packages/catalog-generator/src/test/java/io/kaoto/camelcatalog/commands/GenerateCommandOptionsTest.java
- packages/catalog-generator/src/test/java/io/kaoto/camelcatalog/commands/GenerateCommandTest.java
Currently, the `catalog-generator` tests are failing in Microsoft Windows due to the file separator.
This PR fixes it by using the underlying OS file separator instead.
> fix(catalog-generator): Fix Windows tests

- packages/ui/src/models/visualization/flows/support/flows-visibility.test.ts
- packages/ui/src/models/visualization/flows/support/flows-visibility.ts
- packages/ui/src/providers/visible-flows.provider.tsx
When an entity is updated, for instance, by adding a new component, the VisibleFlows object gets recreated, causing some 'useEffects' to be triggered twice.
| --- | --- |
| ![image](https://github.com/user-attachments/assets/d7bfd68c-e559-4399-8520-b0bf8e14ccde) | ![image](https://github.com/user-attachments/assets/c9bf7e2b-36c7-466e-82e8-bde06ca81dcc) |
> fix(Canvas): Avoid recreating the VisibleFlows object

- packages/ui/src/components/Visualization/Custom/ContextMenu/ItemDisableStep.tsx
fix: https://github.com/KaotoIO/kaoto/issues/1117
> feat #1117: Add EnableAll menu item when routes include multiple disabled steps

- packages/ui/package.json
- packages/ui/vite.config.js
- yarn.lock
Kaoto uses `vite` to bundle the project in dev mode using the `legacy` sass API.
With the upcoming `sass` 2.0, some APIs were marked for removal and show warnings.
This commit follows the [vite
docs](https://vite.dev/config/shared-options#css-preprocessoroptions) and sets the css preprocessor config to `modern-compiler`, in addition to that, replaces the `sass` package with `sass-embedded`
> fix(build): Fix sass-related deprecation notice

- packages/ui/src/models/camel/camel-route-resource.test.ts
- packages/ui/src/models/camel/camel-route-resource.ts
When adding an `onException` to the Canvas, it's created at the end of the YAML, but it should be created at the beginning instead.
fix: https://github.com/KaotoIO/kaoto/issues/1577
> fix(Resources): onException should be created at the top

- packages/ui/src/components/Visualization/Canvas/__snapshots__/Canvas.test.tsx.snap
- packages/ui/src/components/Visualization/Canvas/__snapshots__/flow.service.test.ts.snap
- packages/ui/src/components/Visualization/Canvas/canvas.defaults.ts
- packages/ui/src/components/Visualization/Canvas/flow.service.ts
- packages/ui/src/components/Visualization/Custom/Group/CustomGroupExpanded.tsx
- packages/ui/src/tests/__snapshots__/nodes-edges.test.ts.snap
In order to make room for the node's secondary label, the containers were expanded by `10px`.
The problem comes when in vertical layout, that additional size is not taken into account when calculating the edges since the size is only reflected in the visualization part and not during the layout calculation.
The solution for now is to increase the group padding just a bit to make the secondary label to fit.
| --- | --- |
| ![image](https://github.com/user-attachments/assets/23f15142-c99f-47e8-b364-5aaafc5c8998) | ![image](https://github.com/user-attachments/assets/5b37bf5e-16ef-45b1-90be-8e55b17e4f8e) |
fix: https://github.com/KaotoIO/kaoto/issues/1575
> fix(Canvas): Fix Edge source misplaced for containers

- packages/ui/src/layout/TopBar.tsx
> chore(links): Add Camel and Hawtio links

- packages/catalog-generator/src/main/java/io/kaoto/camelcatalog/generator/CamelCatalogProcessor.java
In the following Camel versions, a new `errorHandler` property was added to the `RouteDefinition` to allow different `errorHandlers` per route.
* 4.4.x
* 4.5.0
The issue with that is the `errorHandler` property is present in the YAML schema but not in the `RouteDefinition` model, making the generation fail.
As a workaround, this commit ignores the missing properties from the model, but is present in the YAML DSL.
The result of this is the `errorHandler` property missing in the configuration form but present in the YAML DSL.
> fix(Catalog): Ignore missing `model` properties

- packages/ui/src/components/Visualization/Canvas/__snapshots__/Canvas.test.tsx.snap
- packages/ui/src/components/Visualization/Custom/Group/CustomGroupExpanded.scss
- packages/ui/src/components/Visualization/Custom/Group/CustomGroupExpanded.tsx
- packages/ui/src/components/Visualization/Custom/Node/CustomNode.scss
- packages/ui/src/components/Visualization/Custom/Node/CustomNode.tsx
Currently, when opening the step toolbar upon hovering over a node or a group, the hover style is lost when hovering over the toolbar.
This commit retains the hover styling when the toolbar is open.
| Before |After |
| --- | --- |
| ![image](https://github.com/user-attachments/assets/3d2af327-de1e-43bc-abbb-3b3fe2b7ee9d) | ![image](https://github.com/user-attachments/assets/fe397c26-2b1f-49f9-8fac-405d36e6835e) |
> feat(Canvas): Use hover styles upon open toolbar

- packages/catalog-generator/scripts/json-schema-to-typescript.mts
Currently, building Kaoto on Windows is broken due to a problem resolving the base path of the catalog related to the folder separator.
The fix is to use the `pathToFileURL` function at all times when resolving paths, so the folder and file paths gets properly resolved.
fix: https://github.com/KaotoIO/kaoto/issues/1592
> fix(Build): Fix Windows build

- packages/ui-tests/cypress/e2e/designer/rootContainerConfig/rootContainersConf.cy.ts
- packages/ui-tests/cypress/e2e/designer/specialCamelRoutes/routeConfiguration.cy.ts
- packages/ui/src/components/Visualization/Canvas/Canvas.test.tsx
- packages/ui/src/models/visualization/flows/abstract-camel-visual-entity.test.ts
- packages/ui/src/models/visualization/flows/abstract-camel-visual-entity.ts
- packages/ui/src/models/visualization/flows/camel-error-handler-visual-entity.ts
- packages/ui/src/models/visualization/flows/camel-route-visual-entity.test.ts
- packages/ui/src/models/visualization/flows/kamelet-visual-entity.test.ts
- packages/ui/src/models/visualization/flows/kamelet-visual-entity.ts
- packages/ui/src/models/visualization/flows/support/camel-component-schema.service.test.ts
- packages/ui/src/models/visualization/flows/support/camel-component-schema.service.ts
Currently, the root groups use the `id` or the `name` as a label.
This commit adds the possibility to use the `description`, if configured, instead.
| --- | --- |
| ![image](https://github.com/user-attachments/assets/04a797b3-1266-4ad0-bbfb-5c43b664cf79) | ![image](https://github.com/user-attachments/assets/0567bc53-c96f-43e7-a0af-f23ed45a9594) |
fix: https://github.com/KaotoIO/kaoto/issues/1581
> fix(Canvas): Use description for root groups

- packages/catalog-generator/src/main/java/io/kaoto/camelcatalog/generator/CatalogGenerator.java
- packages/catalog-generator/src/main/java/io/kaoto/camelcatalog/maven/CamelCatalogVersionLoader.java
- packages/catalog-generator/src/test/java/io/kaoto/camelcatalog/commands/GenerateCatalogWithRedHatVersionTest.java
the test is passing locally for me despite i checked settings.xml to not have the red hat maven repoitory and remove the org.apache/camel folder from my .m2 so maybe another specific part is failing?
relates to https://github.com/KaotoIO/kaoto/issues/1597
> Fix loading of Red Hat artifacts for catalog

- packages/catalog-generator/package.json
- packages/catalog-generator/scripts/build-catalogs.mjs
Currently, only the latest Camel version is available in the catalog.
This commit includes RHBAC versions in the Kaoto catalog.
fix: https://github.com/KaotoIO/kaoto/issues/1392
> feat(Catalog): Include RHBAC in the catalogs

- packages/ui/src/components/Visualization/ContextToolbar/Flows/FlowsList.test.tsx
- packages/ui/src/components/Visualization/ContextToolbar/Flows/FlowsList.tsx
Currently, when deleting a flow, the confirmation modal is not properly evaluated, leading to always deleting the flow regardless of the user's choice.
The fix is to check the return of the modal and act in consequence.
fix: https://github.com/KaotoIO/kaoto/issues/1660
> fix(FLowsList): Evaluate action confirmation when deleting a Flow

- packages/ui/src/models/visualization/flows/support/camel-component-default.service.test.ts
- packages/ui/src/models/visualization/flows/support/camel-component-default.service.ts
fix: https://github.com/KaotoIO/kaoto/issues/1674
> fix(Canvas): Valid `otherwise` and `doFinally`

- packages/catalog-generator/scripts/build-catalogs.mjs
> Add Camel Main and Spring Boot 4.8 productized to the list of catalog

- packages/ui/src/components/InlineEdit/InlineEdit.test.tsx
- packages/ui/src/components/InlineEdit/InlineEdit.tsx
- packages/ui/src/components/Visualization/Canvas/Canvas.test.tsx
- packages/ui/src/components/Visualization/Canvas/Form/CanvasForm.test.tsx
- packages/ui/src/components/Visualization/ContextToolbar/Flows/FlowsList.scss
- packages/ui/src/components/Visualization/ContextToolbar/Flows/FlowsList.test.tsx
- packages/ui/src/components/Visualization/ContextToolbar/Flows/FlowsList.tsx
- packages/ui/src/components/Visualization/ContextToolbar/Flows/FlowsMenu.scss
- packages/ui/src/components/Visualization/ContextToolbar/Flows/FlowsMenu.test.tsx
- packages/ui/src/components/Visualization/ContextToolbar/Flows/FlowsMenu.tsx
- packages/ui/src/providers/visible-flows.provider.tsx
- packages/ui/src/stubs/TestProvidersWrapper.tsx
Currently, there's no mechanism to toggle all flow visibility.
This commit enables that functionality by adding a top `Eye` icon to show or hide all flows.
fix: https://github.com/KaotoIO/kaoto/issues/1655
> feat(FlowsList): Toggle all flows visibility

- packages/ui/src/components/Visualization/ContextToolbar/Flows/FlowsList.test.tsx
- packages/ui/src/components/Visualization/ContextToolbar/Flows/FlowsList.tsx
- packages/ui/src/components/Visualization/Custom/ContextMenu/ItemDeleteGroup.test.tsx
- packages/ui/src/components/Visualization/Custom/hooks/delete-group.hook.tsx
- packages/ui/src/providers/action-confirmation-modal.provider.scss
- packages/ui/src/providers/action-confirmation-modal.provider.tsx
fixes https://github.com/KaotoIO/kaoto/issues/1657
> fix(1657): better name as subject when deleting a flow

- packages/catalog-generator/src/main/java/io/kaoto/camelcatalog/commands/GenerateCommand.java
- packages/catalog-generator/src/test/java/io/kaoto/camelcatalog/commands/GenerateCommandTest.java
- packages/ui/vite.config.js
Currently, dev mode is broken in Windows since the `vite.config.js` file is not copying the catalog files properly. In addition to that, the file paths are generated using the underlying OS path separator.
The fix is to use the `normalizePath` function from `vite`, so it uses a Linux-like path to copy the files. From the Catalog generator part, it forces the use of the `/` as a path separator so it loads properly in the browser.
fix: https://github.com/KaotoIO/kaoto/issues/1654
> fix(Build): Run Kaoto in Windows

- packages/catalog-generator/scripts/build-catalogs.mjs
- packages/ui/src/components/Form/dataFormat/DataFormatEditor.test.tsx
- packages/ui/src/models/visualization/flows/support/__snapshots__/camel-component-schema.service.test.ts.snap
wondering if we should wait for Camel Kamelet and Camel Quarkus aligned with that too.
belongs to #1695
> feat: Add 4.9.0 to Catalog for Main and Spring Boot

- packages/catalog-generator/scripts/build-catalogs.mjs
1. Separate each version into its own line, so we avoid conflicts whenever versions are updated in separate PRs
2. Align Quarkus versions to the "Last version, latest 2 LTS versions" approach
3. Add comments about what underlying Camel version is embedded in the Quarkus version
Output of the `camel version list --fresh --runtime=quarkus` command
```bash
$ camel version list --fresh --runtime=quarkus
CAMEL VERSION   QUARKUS    JDK   KIND     RELEASED     SUPPORTED UNTIL 
...   
4.4.2        3.8.2    17,21  LTS         May 2024    February 2025 
4.4.3        3.8.3    17,21  LTS        July 2024    February 2025 
4.4.4        3.8.4    17,21  LTS    November 2024    February 2025 
4.5.0       3.10.0    17,21            April 2024                  
4.6.0       3.11.0    17,21              May …
```
> chore: Update quarkus versions

- packages/ui/src/assets/settingsSchema.json
- packages/ui/src/components/Form/CustomAutoForm.scss
- packages/ui/src/components/Form/CustomAutoForm.tsx
- packages/ui/src/components/Settings/__snapshots__/SettingsForm.test.tsx.snap
- packages/ui/src/models/settings/localstorage-settings-adapter.test.ts
- packages/ui/src/models/settings/settings.model.ts
- packages/ui/src/multiplying-architecture/KaotoEditorFactory.test.ts
- packages/ui/src/providers/__snapshots__/settings.provider.test.tsx.snap
Currently, there's no mechanism to enable experimental features.
This PR adds a new `experimentalFeatures` section to include long-running features that still are in the experimental phase.
relates: https://github.com/KaotoIO/kaoto/issues/80
prerequisite of: https://github.com/KaotoIO/kaoto/pull/1620
> chore(Settings): Add experimental features

- packages/ui/src/components/Visualization/Custom/Group/CustomGroupExpanded.tsx
- packages/ui/src/components/Visualization/Custom/Node/CustomNode.scss
- packages/ui/src/components/Visualization/Custom/Node/CustomNode.tsx
- packages/ui/src/components/Visualization/Custom/Node/PlaceholderNode.scss
- packages/ui/src/components/Visualization/Custom/Node/PlaceholderNode.tsx
- packages/ui/src/components/Visualization/Custom/_custom.scss
- packages/ui/src/components/Visualization/Custom/customComponentUtils.ts
- packages/ui/src/models/visualization/base-visual-entity.ts
- packages/ui/src/models/visualization/flows/abstract-camel-visual-entity.ts
- packages/ui/src/models/visualization/flows/camel-error-handler-visual-entity.ts
- packages/ui/src/models/visualization/flows/camel-rest-configuration-visual-entity.ts
- packages/ui/src/models/visualization/flows/pipe-visual-entity.ts
- packages/ui/src/models/visualization/visualization-node.ts
Fixes #80 partially
Following are the changes coming with this PR:
- Enabled DND of nodes over other nodes.
- Enabled containers drag only when collapsed.
- Added Visual Feedback when DND on nodes.
- Added feature flag for the DND on the settings page.
- Enabled re-arrangement of when/doCatch containers in case of choice/doTry.
Above changes can be tested live [here](https://shivamg640.github.io/kaoto/).
Note:
- We have restricted group drop on placeholder as there are few breaking cases which needs to be handled.
- There is known console error on every successful drag and drop which needs some attention.
> Feat(DND): Enable Simple DND

- packages/ui-tests/stories/settings/SettingsForm.stories.tsx
- packages/ui/src/assets/settingsSchema.json
- packages/ui/src/components/Settings/SettingsForm.test.tsx
- packages/ui/src/components/Settings/SettingsForm.tsx
Fixes #1885 
This PR adds the following 2 improvements:
1. Navigating to design page on settings save.
2. Fix the console error on loading the settings page
> Fix: Navigate to design page on settings save

- packages/catalog-generator/src/main/java/io/kaoto/camelcatalog/generator/CamelCatalogProcessor.java
- packages/catalog-generator/src/main/java/io/kaoto/camelcatalog/generator/CamelYamlDslSchemaProcessor.java
- packages/catalog-generator/src/test/java/io/kaoto/camelcatalog/generator/CamelCatalogProcessorTest.java
- packages/ui/src/models/camel/camel-route-resource.ts
- packages/ui/src/models/visualization/flows/camel-rest-configuration-visual-entity.ts
- packages/ui/src/models/visualization/flows/camel-rest-visual-entity.test.ts
- packages/ui/src/models/visualization/flows/camel-rest-visual-entity.ts
- packages/ui/src/models/visualization/flows/support/camel-component-default.service.ts
- packages/ui/src/models/visualization/flows/support/camel-component-filter.service.ts
- packages/ui/src/models/visualization/flows/support/camel-component-schema.service.ts
- packages/ui/src/models/visualization/flows/templates/rest.ts
- packages/ui/src/stubs/rest.ts
This commit adds support for the Rest DSL from Apache Camel.
As @apupier spotted, there are two groups of issues that needs to be handled separately:
uniforms-patternfly-related issues:
- on first save, some invalid block code is added
- cannot remove a security definitions if you provide a boolean or dropdown value first, then you try to remove the content, it will keep some of them (boolean/dropdown) or use empty curly brace:
CanvasFormBody filtering issues: (https://github.com/KaotoIO/kaoto/issues/1890)
- the required fields are not appearing in the Required tab
- In modified tab, all nested fields are appearing
https://github.com/user-attachments/assets/e7b189ff-1f0f-4f71-ae80-d73504225bd8
fix: https://github.com/KaotoIO/kaoto/issues/1505
partially implements: …
> feat(Rest): Add Rest visual entity

- packages/ui-tests/cypress/e2e/codeEditor/sourceCodeActions.cy.ts
- packages/ui-tests/cypress/e2e/designer/propsWarnings/mandatoryPropsWarnings.cy.ts
- packages/ui/src/models/visualization/flows/pipe-visual-entity.test.ts
- packages/ui/src/models/visualization/flows/pipe-visual-entity.ts
Currently, the Kamelet name is being used as ID for the canvas node, causing to have duplicated IDs when a Kamelet is added twice or more times in a Pipe.
The fix is to use the `path` instead.
| --- | --- |
| ![image](https://github.com/user-attachments/assets/c75f089d-b52b-4658-b572-a655308550cc) | ![image](https://github.com/user-attachments/assets/a6a00a56-3b37-4da0-abbe-76fc5d5f5f96) |
fix: https://github.com/KaotoIO/kaoto/issues/1873
> fix(Pipe): Use path as ID

- packages/ui-tests/cypress/e2e/codeEditor/sourceCodeActions.cy.ts
- packages/ui-tests/cypress/e2e/designer/branchingFlows/branchingStepAddition.cy.ts
- packages/ui-tests/cypress/support/cypress.d.ts
- packages/ui-tests/cypress/support/next-commands/design.ts
- packages/ui/src/components/Visualization/Canvas/__snapshots__/Canvas.test.tsx.snap
- packages/ui/src/components/Visualization/Canvas/__snapshots__/flow.service.test.ts.snap
- packages/ui/src/components/Visualization/Canvas/flow.service.test.ts
- packages/ui/src/components/Visualization/Canvas/flow.service.ts
- packages/ui/src/tests/__snapshots__/nodes-edges.test.ts.snap
Currently, edge IDs are not scoped to the owner flow, causing to be duplicated in case two flows use the same step combination.
The fix is to scope the edge ID as well, so we avoid duplication.
| --- | --- |
| ![image](https://github.com/user-attachments/assets/c08163a2-7c7c-4587-b4e2-013e6f1b7d20) | ![image](https://github.com/user-attachments/assets/b57aac3a-e9c3-4353-9dc8-7ec182e36101) |
fix: https://github.com/KaotoIO/kaoto/issues/1897
> fix(Canvas): Duplicated edge IDs

- packages/ui/src/components/Visualization/Custom/Node/CustomNode.tsx
Fixes: #1888
[Screencast from 2025-01-08 16-58-28.webm](https://github.com/user-attachments/assets/96c0d1b3-4947-440a-8434-ccbb619018c0)
> Fix(DND): Fix console errors related to DND

- packages/ui-tests/.storybook/main.ts
- packages/ui/src/components/DataMapper/debug/vite.config.js
- packages/ui/src/components/Document/Document.scss
- packages/ui/src/components/Document/NodeContainer.scss
- packages/ui/src/components/Document/NodeContainer.tsx
- packages/ui/src/providers/datamapper-dnd.provider.scss
- packages/ui/src/providers/datamapper-dnd.provider.tsx
- packages/ui/src/styles/_dnd.scss
- packages/ui/vite.config.js
https://github.com/user-attachments/assets/2d52e753-c4b9-4075-a640-85444034b95e
> fix(Datamapper-styles): fix the PF tokens and tweak DnD styling

- packages/ui-tests/.storybook/main.ts
After forwarding `DragDrop.scss`, we need to instruct `vite` to import files starting with `~` from the `node_modules` folder.
This commit normalizes the required configuration to do so.
Comes from: https://github.com/KaotoIO/kaoto/pull/1927
Relates: https://github.com/KaotoIO/kaoto/pull/1927/files#r1924952467
> chore(vite): Normalize SCSS node_modules imports

- packages/ui/src/components/Form/bean/BeanReferenceField.tsx
- packages/ui/src/components/Form/customField/TypeaheadEditor.tsx
- packages/ui/src/components/Form/customField/TypeaheadField.tsx
- packages/ui/src/components/MetadataEditor/PipeErrorHandlerEditor.tsx
- packages/ui/src/components/Visualization/ContextToolbar/DSLSelector/DSLSelectorToggle/DSLSelectorToggle.tsx
- packages/ui/src/components/Visualization/ContextToolbar/Flows/FlowsMenu.tsx
- packages/ui/src/components/Visualization/EmptyState/FlowType/FlowTypeSelector.tsx
After updating patternfly to v6, the Select component is no longer scrollable.
This commit enables the scrolling back by setting the `isScrollable` attribute.
> fix(Form): Enable scrolling for Selects

- packages/ui/src/components/Form/schema.service.ts
- packages/ui/src/components/Visualization/Canvas/Canvas.tsx
- packages/ui/src/components/Visualization/Canvas/Form/CanvasFormBody.tsx
- packages/ui/src/components/Visualization/Canvas/FormV2/KaotoForm.tsx
- packages/ui/src/components/Visualization/Canvas/FormV2/fields/OneOfField/Typeahead.types.tsx
- packages/ui/src/components/Visualization/Canvas/FormV2/hooks/field-value.ts
- packages/ui/src/components/Visualization/Canvas/FormV2/providers/FormComponentFactoryProvider.tsx
- packages/ui/src/components/Visualization/Canvas/FormV2/providers/ModelProvider.tsx
- packages/ui/src/components/Visualization/Canvas/FormV2/providers/SchemaDefinitionsProvider.tsx
- packages/ui/src/components/Visualization/Canvas/FormV2/providers/SchemaProvider.tsx
- packages/ui/src/utils/get-applied-schema-index.ts
- packages/ui/src/utils/get-value.ts
- packages/ui/src/utils/weight-schemas-against-model.test.ts
- packages/ui/src/utils/weight-schemas-against-model.ts
* Show `DisabledField` for `ArrayField` since they are not implemented yet
* Add support for `omitFields`
* Fix: Avoid `CanvasForm` rerender, causing the model to be loaded twice
* Give higher priority to matching model and schema types for empty models
> feat(form): Form V2 enhancements

- packages/ui/src/components/Visualization/Canvas/FormV2/KaotoForm.tsx
- packages/ui/src/components/Visualization/Canvas/FormV2/fields/OneOfField/OneOfField.tsx
- packages/ui/src/components/Visualization/Canvas/FormV2/hooks/field-value.ts
This PR adds an `useState` in the `KaotoForm` component so it can be rerendered when a property changes, this refreshes the values of every field, allowing the `OneOf` field to always have up-to-date data.
In addition to that, the `OneOf` component introduces a `onSchemaChange` callback that remove the properties from the selected schema before switching to a new one.
part of #1939
> feat(Form): Clean current schema after switching to another schema

- packages/catalog-generator/src/main/java/io/kaoto/camelcatalog/generators/CamelCatalogSchemaEnhancer.java
- packages/catalog-generator/src/main/java/io/kaoto/camelcatalog/generators/EIPGenerator.java
- packages/catalog-generator/src/test/java/io/kaoto/camelcatalog/generators/CamelCatalogSchemaEnhancerTest.java
- packages/catalog-generator/src/test/java/io/kaoto/camelcatalog/generators/EIPGeneratorTest.java
> feat(Catalog): Add CamelCatalogSchemaEnhancer

- packages/catalog-generator/src/main/java/io/kaoto/camelcatalog/generators/CamelCatalogSchemaEnhancer.java
- packages/catalog-generator/src/main/java/io/kaoto/camelcatalog/generators/EIPGenerator.java
- packages/catalog-generator/src/test/java/io/kaoto/camelcatalog/generators/CamelCatalogSchemaEnhancerTest.java
- packages/catalog-generator/src/test/java/io/kaoto/camelcatalog/generators/EIPGeneratorTest.java
> feat(Catalog): Add group/label information

- packages/catalog-generator/src/main/java/io/kaoto/camelcatalog/generators/CamelCatalogSchemaEnhancer.java
- packages/catalog-generator/src/test/java/io/kaoto/camelcatalog/generators/CamelCatalogSchemaEnhancerTest.java
Now, We don't see any "Expression" field in the form:
> Fix(Catalog): Restrict group information for empty EIP properties

- packages/ui/src/components/Visualization/Canvas/FormV2/fields/EnumField.tsx
- packages/ui/src/components/Visualization/Canvas/FormV2/fields/OneOfField/SchemaList.tsx
- packages/ui/src/components/Visualization/Canvas/FormV2/providers/FormComponentFactoryProvider.tsx
- packages/ui/src/components/typeahead/SimpleSelector.tsx
- packages/ui/src/components/typeahead/Typeahead.tsx
- packages/ui/src/components/typeahead/Typeahead.types.tsx
**Context**
Add support for EnumField
part of: https://github.com/KaotoIO/kaoto/pull/1939
> feat(Form): Add EnumField

- packages/ui/src/components/Visualization/Canvas/CanvasSideBar.scss
- packages/ui/src/components/Visualization/Canvas/CanvasSideBar.tsx
- packages/ui/src/components/Visualization/Canvas/__snapshots__/CanvasSideBar.test.tsx.snap
After upgrading to Patternfly v6, the `Card` component has `padding-block-start` and `padding-block-end` CSS properties set to `0.5rem` and that's generating an additional scrollbar in the form.
The fix is to set those properties to 0 for the Form scope.
| --- | --- |
| ![image](https://github.com/user-attachments/assets/bfb8a8a7-0ca2-474e-85ca-47646e476da3) | ![image](https://github.com/user-attachments/assets/140c5188-1239-452c-8a76-f42e68b6765c) |
fix: https://github.com/KaotoIO/kaoto/issues/1944
> fix(CanvasForm): Remove double scrollbar

- packages/ui/src/components/Visualization/Canvas/FormV2/KaotoForm.scss
- packages/ui/src/components/Visualization/Canvas/FormV2/fields/EnumField.tsx
- packages/ui/src/components/Visualization/Canvas/FormV2/fields/FieldWrapper.tsx
- packages/ui/src/components/Visualization/Canvas/FormV2/fields/PasswordField.tsx
- packages/ui/src/components/Visualization/Canvas/FormV2/fields/PropertiesField/PropertiesField.tsx
- packages/ui/src/components/Visualization/Canvas/FormV2/fields/StringField.tsx
- packages/ui/src/components/Visualization/Canvas/FormV2/fields/TextAreaField.tsx
This PR uses the propertyName as the title when the title is not present in the schema.
Part of https://github.com/KaotoIO/kaoto/pull/1939
> fix(Form): Use property name as title if title is not present

- packages/ui/src/components/Visualization/Canvas/FormV2/KaotoForm.scss
Fixes:
1. Fix spacing for collapsed groups
| --- | --- |
| ![image](https://github.com/user-attachments/assets/f18983be-5b51-47da-a1e2-aff0f1205523) | ![image](https://github.com/user-attachments/assets/5ff77495-d0f0-49c6-bc2c-cd8ac52ddaa8) |
part of #1939
> fix(Form): Fix Form styling

- packages/ui/src/components/Visualization/Custom/ContextMenu/ItemReplaceStep.test.tsx
- packages/ui/src/external/RouteVisualization/RouteVisualization.tsx
- packages/ui/src/hooks/entities.test.tsx
- packages/ui/src/hooks/entities.ts
- packages/ui/src/layout/Shell.tsx
- packages/ui/src/models/camel/camel-resource-factory.ts
- packages/ui/src/models/camel/camel-resource.test.ts
- packages/ui/src/models/camel/source-schema-type.test.ts
- packages/ui/src/models/camel/source-schema-type.ts
- packages/ui/src/multiplying-architecture/KaotoBridge.tsx
- packages/ui/src/providers/source-code.provider.test.tsx
- packages/ui/src/providers/source-code.provider.tsx
- packages/ui/src/stubs/TestProvidersWrapper.tsx
- packages/ui/src/utils/event-notifier.test.ts
- packages/ui/src/utils/event-notifier.ts
In relation to https://github.com/KaotoIO/kaoto/pull/2009, we need to add the filename to the source code API to be able to create the appropriate resource with the right serializer.
* Remove `setCurrentSchemaType` API which wasn't used
* Add an optional `path` property to the `setCodeAndNotify` API
* Remove unnecessary methods
> chore: Cleanup create new resource functionality

- packages/catalog-generator/src/main/java/io/kaoto/camelcatalog/commands/GenerateCommand.java
- packages/catalog-generator/src/main/java/io/kaoto/camelcatalog/model/CatalogLibrary.java
- packages/catalog-generator/src/test/java/io/kaoto/camelcatalog/commands/GenerateCommandTest.java
Currently, the Kaoto catalog is not versioned, preventing the project from distinguishing between breaking changes.
This commit adds a version field to tell the UI the catalog format.
fix: https://github.com/KaotoIO/kaoto/issues/2004
> feat(Catalog): Add catalog version

- packages/ui/src/models/camel/camel-route-resource.test.ts
- packages/ui/src/models/camel/camel-route-resource.ts
OnCompletion entities should be placed before existing camel routes; otherwise, it will fail at runtime.
fix: https://github.com/KaotoIO/kaoto/issues/2008
> fix(OnCompletion): Add OnCompletion at the beginning of the route

- packages/catalog-generator/src/main/java/io/kaoto/camelcatalog/generator/CatalogGenerator.java
- packages/catalog-generator/src/main/java/io/kaoto/camelcatalog/generators/EntityGenerator.java
- packages/catalog-generator/src/test/java/io/kaoto/camelcatalog/commands/GenerateCatalogWithRedHatVersionTest.java
- packages/ui/src/pages/Metadata/MetadataPage.test.tsx
- packages/ui/src/pages/Metadata/MetadataPage.tsx
- packages/ui/src/pages/Metadata/__snapshots__/MetadataPage.test.tsx.snap
- packages/ui/src/pages/PipeErrorHandler/PipeErrorHandlerPage.test.tsx
- packages/ui/src/pages/PipeErrorHandler/PipeErrorHandlerPage.tsx
- packages/ui/src/pages/PipeErrorHandler/__snapshots__/PipeErrorHandlerPage.test.tsx.snap
Fixes #2072 partially.
This PR brings the following 2 changes in:
- Using the Kamelet and Pipe Config code inside of the Entities Generator for loading the forms.
- Added **propertiesSchema** to **objectMeta** and **PipeErrorHandler** to mentain the similar structure in the entities Catalog
> Fix: Moved Kamelet and Pipe Configuration schema generation into Entities Generator

- packages/ui/src/multiplying-architecture/KaotoEditor.tsx
- packages/ui/src/multiplying-architecture/KaotoEditorApp.tsx
After merging https://github.com/KaotoIO/kaoto/pull/2081, we're no longer generating schemas for the `Form` component but for the `SourceCodeEditor` component used in the web version.
With this in mind, we no longer need to load said schemas in VS Code, as the `SourceCodeEditor` component is not used there.
> chore(VSCode): Avoid loading JSON Schemas for VS Code

- packages/ui/src/serializers/xml/kaoto-xml-parser.ts
- packages/ui/src/serializers/xml/parsers/beans-xml-parser.test.ts
- packages/ui/src/serializers/xml/parsers/beans-xml-parser.ts
- packages/ui/src/serializers/xml/parsers/expression-parser.test.ts
- packages/ui/src/serializers/xml/parsers/expression-parser.ts
- packages/ui/src/serializers/xml/parsers/rest-xml-parser.test.ts
- packages/ui/src/serializers/xml/parsers/rest-xml-parser.ts
- packages/ui/src/serializers/xml/parsers/route-xml-parser.test.ts
- packages/ui/src/serializers/xml/parsers/route-xml-parser.ts
- packages/ui/src/serializers/xml/parsers/step-parser.test.ts
- packages/ui/src/serializers/xml/parsers/step-parser.ts
- packages/ui/src/serializers/xml/serializers/beans-xml-serializer.test.ts
- packages/ui/src/serializers/xml/serializers/beans-xml-serializer.ts
- packages/ui/src/serializers/xml/serializers/expression-xml-serializer.test.ts
- packages/ui/src/serializers/xml/serializers/expression-xml-serializer.ts
- packages/ui/src/serializers/xml/serializers/kaoto-xml-serializer.test.ts
- packages/ui/src/serializers/xml/serializers/kaoto-xml-serializer.ts
- packages/ui/src/serializers/xml/serializers/rest-xml-serializer.test.ts
- packages/ui/src/serializers/xml/serializers/rest-xml-serializer.ts
- packages/ui/src/serializers/xml/serializers/serializer-test-utils.ts
- packages/ui/src/serializers/xml/serializers/step-xml-serializer.test.ts
- packages/ui/src/serializers/xml/serializers/step-xml-serializer.ts
- packages/ui/src/serializers/xml/xml-parser.test.ts
Changes:
-  - closes #2084 => implement the recognition of the steps and expressions defined only by string not only as a object, for example:
``` yaml 
steps:
- setBody:
constant: Initial message
- to: log:info?showAll=true&multiline=true&logMask=true
```  
- removing incorrect imports in some tests
-  fixed parsing beans constructors when index is not defined: fixes #1998
-  licenses updated
> fix(xml-serializer): Recognise also steps and expressions defined by string

- packages/ui/src/components/Visualization/Canvas/FormV2/fields/BeanField.test.tsx
- packages/ui/src/components/Visualization/Canvas/FormV2/fields/BeanField.tsx
- packages/ui/src/components/typeahead/Typeahead.test.tsx
- packages/ui/src/components/typeahead/Typeahead.tsx
When creating a new bean from the `BeanField`, the list is not updated, making it complicated for picking it up when expanding the list.
This commit updates the list after the bean creation.
fix: https://github.com/KaotoIO/kaoto/issues/2037
> fix(Form): Update Beans list after creation

- packages/ui/src/services/documentation.service.ts
> fix: Remove license header embedded in generated markdown export

- packages/ui/src/components/Visualization/ContextToolbar/ExportDocument/MarkdownComponentMapping.tsx
- packages/ui/src/services/documentation.service.test.ts
- packages/ui/src/services/documentation.service.ts
- packages/ui/src/stubs/kamelet-with-multiline-xml-prop.ts
Fixes: #2096
It replaces the line breaks to `&#10;` and also put `<pre><code>` when the markdown is rendered in the preview through the component mapper. On the other hand it preserves the XML tags as-is in the markdown source code for download to keep property value polution minimal. The markdown renderer would have to disable HTML to render XML tags in the property value.
```md
| Step ID      | Step    | URI          | Parameter Name    | Value                            |
| ------------ | ------- | ------------ | ----------------- | -------------------------------- |
| from-2961    | from    | timer        | period            | {{period}}                       |
|              |         |              | timerName         | user                             |
|              | to      | …
```
> fix(Document Export): Fix multiline property value in the table

- packages/catalog-generator/src/main/java/io/kaoto/camelcatalog/generators/CamelCatalogSchemaEnhancer.java
- packages/catalog-generator/src/test/java/io/kaoto/camelcatalog/generators/CamelCatalogSchemaEnhancerTest.java
- packages/catalog-generator/src/test/java/io/kaoto/camelcatalog/generators/EIPGeneratorTest.java
- packages/ui/src/components/Visualization/Canvas/FormV2/fields/AutoField.tsx
- packages/ui/src/models/visualization/flows/support/validators/model-validation.service.test.ts
- packages/ui/src/models/visualization/flows/support/validators/model-validation.service.ts
> Fix(CanvasForm): Update model validation to support new complex schema

- packages/ui/src/serializers/xml/serializers/beans-xml-serializer.test.ts
- packages/ui/src/serializers/xml/serializers/beans-xml-serializer.ts
fix #2086
When object property in the bean tab is defined, bean-xml serializer will convert it as follows :
```typescript
properties: {
a: value,
nested:{ 
b:value,
c: { c1: value}
}
}
```
to: 
```xml
<properties>
<property key="a" value="value"/>
<property key="nested.b" value="value"/>
<property key="nested.c.c1" value="value"/>
</properties>
```
> fix(beans-xml-serializer): flatten bean object properties

- packages/catalog-generator/src/main/java/io/kaoto/camelcatalog/generators/EIPGenerator.java
- packages/catalog-generator/src/test/java/io/kaoto/camelcatalog/generators/EIPGeneratorTest.java
whenSkipSendToEndpoint was removed from camel-spring XSD schema in camel 3.11.7 and in 4.10 from camel-yaml-dsl.
> fix: exclude whenSkipSendToEndpoint from EIP names in EIPGenerator

- packages/ui/src/components/Visualization/ContextToolbar/Flows/FlowsMenu.scss
- packages/ui/src/components/Visualization/ContextToolbar/Flows/FlowsMenu.tsx
fix https://github.com/KaotoIO/kaoto/issues/1988
removed the split line:
> fix(1988): Flows list doesn't need to be split toggle

- packages/ui/src/models/visualization/flows/support/camel-component-default.service.test.ts
- packages/ui/src/models/visualization/flows/support/camel-component-default.service.ts
When adding a `onFallback` property in the `circuitBreaker` EIP, it's nested one additional level, making the route fail.
This commit adds a default value for `onFallback` to fix this issue.
fix: https://github.com/KaotoIO/kaoto/issues/2119
> fix(SourceCode): OnFallback default generation

- packages/ui/src/utils/camel-uri-helper.test.ts
- packages/ui/src/utils/camel-uri-helper.ts
> fix: (#2121) filter out undefined parameters when creating query string

- packages/ui/src/multiplying-architecture/KaotoBridge.tsx
- packages/ui/src/multiplying-architecture/KaotoEditorApp.tsx
Switching the runtime in VS Code Kaoto, lead to an empty page.
The problem was the following `onReady` callback, switching from `() => void` to `() => Promise<void>`
```tsx
useEffect(onReady, [onReady]);
```
`useEffect` expects a function to return `void ` or another function for cleanup purposes. Originally, the `onReady` callback was a function returning `void`, but with the addition of `XML` support, it was mutated to be an `async` function.
Here's the change: https://github.com/KaotoIO/kaoto/pull/2009/commits/879578d51e5a839447a1198cb6c969aaefd82685#diff-20b60620c7e3be7c2a4671ed42d59c6c7e5340e43993d6b0cc77e27fb9e86d64R97-R100
The fix is to call the `onReady` function isolated, so the `useEffect` doesn't receive an async function.
```tsx
useEffect(() => {
onReady();
}, [onReady]);
``` …
> fix(VSCode): Avoid returning async function in useEffect

- packages/ui/package.json
- yarn.lock
Fixes: #2162
html-to-image version 1.11.13 breaks the route image, as if it doesn't honor some or all of CSS. There're couple of issues reported on html-to-image repo for similar issues that CSS is not honored as expected. We would want to stay with 1.11.11 until the problem is addressed upstream.
> fix(Route Image): Downgrade html-to-image to 1.11.11

- packages/ui/src/App.tsx
For properly parsing the XML catalog has to be available for the parser. Parsers are loaded in the entitiesContext so after initial load catalog was not available. This PR should fix that. 
fix: #2155
> fix: reorder providers for catalog to be available for the entities provider

- packages/ui-tests/cypress/e2e/xmlSupport/basicXml.cy.ts
- packages/ui/src/components/MetadataEditor/__snapshots__/MetadataEditor.test.tsx.snap
- packages/ui/src/components/Settings/__snapshots__/SettingsForm.test.tsx.snap
- packages/ui/src/components/Visualization/Canvas/Form/__snapshots__/CanvasForm.test.tsx.snap
- packages/ui/src/components/Visualization/Canvas/FormV2/__snapshots__/KaotoForm.test.tsx.snap
- packages/ui/src/components/Visualization/Canvas/FormV2/fields/ArrayField/ArrayField.test.tsx
- packages/ui/src/components/Visualization/Canvas/FormV2/fields/BeanField.test.tsx
- packages/ui/src/components/Visualization/Canvas/FormV2/fields/FieldActions.tsx
- packages/ui/src/components/Visualization/Canvas/FormV2/fields/FieldWrapper.test.tsx
- packages/ui/src/components/Visualization/Canvas/FormV2/fields/FieldWrapper.tsx
- packages/ui/src/components/Visualization/Canvas/FormV2/fields/PasswordField.test.tsx
- packages/ui/src/components/Visualization/Canvas/FormV2/fields/PasswordField.tsx
- packages/ui/src/components/Visualization/Canvas/FormV2/fields/StringField.test.tsx
- packages/ui/src/components/Visualization/Canvas/FormV2/fields/StringField.tsx
- packages/ui/src/components/Visualization/Canvas/FormV2/fields/__snapshots__/PasswordField.test.tsx.snap
- packages/ui/src/components/Visualization/Canvas/FormV2/fields/__snapshots__/StringField.test.tsx.snap
- packages/ui/src/components/Visualization/Canvas/FormV2/hooks/field-value.test.tsx
- packages/ui/src/components/Visualization/Canvas/FormV2/hooks/field-value.ts
- packages/ui/src/pages/Metadata/__snapshots__/MetadataPage.test.tsx.snap
This PR creates new drowdown menu for string/password inputs with  option to wrap the input value with `RAW(%s)` : 
fixes: #1666
> feat: Add Raw wrapper for string and password inputs

- packages/ui/src/components/Visualization/ContextToolbar/Flows/FlowsList.tsx
fixes #2183 
Closes the route-list dropdown before showing the delete confirmation modal
> fix(#2183): close routes-list when click on delete

- packages/ui/src/App.tsx
- packages/ui/src/assets/settingsSchema.json
- packages/ui/src/components/Settings/__snapshots__/SettingsForm.test.tsx.snap
- packages/ui/src/components/SourceCode/SourceCode.tsx
- packages/ui/src/components/Visualization/Custom/Group/CustomGroupExpanded.scss
- packages/ui/src/components/Visualization/Custom/Node/CustomNode.scss
- packages/ui/src/components/Visualization/Custom/Node/CustomNode.tsx
- packages/ui/src/models/local-storage-keys.ts
- packages/ui/src/models/settings/localstorage-settings-adapter.test.ts
- packages/ui/src/models/settings/settings.model.ts
- packages/ui/src/multiplying-architecture/KaotoEditor.scss
- packages/ui/src/multiplying-architecture/KaotoEditor.tsx
- packages/ui/src/multiplying-architecture/KaotoEditorApp.test.tsx
- packages/ui/src/multiplying-architecture/KaotoEditorApp.tsx
- packages/ui/src/multiplying-architecture/KaotoEditorFactory.test.ts
- packages/ui/src/providers/__snapshots__/settings.provider.test.tsx.snap
- packages/ui/src/utils/color-scheme.test.ts
- packages/ui/src/utils/color-scheme.ts
This PR adds support for selecting light and dark modes in Kaoto. The mechanism works in 3 ways:
* Auto: It will try to read the preference from the system
* Light: Light mode
* Dark: Dark mode
fix: https://github.com/KaotoIO/kaoto/issues/1543
> feat(UI): Add support for dark mode

- packages/ui/src/components/DataMapper/debug/DebugLayout.test.tsx
- packages/ui/src/components/Document/Document.scss
- packages/ui/src/components/Document/NodeContainer.tsx
- packages/ui/src/components/Document/TargetDocument.tsx
- packages/ui/src/components/Document/actions/ConditionMenuAction.test.tsx
- packages/ui/src/components/Document/actions/ConditionMenuAction.tsx
- packages/ui/src/models/datamapper/visualization.ts
- packages/ui/src/services/document.service.test.ts
- packages/ui/src/services/document.service.ts
- packages/ui/src/services/visualization.service.test.ts
- packages/ui/src/services/visualization.service.ts
Fixes: https://github.com/KaotoIO/kaoto/issues/1845
The 2nd and final step for supporting multiple mappings to the same collection field, adding the UI part of "Add Mapping". It also adds "Add Conditional Mapping" menu which allows to directly add a conditional mapping such as `for-each`, which is a short cut for "Add Mapping" and then "Wrap with for-each" for example.
https://github.com/user-attachments/assets/96f11fd1-425d-4424-b9be-a64ea82fd022
> feat(DataMapper): Allow multiple mappings to the collection field

- packages/ui/src/components/Document/actions/ConditionMenuAction.tsx
- packages/ui/src/components/Visualization/Canvas/FormV2/fields/FieldActions.tsx
- packages/ui/src/components/typeahead/Typeahead.tsx
- packages/ui/src/layout/TopBar.tsx
- packages/ui/src/models/index.ts
- packages/ui/src/models/popper-default.ts
When displaying the Field's contextual menu in VS Code, it gets out of the screen.
The solution is to align the contextual menu to the left, so it renders from the trigger button toward the inner part of the UI.
| --- | --- |
| ![image](https://github.com/user-attachments/assets/83d729f1-6043-4604-a7ed-167125a5ea3a) | ![image](https://github.com/user-attachments/assets/a22150a0-2c8d-444e-9180-fe63e5035c5b) |
fix: https://github.com/KaotoIO/kaoto/issues/2202
> fix(Form): Align Field context menu to the left

- packages/ui/src/components/Visualization/Canvas/FormV2/KaotoForm.test.tsx
- packages/ui/src/components/Visualization/Canvas/FormV2/KaotoForm.tsx
- packages/ui/src/components/Visualization/Canvas/FormV2/__snapshots__/KaotoForm.test.tsx.snap
Currently, when pressing `enter` in some form fields, the `onSubmit` event, making the UI to reload, and in case of VS Code, that leaves the user into a blank page.
The fix is to intercept the `onSubmit` event and stop the default process.
fix: https://github.com/KaotoIO/kaoto/issues/2210
> fix(Form): Prevent onSubmit event from firing

- packages/ui/src/components/Visualization/Custom/Node/CustomNode.scss
fixes https://github.com/KaotoIO/kaoto/issues/2215
> fix(#2215): Azure-related icons seems small

- packages/ui/src/App.test.tsx
- packages/ui/src/App.tsx
- packages/ui/src/components/Visualization/Canvas/Canvas.test.tsx
- packages/ui/src/components/Visualization/Canvas/Canvas.tsx
- packages/ui/src/components/Visualization/Canvas/__snapshots__/Canvas.test.tsx.snap
- packages/ui/src/components/Visualization/Canvas/canvas.defaults.ts
- packages/ui/src/components/Visualization/Canvas/controller.service.test.ts
- packages/ui/src/components/Visualization/Canvas/controller.service.ts
- packages/ui/src/components/Visualization/ContextToolbar/Flows/FlowsList.tsx
- packages/ui/src/components/Visualization/ContextToolbar/Flows/FlowsMenu.tsx
- packages/ui/src/hooks/index.ts
- packages/ui/src/hooks/previous.hook.test.ts
- packages/ui/src/hooks/previous.hook.ts
- packages/ui/src/layout/Shell.test.tsx
- packages/ui/src/layout/Shell.tsx
- packages/ui/src/providers/index.ts
- packages/ui/src/providers/source-code-local-storage.provider.test.tsx
- packages/ui/src/providers/source-code-local-storage.provider.tsx
- packages/ui/src/providers/source-code.provider.test.tsx
- packages/ui/src/providers/source-code.provider.tsx
Currently, when adding or removing steps in the canvas, there's a process of auto-fitting that makes the current zoom and position be lost.
The fix is to remove the `setFitToScreenOnLayout` method call and schedule a single autofit when loading the routes for the first time.
In addition to that, this commit removes the double rendering of the `Canvas` component due to the `SourceCodeProvider` being initialized with an empty string (`""`) and then updated from the `LocalStorage` with an `useEffect` call in the `Shell` component.
fix: https://github.com/KaotoIO/kaoto/issues/2216
> fix(Canvas): Avoid auto-fitting canvas

- packages/ui/src/models/visualization/flows/support/flows-visibility.test.ts
- packages/ui/src/models/visualization/flows/support/flows-visibility.ts
- packages/ui/src/providers/__snapshots__/visible-flows.provider.test.tsx.snap
- packages/ui/src/providers/visible-flows.provider.test.tsx
- packages/ui/src/providers/visible-flows.provider.tsx
- packages/ui/src/utils/index.ts
- packages/ui/src/utils/init-visible-flows.ts
- packages/ui/src/utils/is-same-array.test.ts
- packages/ui/src/utils/is-same-array.ts
Going to the source code editor and pasting a completely new route definition, when returning back to the design page, the route is hidden by default.
The fix is to keep the visibility of the existing routes, if possible. This is possible by checking the IDs from the VisualEntities and comparing them against the VisibleFlows object.
fix: https://github.com/KaotoIO/kaoto/issues/2214
> Fix(Canvas): Making Flows visible after the source code change

- packages/ui/src/components/Visualization/ContextToolbar/ContextToolbar.tsx
- packages/ui/src/multiplying-architecture/KaotoEditor.scss
- packages/ui/src/multiplying-architecture/KaotoEditor.tsx
This PR refines a little bit kaoto style in VS-Code: 
- bottom margin reverted to the original state 
- clean up the tabs layout and contextToolbar: 
Light Theme: 
BEFORE:
Dark Theme:
Before:
> refactor(kaoto-vscode): revert bottom margin for the canvas controls

- packages/ui/src/components/Visualization/Canvas/Canvas.test.tsx
- packages/ui/src/components/Visualization/ContextToolbar/Flows/FlowsList.test.tsx
- packages/ui/src/components/Visualization/ContextToolbar/Flows/FlowsList.tsx
- packages/ui/src/components/Visualization/Custom/ContextMenu/ItemDeleteGroup.test.tsx
- packages/ui/src/components/Visualization/Custom/hooks/delete-group.hook.tsx
- packages/ui/src/models/camel/camel-k-resource.ts
- packages/ui/src/models/camel/camel-resource.ts
- packages/ui/src/models/camel/camel-route-resource.test.ts
- packages/ui/src/models/camel/camel-route-resource.ts
This pull request introduces changes to support bulk deletion of entities in the visualization components and underlying models. It modifies the `removeEntity` method to accept multiple IDs and updates the UI and tests accordingly. The most important changes include refactoring the `removeEntity` method, adding a bulk delete feature in the `FlowsList` component, and updating tests to reflect these changes.
> Feat: Allow to delete filtered/all routes at once

- packages/ui/src/components/DataMapper/debug/DataMapperMonitor.tsx
- packages/ui/src/components/DataMapper/debug/DebugLayout.test.tsx
- packages/ui/src/components/Document/Document.scss
- packages/ui/src/components/Document/NodeContainer.tsx
- packages/ui/src/components/Document/Parameters.tsx
- packages/ui/src/components/Document/SourceDocument.tsx
- packages/ui/src/components/Document/TargetDocument.tsx
- packages/ui/src/components/View/MappingLink.tsx
- packages/ui/src/components/View/SourceTargetView.tsx
- packages/ui/src/hooks/useMappingLinks.tsx
- packages/ui/src/models/datamapper/visualization.ts
- packages/ui/src/providers/data-mapping-links.provider.test.tsx
- packages/ui/src/providers/data-mapping-links.provider.tsx
- packages/ui/src/providers/datamapper-canvas.provider.tsx
- packages/ui/src/services/mapping-links.service.test.ts
- packages/ui/src/services/mapping-links.service.ts
- packages/ui/src/services/mapping.service.test.ts
- packages/ui/src/services/mapping.service.ts
Fixes: #2204
This enables to select and highlight a mapping by clicking a field or a mapping line. If a field is clicked, the mappings clicked field participates are highlighted, which includes source fields, lines and target fields. If a line is clicked, it behaves as if the target field connected to that line is clicked.
https://github.com/user-attachments/assets/5694ffcf-e146-43d8-9a09-bd29e26cb711
> feat(DataMapper): Select a mapping

- packages/ui-tests/cypress/e2e/designer/sidepanelConfig/stepConfiguration.cy.ts
- packages/ui-tests/cypress/e2e/designer/sidepanelConfig/uriRouteConfig.cy.ts
- packages/ui-tests/cypress/e2e/designer/specialCamelRoutes/onException.cy.ts
- packages/ui-tests/cypress/e2e/designer/specialStepConfiguration/dataFormatStepConfig.cy.ts
- packages/ui-tests/cypress/e2e/metadata.cy.ts
- packages/ui-tests/cypress/e2e/pipeErrorHandler.cy.ts
- packages/ui/src/components/Visualization/Canvas/FormV2/fields/StringField.test.tsx
- packages/ui/src/components/Visualization/Canvas/FormV2/fields/StringField.tsx
Currently, `Number` schemas are serialized as `String` due to both schemas using `StringField`.
This commit dynamically chooses how to serialize the value, depending on the schema type and the actual value.
For example, for a `Number` schema, numbers will be serialized as numbers, while placeholders like `{{ property }}` will be serialized as text.
fix: https://github.com/KaotoIO/kaoto/issues/1653
> feat(Form): Dynamically serialize string & numbers

- packages/ui/src/models/datamapper/document.ts
- packages/ui/src/models/datamapper/types.ts
- packages/ui/src/services/document.service.test.ts
- packages/ui/src/services/document.service.ts
- packages/ui/src/services/json-schema-document.service.test.ts
- packages/ui/src/services/json-schema-document.service.ts
- packages/ui/src/stubs/camelYamlDsl.json
- packages/ui/src/stubs/data-mapper.ts
Step1 for https://github.com/KaotoIO/kaoto/issues/1834 - Add [JsonSchemaDocumentService](https://github.com/KaotoIO/kaoto/compare/main...igarashitm:datamapper-json-inspection?expand=1#diff-2ea299a35f085ca0085d0a78e21b033ee3f160f52db13fcfbe4df793e360a57e)
Although there still must be rough edges here and there, it does minimal job so we can go to the next step.
This includes [camelYamlDsl.json](https://github.com/KaotoIO/kaoto/compare/main...igarashitm:datamapper-json-inspection?expand=1#diff-8657b5a4cf0e004736efea797154c754a2a75846c4e150d0f15c9ebd2fc65065) as a test resource, apologize for PR being bigger, however this most complex JSON schema helps a lot to test this JSON schema inspection.
relates: https://github.com/KaotoIO/kaoto/issues/1834
> feat(DataMapper): JSON schema inspection

- packages/ui-tests/package.json
- packages/ui/package.json
- packages/ui/src/multiplying-architecture/KaotoEditorChannelApi.ts
- packages/ui/src/multiplying-architecture/index.ts
- yarn.lock
Define a public API for the suggestions query. It might be beneficial to merge it in a similar order, like @apupier suggested for the Maven-related feature, first define the API, then implement it, and lastly merge this one.
relates: https://github.com/KaotoIO/kaoto/issues/494
relates: https://github.com/KaotoIO/vscode-kaoto/issues/975
> chore(MA): Define public API to query suggestions

- packages/ui/src/models/index.ts
- packages/ui/src/models/runtime-maven-information.ts
- packages/ui/src/public-api.ts
This PR defines the Runtime types from the `camel dependency runtime` command. It can be merged now but it should wait until the next release in order to use it.
relates: https://github.com/KaotoIO/vscode-kaoto/issues/977
> chore: Add MavenRuntime information types

- packages/ui-tests/cypress/e2e/designer/basicNodeActions/hoverToolbarActions.cy.ts
This pull request adds a new test case to the `hoverToolbarActions.cy.ts` file to verify that a group remains collapsed after a route change in the design interface. 
closes: [#1646](https://github.com/KaotoIO/kaoto/issues/1646)
relates to: https://github.com/KaotoIO/kaoto/pull/1922
> test: Add e2e test to check if the group stays collapsed after the route change

- packages/ui-tests/cypress/e2e/xmlSupport/editingSourceXml.cy.ts
- packages/ui-tests/cypress/e2e/xmlSupport/importFileXml.cy.ts
- packages/ui/src/models/visualization/flows/support/camel-component-schema.service.test.ts
- packages/ui/src/models/visualization/flows/support/camel-component-schema.service.ts
- packages/ui/src/serializers/xml/parsers/step-parser.ts
This pull request introduces enhancements to the `CamelComponentSchemaService` and `StepParser` to improve URI parsing and streamline the handling of Camel component definitions. The key changes include the addition of a new method for parsing URIs, updates to unit tests to cover the new functionality.
* **New URI Parsing Method**: Added the `getComponentDefinitionFromUri` method to parse component URIs into structured definitions, including support for path and query parameters.
[[1]](diffhunk://#diff-0c53154d7a0becbc8f47579bcbc55076f6814b5bfa02868cec0de1eeacecb759L176-R183) 
* **Enhanced Attribute Parsing**: Introduced the `parseAttributeType` method to handle `uri` attributes by leveraging the new `getComponentDefinitionFromUri` method from `CamelComponentSchemaService`.
* **Updated …
> fix(xml-step-parser): Parse uri to object with parameters

- packages/ui/src/components/ComponentMode/ComponentMode.scss
- packages/ui/src/components/ComponentMode/ComponentMode.test.tsx
- packages/ui/src/components/ComponentMode/ComponentMode.tsx
- packages/ui/src/components/Visualization/Custom/FloatingCircle/FloatingCircle.scss
- packages/ui/src/components/Visualization/Custom/FloatingCircle/FloatingCircle.test.tsx
- packages/ui/src/components/Visualization/Custom/FloatingCircle/FloatingCircle.tsx
- packages/ui/src/components/Visualization/Custom/FloatingCircle/__snapshots__/FloatingCircle.test.tsx.snap
- packages/ui/src/components/Visualization/Custom/Group/CustomGroupExpanded.scss
- packages/ui/src/components/Visualization/Custom/Group/CustomGroupExpanded.tsx
- packages/ui/src/components/Visualization/Custom/Node/CustomNode.scss
- packages/ui/src/components/Visualization/Custom/Node/CustomNode.tsx
- packages/ui/src/components/Visualization/Custom/_custom.scss
- packages/ui/src/components/registers/RegisterComponents.tsx
- packages/ui/src/components/registers/component-mode.activationfn.test.ts
- packages/ui/src/components/registers/component-mode.activationfn.ts
- packages/ui/src/hooks/processor-icon.hook.test.tsx
- packages/ui/src/hooks/processor-icon.hook.tsx
This commit adds support for the first part of the new `toD` configuration experience.
At this time, we offer the user a mechanism to switch between the related EIPs to leverage the existing configuration. Said EIPs are `to`, `toD`, and `poll`.
relates: https://github.com/KaotoIO/kaoto/issues/2392
> feat(Form): Switch between to, toD and poll

- packages/ui/src/components/Visualization/Canvas/StepToolbar/StepToolbar.tsx
- packages/ui/src/components/Visualization/Custom/ContextMenu/ItemMoveStep.test.tsx
- packages/ui/src/components/Visualization/Custom/ContextMenu/ItemMoveStep.tsx
- packages/ui/src/components/Visualization/Custom/ContextMenu/ItemPasteStep.test.tsx
- packages/ui/src/components/Visualization/Custom/ContextMenu/NodeContextMenu.tsx
- packages/ui/src/components/Visualization/Custom/ContextMenu/__snapshots__/ItemMoveStep.test.tsx.snap
- packages/ui/src/components/Visualization/Custom/hooks/copy-step.hook.test.tsx
- packages/ui/src/components/Visualization/Custom/hooks/copy-step.hook.tsx
- packages/ui/src/components/Visualization/Custom/hooks/move-step.hook.test.tsx
- packages/ui/src/components/Visualization/Custom/hooks/move-step.hook.tsx
- packages/ui/src/models/visualization/flows/__snapshots__/abstract-camel-visual-entity.test.ts.snap
- packages/ui/src/models/visualization/flows/abstract-camel-visual-entity.test.ts
- packages/ui/src/models/visualization/flows/abstract-camel-visual-entity.ts
- packages/ui/src/utils/get-potential-path.test.ts
- packages/ui/src/utils/get-potential-path.ts
Fixes #1484 
Note: This just not works for choice nodes. It enables Move functionality for all entity type!
Check this out here: https://shivamg640.github.io/kaoto/
> feat(move-steps): Reorder steps on the canvas

- packages/ui/src/services/document-util.service.test.ts
- packages/ui/src/services/xml-schema-document.service.test.ts
- packages/ui/src/services/xml-schema-document.service.ts
Fixes: https://github.com/KaotoIO/kaoto/issues/2457
> fix(DataMapper): XML schema parser fails to detect a collection field

- packages/ui/src/components/View/MappingLink.scss
- packages/ui/src/components/View/MappingLink.test.tsx
- packages/ui/src/components/View/MappingLink.tsx
- packages/ui/src/components/View/MappingLinkContainer.scss
- packages/ui/src/components/View/MappingLinkContainer.tsx
- packages/ui/src/components/View/SourceTargetView.scss
- packages/ui/src/components/View/SourceTargetView.tsx
This PR improves the rendering performance of DataMapper edges through several small optimizations:
- Extracted `MappingLinkContainer` from `MappingLink` to reduce component complexity
- Optimized key strategy: Changed to use `sourceNodePath` and `targetNodePath` as `React` keys for better reconciliation and reduced re-renders
- Moved `getX` and `getY` calculations outside render cycle to prevent unnecessary recalculations
- Extracted inline styles into separate SCSS classes for better performance and maintainability
- Added overflow containment to prevent mapping lines from extending outside their container
- Add missing tests for the MappingLink component
relates: https://github.com/KaotoIO/kaoto/issues/2396
> fix(DataMapper): Improve rendering performance - batch 1

- packages/ui/src/models/camel/camel-route-resource.test.ts
- packages/ui/src/models/camel/camel-route-resource.ts
- packages/ui/src/models/camel/entity-ordering.service.test.ts
- packages/ui/src/models/camel/entity-ordering.service.ts
- packages/ui/src/serializers/xml/serializers/kaoto-xml-serializer.test.ts
- packages/ui/src/serializers/xml/serializers/kaoto-xml-serializer.ts
- packages/ui/src/services/documentation.service.test.ts
Currently, new XML entities are added at the end of the document. This is problematic because `outeConfiguration` needs to be defined before `route`.
The fix is to create an `EntityOrderingService` so both `XML` and `YAML` entities are kept in the right order.
fix: https://github.com/KaotoIO/kaoto/issues/2467
> fix(XML): Sort XML and YAML entities

- packages/ui/src/components/Visualization/ContextToolbar/ContextToolbar.tsx
relates: https://github.com/KaotoIO/kaoto/issues/2525
> chore: remove keyboard labels for undo/redo

- packages/ui/src/components/Visualization/Custom/Node/CustomNode.scss
- packages/ui/src/components/Visualization/Custom/Node/CustomNode.tsx
- packages/ui/src/components/Visualization/Custom/_custom.scss
Fix #2516 
Test this change here: https://shivamg640.github.io/kaoto/
> Fix(drag-and-drop): Show different mouse pointers for draggable vs non-draggable nodes

- packages/ui/src/components/Visualization/Canvas/Form/fields/BeanField/BeanField.test.tsx
- packages/ui/src/components/Visualization/Canvas/Form/fields/BeanField/BeanField.tsx
- packages/ui/src/components/Visualization/Canvas/Form/fields/custom-fields-factory.ts
- Add DataSourceBeanField component with predefined default items (default, dataSource)
- Implement DataSource-specific bean filtering to show only beans with DataSource in type
- Configure DataSourceBeanField to use unprefixed bean names
- Add comprehensive test suite covering default items, filtering, and bean creation
- Refactor BeanFieldBase to support optional defaultItems and isDataSource props
#closes [#967](https://github.com/KaotoIO/kaoto/issues/967)
> feat: create DataSourceBeanField with default values and DataSource filtering
