KaotoIO/kaoto

- packages/ui/.lintstagedrc.json
- packages/ui/src/components/README.md
- packages/ui/src/pages/Dashboard/Dashboard.tsx
- packages/ui/src/pages/Dashboard/index.ts
- packages/ui/src/pages/Dashboard/router-exports.tsx
- packages/ui/src/pages/README.md
This pull request adds development documentation about the structure of the `Components` and `Pages` folders and what to expect from them.
> chore(docs): Add README.md files for Components and Pages

- packages/ui/src/components/Canvas/Canvas.tsx
- packages/ui/src/components/Canvas/index.ts
- packages/ui/src/components/SourceCode/SourceCode.tsx
- packages/ui/src/components/SourceCode/index.ts
- packages/ui/src/layout/Navigation.tsx
- packages/ui/src/layout/Shell.tsx
- packages/ui/src/layout/navigation.model.ts
- packages/ui/src/pages/Canvas/CanvasPage.tsx
- packages/ui/src/pages/Canvas/index.ts
- packages/ui/src/pages/Canvas/router-exports.tsx
- packages/ui/src/pages/Dashboard/DashboardPage.tsx
- packages/ui/src/pages/Dashboard/router-exports.tsx
- packages/ui/src/pages/SourceCode/SourceCode.tsx
- packages/ui/src/pages/SourceCode/index.ts
- packages/ui/src/pages/SourceCode/router-exports.tsx
- packages/ui/src/router.tsx
- packages/ui/src/router/links.ts
> chore(visualization): Initial scaffolding for viz components

- README.md
This pull request consolidates multiple commits aimed at elevating the README.md to a new standard of clarity and usability. Specific changes include:
- Introduced a Table of Contents for seamless navigation.
- Reorganized content under logical headers for better scanability.
- Included code snippets for a more hands-on guide to setup and build steps.
- Fine-tuned language and instructions for greater clarity.
- Incorporated italics to emphasize key notes and critical steps.
- Harmonized code snippet styles to enhance readability.
- Utilized underscores to indicate optional steps, simplifying the user journey.
This concerted effort to make the README more user-friendly and clear aims to assist both newcomers and existing contributors in understanding how to navigate and utilize the …
> Comprehensive README Refactoring for Improved Usability

- packages/ui/src/camel-utils/camel-to-table.adapter.test.ts
- packages/ui/src/camel-utils/camel-to-tabs.adapter.test.ts
- packages/ui/src/camel-utils/camel-to-tabs.adapter.ts
- packages/ui/src/components/PropertiesModal/EmptyTableState.tsx
- packages/ui/src/components/PropertiesModal/PropertiesModal.models.ts
- packages/ui/src/components/PropertiesModal/PropertiesModal.test.tsx
- packages/ui/src/components/PropertiesModal/PropertiesModal.tsx
- packages/ui/src/components/PropertiesModal/PropertiesTabs.tsx
- packages/ui/src/components/PropertiesModal/index.ts
- packages/ui/src/models/camel-properties-common.ts
Passing the linter to the `ui` package.
> chore: format files

- .github/workflows/chromatic.yml
Discussed with @igarashitm
similar to the way this is done in Kaoto-ui chromatic [workflow conf](https://github.com/KaotoIO/kaoto-ui/blob/main/.github/workflows/chromatic.yml#L34)
> Add chromatic token to the GH workflow

- packages/ui-tests/.storybook/main.ts
- packages/ui-tests/package.json
- packages/ui-tests/stories/Navigation.stories.tsx
- packages/ui/src/layout/index.ts
- packages/ui/src/public-api.ts
- yarn.lock
Added story for navigation components - `Navigation` and `Shell`
> Add navigation stories to storybook

- packages/camel-catalog/assembly/pom.xml
- packages/camel-catalog/kaoto-camel-catalog-maven-plugin/src/main/java/io/kaoto/camelcatalog/KaotoCamelCatalogMojo.java
- packages/camel-catalog/src/json-schema-to-typescript.mts
> fix: Remove kebab-case YAML schema in favor of camelCase one

- packages/ui/src/camel-utils/camel-to-table.adapter.test.ts
- packages/ui/src/camel-utils/camel-to-table.adapter.ts
Fix for https://github.com/KaotoIO/kaoto-next/issues/61
> fix(gh-61): Get class name from fully qualified name

- packages/ui/src/layout/Shell.scss
- packages/ui/src/layout/TopBar.tsx
- packages/ui/src/router/links.models.ts
Adding a GitHub link to the project
> feat(toolbar): Add GitHub project link

- packages/ui/src/camel-utils/camel-schemas-processor.test.ts
- packages/ui/src/camel-utils/camel-schemas-processor.ts
Fixes: #145
Relates to: https://github.com/KaotoIO/kaoto-next/pull/144
> fix: Fails to load camel schema files

- packages/ui/src/hooks/entities.ts
> fix: Do not make KameletBinding/Pipe an array

- packages/ui-tests/cypress.config.ts
- packages/ui-tests/cypress/e2e/beans.cy.ts
- packages/ui-tests/cypress/e2e/catalog.cy.ts
- packages/ui-tests/cypress/e2e/designer.cy.ts
- packages/ui-tests/cypress/e2e/sourceCode.cy.ts
- packages/ui-tests/cypress/fixtures/flows/Beans.yaml
- packages/ui-tests/cypress/fixtures/flows/CamelRoute.yaml
- packages/ui-tests/cypress/fixtures/flows/Integration.yaml
- packages/ui-tests/cypress/fixtures/flows/KafkaSourceSinkKB.yaml
- packages/ui-tests/cypress/fixtures/flows/TimerKafkaKB.yaml
- packages/ui-tests/cypress/support/cypress.d.ts
- packages/ui-tests/cypress/support/e2e.ts
- packages/ui-tests/cypress/support/next-commands/default.ts
- packages/ui-tests/cypress/support/next-commands/design.ts
- packages/ui-tests/cypress/support/next-commands/sourceCode.ts
- packages/ui-tests/package.json
- packages/ui-tests/tsconfig.json
- packages/ui/src/components/Form/properties/PropertiesField.tsx
- yarn.lock
relates to https://github.com/KaotoIO/kaoto-next/issues/168
This PR does not yet introduce the PR hook, will be added in separate PR.
> chore(tests): Add e2e coverage for newly added functionality

- packages/ui/src/camel-utils/is-kamelet-binding.test.ts
- packages/ui/src/camel-utils/is-kamelet.test.ts
- packages/ui/src/components/Form/properties/AddPropertyButtons.test.tsx
- packages/ui/src/components/Form/properties/PropertyRow.test.tsx
- packages/ui/src/components/MetadataEditor/MetadataEditor.tsx
- packages/ui/src/models/visualization/flows/kamelet-binding.test.ts
- packages/ui/src/models/visualization/flows/kamelet-visual-entity.ts
- packages/ui/src/pages/Beans/BeansPage.tsx
- packages/ui/src/pages/Beans/router-exports.tsx
- packages/ui/src/stubs/kamelet-route.ts
- packages/ui/tsconfig.json
Fix format that triggered auto-format during #201 work. Also added kamelet stub.
> chore: Pre #201: format fix and add kamelet example into stubs

- packages/ui/src/components/Catalog/Catalog.tsx
- packages/ui/src/models/local-storage-keys.ts
fix for: https://github.com/KaotoIO/kaoto-next/issues/184
> feat: persist catalog layout globally

- packages/camel-catalog/assembly/pom.xml
- packages/camel-catalog/assembly/src/main/resources/PipeErrorHandler.json
- packages/camel-catalog/kaoto-camel-catalog-maven-plugin/src/main/java/io/kaoto/camelcatalog/KaotoCamelCatalogMojo.java
- packages/camel-catalog/src/json-schema-to-typescript.mts
Add schema for k8s metadata and Pipe errorHandler
> feat: Support configuring Camel K CR metadata (#181)

- package.json
- packages/ui/package.json
- yarn.lock
Fixing https://security.snyk.io/vuln/SNYK-JS-BABELTRAVERSE-5962462
> fix(security): Update @babel/traverse

- packages/ui/src/components/Visualization/Canvas/Canvas.test.tsx
- packages/ui/src/components/Visualization/Canvas/Canvas.tsx
- packages/ui/src/components/Visualization/Canvas/__snapshots__/Canvas.test.tsx.snap
- packages/ui/src/components/Visualization/ContextToolbar/ContextToolbar.tsx
- packages/ui/src/components/Visualization/ContextToolbar/FlowType/FlowTypeSelector.test.tsx
- packages/ui/src/components/Visualization/ContextToolbar/FlowType/FlowTypeSelector.tsx
- packages/ui/src/components/Visualization/ContextToolbar/FlowType/NewFlow.test.tsx
- packages/ui/src/components/Visualization/ContextToolbar/FlowType/NewFlow.tsx
- packages/ui/src/components/Visualization/ContextToolbar/Flows/FlowsList.css
- packages/ui/src/components/Visualization/ContextToolbar/Flows/FlowsList.scss
- packages/ui/src/components/Visualization/ContextToolbar/Flows/FlowsList.test.tsx
- packages/ui/src/components/Visualization/ContextToolbar/Flows/FlowsList.tsx
- packages/ui/src/components/Visualization/ContextToolbar/Flows/FlowsListEmptyState.tsx
- packages/ui/src/components/Visualization/ContextToolbar/Flows/FlowsMenu.test.tsx
- packages/ui/src/components/Visualization/ContextToolbar/Flows/FlowsMenu.tsx
- packages/ui/src/components/Visualization/Visualization.tsx
- packages/ui/src/hooks/entities.ts
- packages/ui/src/models/camel/source-schema-config.ts
- packages/ui/src/models/visualization/flows/flows-visibility.ts
- packages/ui/src/providers/visible-flows.provider.tsx
Added controls for the multiple-routes support including setting visible route.
> feat(canvas):Add multiple routes control

- packages/ui/src/components/Visualization/Canvas/Canvas.tsx
- packages/ui/src/components/Visualization/Canvas/__snapshots__/Canvas.test.tsx.snap
> fix(viz):  fix opening properties for all nodes

- packages/ui/src/pages/Beans/BeansPage.tsx
> fix: Can't delete all beans using the bean editor

- packages/camel-catalog/assembly/src/main/resources/PipeErrorHandler.json
- packages/ui/src/components/MetadataEditor/PipeErrorHandlerEditor.test.tsx
- packages/ui/src/components/MetadataEditor/PipeErrorHandlerEditor.tsx
- packages/ui/src/pages/PipeErrorHandler/PipeErrorHandlerPage.tsx
- packages/ui/src/stubs/PipeErrorHandler.ts
> feat: Support configuring /PipeSpec/ErrorHandler

- packages/ui/src/models/visualization/flows/support/camel-component-schema.service.ts
Closes #302 
Change title and description
> Fix: change title of section 

- packages/camel-catalog/kaoto-camel-catalog-maven-plugin/src/main/java/io/kaoto/camelcatalog/KaotoCamelCatalogMojo.java
- packages/camel-catalog/package.json
> fix: Support using camel catalog and schema in Jest tests

- packages/ui/src/components/Visualization/Canvas/expression.service.ts
> chore: Add a bit more TSDoc comments

- packages/ui/src/components/Catalog/__snapshots__/DataListItem.test.tsx.snap
- packages/ui/src/components/Catalog/__snapshots__/Tile.test.tsx.snap
- packages/ui/src/components/IconResolver/IconResolver.test.tsx
- packages/ui/src/components/IconResolver/IconResolver.tsx
fixes https://github.com/KaotoIO/kaoto-next/issues/307
> fix(icons): use same icons from the canvas in Catalog

- packages/ui-tests/cypress/e2e/designer/stepAddition.cy.ts
- packages/ui-tests/cypress/e2e/designer/stepConfiguration.cy.ts
- packages/ui-tests/cypress/e2e/designer/stepRemoval.cy.ts
- packages/ui-tests/cypress/e2e/designer/stepReplacement.cy.ts
- packages/ui-tests/cypress/support/cypress.d.ts
- packages/ui-tests/cypress/support/next-commands/design.ts
> chore(e2e): extend add/replace/remove node in canvas

- packages/ui/src/camel-utils/camel-to-table.adapter.ts
- packages/ui/src/components/PropertiesModal/PropertiesModal.tsx
- packages/ui/src/components/Visualization/Canvas/Canvas.tsx
- packages/ui/src/components/Visualization/Canvas/canvas.defaults.ts
- packages/ui/src/components/Visualization/Canvas/canvas.service.test.ts
- packages/ui/src/components/Visualization/Canvas/canvas.service.ts
- packages/ui/src/components/Visualization/Custom/CustomNode.tsx
At the moment, there are a few circular dependencies between a few files.
* Break circular dependency between `CanvasService` and `CustomNode`
* Break circular dependency between `PropertyModal` and `camel-to-table.adapter`
> chore: Break circular dependencies

- packages/ui/src/components/Visualization/Canvas/canvas.service.ts
| --- | --- |
| ![image](https://github.com/KaotoIO/kaoto-next/assets/16512618/86a780e9-b904-4a18-be79-50d08741e777) | ![image](https://github.com/KaotoIO/kaoto-next/assets/16512618/a0644629-0e00-4be0-8cc4-4b3516902898) |
> Feat(canvas): Reduce node distance

- packages/camel-catalog/kaoto-camel-catalog-maven-plugin/src/main/java/io/kaoto/camelcatalog/CamelYamlDslSchemaProcessor.java
- packages/camel-catalog/kaoto-camel-catalog-maven-plugin/src/test/java/CamelYamlDslSchemaProcessorTest.java
- packages/ui/src/components/MetadataEditor/MetadataEditor.tsx
- packages/ui/src/components/Visualization/Canvas/CanvasForm.tsx
- packages/ui/src/components/Visualization/Canvas/DataFormatEditor.test.tsx
- packages/ui/src/components/Visualization/Canvas/DataFormatEditor.tsx
- packages/ui/src/components/Visualization/Canvas/dataformat.service.test.ts
- packages/ui/src/components/Visualization/Canvas/dataformat.service.ts
- packages/ui/src/models/visualization/flows/camel-catalog.service.ts
Fixes: #273
https://github.com/KaotoIO/kaoto-next/assets/265462/f71adad2-9e89-48d5-9108-91b47181c46c
> feat: Support configuring dataformat in Canvas form

- packages/camel-catalog/pom.xml
> fix maven warnings #390

- packages/camel-catalog/kaoto-camel-catalog-maven-plugin/src/main/java/io/kaoto/camelcatalog/CamelCatalogProcessor.java
- packages/camel-catalog/kaoto-camel-catalog-maven-plugin/src/main/java/io/kaoto/camelcatalog/CamelYamlDslSchemaProcessor.java
- packages/camel-catalog/kaoto-camel-catalog-maven-plugin/src/test/java/CamelCatalogProcessorTest.java
- packages/ui/src/models/camel-catalog-index.ts
- packages/ui/src/providers/catalog.provider.tsx
> catalog model tab shows only processors now

- packages/ui/package.json
- packages/ui/src/components/Visualization/ContextToolbar/ContextToolbar.tsx
- packages/ui/src/components/Visualization/ContextToolbar/FlowExportImage/FlowExportImage.test.tsx
- packages/ui/src/components/Visualization/ContextToolbar/FlowExportImage/FlowExportImage.tsx
- yarn.lock
> introduce a save to image function

- packages/ui/src/components/Visualization/ContextToolbar/FlowType/NewFlow.tsx
- packages/ui/src/hooks/entities.test.tsx
- packages/ui/src/hooks/entities.ts
- packages/ui/src/models/camel/camel-route-resource.ts
- packages/ui/src/models/camel/kamelet-resource.ts
- packages/ui/src/models/camel/pipe-resource.ts
- packages/ui/src/models/visualization/flows/flow-templates-service.ts
- packages/ui/src/models/visualization/flows/support/camel-component-default.service.ts
- packages/ui/src/models/visualization/flows/templates/kamelet.ts
- packages/ui/src/models/visualization/flows/templates/pipe.ts
- packages/ui/src/models/visualization/flows/templates/route.ts
fixes: https://github.com/KaotoIO/kaoto-next/issues/330
> feat(templates): Provide IDs for templates

- packages/ui/src/components/Visualization/Canvas/dataformat.service.test.ts
- packages/ui/src/components/Visualization/Canvas/dataformat.service.ts
> fix: Short form avro dataformat is not correctly parsed

- packages/ui-tests/cypress/support/next-commands/default.ts
- packages/ui/src/pages/Beans/BeansPage.tsx
- packages/ui/src/pages/Catalog/CatalogPage.tsx
- packages/ui/src/pages/Metadata/MetadataPage.tsx
- packages/ui/src/pages/PipeErrorHandler/PipeErrorHandlerPage.tsx
> removing duplicated headers on each page

- packages/ui-tests/cypress/e2e/catalog.cy.ts
- packages/ui-tests/cypress/e2e/designer/stepAddition.cy.ts
- packages/ui-tests/cypress/e2e/designer/stepReplacement.cy.ts
- packages/ui/src/components/Catalog/CatalogFilter.tsx
- packages/ui/src/models/catalog-kind.ts
Mostly textual changes. 
"Search term" -> "Filter"
"Find by name..." -> "Filer by name..." placeholder for the filter text field
Capitalizing the type labels in the toggle buttons
Replacing "model" with "processor" in the toggle labels
> improve the UI of the catalog header

- packages/ui/src/models/visualization/flows/support/node-definition.service.test.ts
- packages/ui/src/models/visualization/flows/support/node-definition.service.ts
> fix: Add String array handling for component parameter

- packages/ui/src/components/Form/CustomAutoField.tsx
- packages/ui/src/components/Form/CustomAutoForm.tsx
- packages/ui/src/components/Form/properties/PropertiesField.tsx
- packages/ui/src/components/Form/properties/PropertyRow.scss
- packages/ui/src/components/Form/properties/PropertyRow.tsx
- packages/ui/src/components/MetadataEditor/MetadataEditor.tsx
| --- | --- |
| ![image](https://github.com/KaotoIO/kaoto-next/assets/16512618/399d00aa-7e86-47ee-914c-f8014f3a6f93) | ![image](https://github.com/KaotoIO/kaoto-next/assets/16512618/cd6c2eb3-54e7-4811-9233-59394c114921) |
> chore(metadata): Styling improvements for MetadataEditor

- packages/ui/src/components/Visualization/Canvas/CanvasSideBar.tsx
> fix: Error "Something didn't work as expected" sticks

- packages/ui/src/components/Visualization/ContextToolbar/FlowType/FlowTypeSelector.tsx
- packages/ui/src/components/Visualization/ContextToolbar/FlowType/NewFlow.tsx
> improving the NEW menu on the canvas

- packages/ui/src/components/InlineEdit/routeIdValidator.test.ts
- packages/ui/src/components/InlineEdit/routeIdValidator.ts
- packages/ui/src/components/Visualization/ContextToolbar/Flows/FlowsList.tsx
fixes https://github.com/KaotoIO/kaoto-next/issues/513
> fix - add route ID format and duplicity validation

- packages/ui/src/components/Form/CustomAutoField.tsx
- packages/ui/src/components/Form/bean/BeanReferenceField.test.tsx
- packages/ui/src/components/Form/bean/BeanReferenceField.tsx
- packages/ui/src/components/Form/bean/NewBeanModal.test.tsx
- packages/ui/src/components/Form/bean/NewBeanModal.tsx
Fixes: #470
https://github.com/KaotoIO/kaoto-next/assets/265462/af604413-305e-42ab-ba4d-b575f0e7462f
> feat: Add BeanReferenceField

- packages/ui-tests/cypress/e2e/codeEditor/malformedFlows.cy.ts
- packages/ui-tests/cypress/fixtures/flows/malformed/missingIdRoute.yaml
- packages/ui-tests/cypress/fixtures/flows/malformed/missingKindKamelet.yaml
- packages/ui-tests/cypress/fixtures/flows/malformed/unknownNode.yaml
- packages/ui-tests/cypress/fixtures/flows/malformed/wrongIndentPropertiesKamelet.yaml
- packages/ui-tests/cypress/fixtures/flows/malformed/wrongIndentSourceKamelet.yaml
- packages/ui-tests/cypress/support/cypress.d.ts
- packages/ui-tests/cypress/support/next-commands/sourceCode.ts
resolves https://github.com/KaotoIO/kaoto-next/issues/555
> e2e - erroneous input yaml resiliency coverage

- packages/ui-tests/cypress/e2e/designer/routeBeanConf.cy.ts
- packages/ui/src/components/Form/bean/BeanReferenceField.test.tsx
- packages/ui/src/components/Form/bean/BeanReferenceField.tsx
fixes https://github.com/KaotoIO/kaoto-next/issues/559
https://github.com/KaotoIO/kaoto-next/assets/4180208/2ad6d16c-53f1-47d8-8da4-a68233ffbcdd
> fix(559) - Removing the bean reference name should be persisted

- packages/ui/src/components/Visualization/Canvas/CanvasSideBar.tsx
small fix - relates to merged PR - https://github.com/KaotoIO/kaoto-next/pull/556
> fix - prevent images from have class sidebar-icon-undefined

- packages/ui/src/models/camel/camel-k-resource.ts
- packages/ui/src/models/camel/pipe-resource.ts
- packages/ui/src/pages/Metadata/MetadataPage.tsx
fixes https://github.com/KaotoIO/kaoto-next/issues/593
the visual entity needs to be updated to reflect the change in the metadata
https://github.com/KaotoIO/kaoto-next/assets/4180208/e2eb8247-1829-4b0f-9125-7137b249c650
> fix(593): metadata editor change visual metadata in canvas

- .github/workflows/deploy-main.yml
Please provide a brief summary of your changes along with a link to the related issue if applicable.
Provide information about the testing procedures, types of tests, and tools used to ensure the functionality and correctness of the changes.
> Fix workflow to publish github pages and docker images #597

- Dockerfile
Please provide a brief summary of your changes along with a link to the related issue if applicable.
Provide information about the testing procedures, types of tests, and tools used to ensure the functionality and correctness of the changes.
> Switch container image from nginxinc/nginx-unprivileged to registry.access.redhat.com/ubi8/nginx-122

- packages/ui/src/components/Form/CustomAutoField.test.tsx
- packages/ui/src/components/Form/CustomAutoField.tsx
- packages/ui/src/components/Form/customField/BoolField.tsx
fixes https://github.com/KaotoIO/kaoto-next/issues/607
https://github.com/KaotoIO/kaoto-next/assets/4180208/c8216576-ef4c-467f-ae47-474da9e6890d
> fix(607) Add custom BoolField component with help icon

- packages/ui/src/models/camel/__snapshots__/camel-resource.test.ts.snap
- packages/ui/src/models/camel/__snapshots__/kamelet-resource.test.ts.snap
- packages/ui/src/models/camel/kamelet-resource.test.ts
- packages/ui/src/models/camel/kamelet-resource.ts
- packages/ui/src/models/camel/pipe-resource.ts
- packages/ui/src/models/visualization/flows/abstract-camel-visual-entity.ts
- packages/ui/src/models/visualization/flows/camel-route-visual-entity.ts
- packages/ui/src/models/visualization/flows/index.ts
- packages/ui/src/models/visualization/flows/kamelet-visual-entity.ts
fixes https://github.com/KaotoIO/kaoto-next/issues/605 and also https://github.com/KaotoIO/kaoto-next/issues/596
> fix(605) - add metadata handling for kamelet resource

- README.md
info related to running the docker image locally for reference and visibility
> Add info regarding the docker image to README

- packages/camel-catalog/kaoto-camel-catalog-maven-plugin/src/main/java/io/kaoto/camelcatalog/CamelCatalogProcessor.java
- packages/camel-catalog/kaoto-camel-catalog-maven-plugin/src/main/java/io/kaoto/camelcatalog/CamelYamlDslSchemaProcessor.java
- packages/camel-catalog/kaoto-camel-catalog-maven-plugin/src/test/java/io/kaoto/camelcatalog/CamelCatalogProcessorTest.java
- packages/camel-catalog/kaoto-camel-catalog-maven-plugin/src/test/java/io/kaoto/camelcatalog/CamelYamlDslSchemaProcessorTest.java
- packages/ui/src/components/Visualization/Canvas/CanvasForm.tsx
- packages/ui/src/components/Visualization/Canvas/LoadBalancerEditor.test.tsx
- packages/ui/src/components/Visualization/Canvas/LoadBalancerEditor.tsx
- packages/ui/src/components/Visualization/Canvas/loadbalancer.service.test.ts
- packages/ui/src/components/Visualization/Canvas/loadbalancer.service.ts
- packages/ui/src/models/camel-catalog-index.ts
- packages/ui/src/models/camel-loadbalancers-catalog.ts
- packages/ui/src/models/catalog-kind.ts
- packages/ui/src/models/index.ts
- packages/ui/src/models/visualization/flows/camel-catalog.service.ts
- packages/ui/src/providers/catalog.provider.tsx
Fixes: #520
https://github.com/KaotoIO/kaoto-next/assets/265462/68c2ed5b-dead-4073-b13f-1a5198d6bb8c
> feat: Create LoadBalancerEditor component

- packages/ui/src/providers/catalog-modal.provider.tsx
fixes https://github.com/KaotoIO/kaoto-next/issues/638
https://github.com/KaotoIO/kaoto-next/assets/4180208/14f0d220-5d3d-4485-9541-4c2103134b90
> fix(638): make canvas modal top alligned

- packages/ui-tests/cypress/e2e/codeEditor/sourceCodeActions.cy.ts
- packages/ui-tests/cypress/e2e/designer/uriRouteConfig.cy.ts
- packages/ui-tests/cypress/fixtures/flows/UriConfRoute.yaml
e2e coverage for URI based node config - https://github.com/KaotoIO/kaoto-next/issues/274
> e2e: add uri node config coverage

- .github/workflows/publish-npm-package.yml
Change the release and publish workflow to be triggered by a published GitHub release
> chore(publish): Update publish workflow

- Dockerfile
- nginx/nginx.conf
Please provide a brief summary of your changes along with a link to the related issue if applicable.
Provide information about the testing procedures, types of tests, and tools used to ensure the functionality and correctness of the changes.
> chore(container-image): disable ipv6 and index,html caching

- packages/ui/src/models/visualization/flows/templates/pipe.ts
related to https://github.com/KaotoIO/kaoto-next/issues/653
> fix pipe.ts with - move properties to right place

- packages/ui-tests/cypress/support/next-commands/design.ts
fix failing  e2e for https://github.com/KaotoIO/kaoto-next/pull/692
> fix e2e routeBeanConf.cy.ts instability

- packages/ui/src/components/Visualization/Canvas/CanvasForm.scss
- packages/ui/src/components/Visualization/Canvas/CanvasSideBar.scss
Before:
https://github.com/KaotoIO/kaoto-next/assets/73224329/c92c1ff9-6096-4769-92bc-1b104d13f635
After:
https://github.com/KaotoIO/kaoto-next/assets/73224329/392daaa8-841d-442a-bff5-ed3b2d1f9993
> fix: Fix for Canvas Side Bar scrolling

- packages/camel-catalog/kaoto-camel-catalog-maven-plugin/src/main/java/io/kaoto/camelcatalog/CamelCatalogProcessor.java
- packages/camel-catalog/kaoto-camel-catalog-maven-plugin/src/test/java/io/kaoto/camelcatalog/CamelCatalogProcessorTest.java
> fix: Duplicated enum members in Route propertySchema

- .github/workflows/release-pipeline.yml
> Fix Release Pipeline and container image stage

- packages/ui/package.json
- yarn.lock
| --- | --- |
| ![image](https://github.com/KaotoIO/kaoto-next/assets/16512618/cf35671e-d159-4b44-a34f-62db08a9c2a9) | ![image](https://github.com/KaotoIO/kaoto-next/assets/16512618/24870510-2150-4c5a-ba5f-ba30b6fd0dcd) |
> chore(deps): Update @kaoto-next/uniforms-patternfly dependency

- packages/ui/src/components/Form/customField/TypeaheadField.test.tsx
- packages/ui/src/components/PropertiesModal/PropertiesModal.tsx
- packages/ui/src/models/visualization/flows/abstract-camel-visual-entity.test.ts
- packages/ui/src/models/visualization/flows/camel-route-visual-entity.ts
- packages/ui/src/models/visualization/flows/support/kamelet-schema.service.test.ts
- packages/ui/src/models/visualization/flows/support/validators/model-validation.service.test.ts
Replace relative imports with the dedicated token
> chore(imports): Fix relative imports

- packages/camel-catalog/assembly/pom.xml
- packages/camel-catalog/assembly/src/main/resources/schemas/KameletConfiguration.json
Fixes #793 
Fixes #782 Partially
> feat: Added Kamelet configuration schema

- packages/ui/src/multiplying-architecture/KaotoEditor.scss
based on https://github.com/KaotoIO/kaoto-next/pull/820
relates to https://github.com/KaotoIO/kaoto-next/pull/817#issuecomment-1935592122
> 465 provide padding back for other tab than canvas

- packages/ui/src/components/Form/expression/ExpressionField.tsx
- packages/ui/src/components/Form/expression/ExpressionModalLauncher.tsx
- packages/ui/src/components/Form/stepExpression/StepExpressionEditor.tsx
fixes https://github.com/KaotoIO/kaoto-next/issues/765
> fix(765) - remove redundant parameter label for property expression

- packages/ui-tests/cypress/e2e/designer/rootContainersConf.cy.ts
- packages/ui-tests/cypress/fixtures/flows/CamelRoute.yaml
e2e tests for root container configuration for Camel Routes
> e2e(768) - root container configuration for CR

- packages/camel-catalog/kaoto-camel-catalog-maven-plugin/src/main/java/io/kaoto/camelcatalog/KaotoCamelCatalogMojo.java
> fix: syntax fix

- packages/ui/src/components/Form/bean/NewBeanModal.tsx
- packages/ui/src/components/Form/expression/ExpressionModalLauncher.tsx
- packages/ui/src/components/Visualization/ContextToolbar/FlowType/NewFlow.tsx
- packages/ui/src/providers/catalog-modal.provider.tsx
Changed the Modal size to large for the following Modal's - New BeanModal, ExpressionModalLauncher, NewFlow, catalog-modal.provider
fixes: #891
> Changed the modal varient to large

- packages/ui/src/components/Form/expression/ExpressionEditor.test.tsx
add missing test for https://github.com/KaotoIO/kaoto-next/pull/898
> add missing jest test for the clear in expression editor

- packages/ui-tests/cypress/e2e/codeEditor/multiFlowEditor.cy.ts
- packages/ui-tests/cypress/e2e/codeEditor/sourceCodeActions.cy.ts
- packages/ui-tests/cypress/support/cypress.d.ts
- packages/ui-tests/cypress/support/next-commands/sourceCode.ts
coverage for source undo/redo - [fix](https://github.com/patternfly/patternfly-react/issues/9838) was already included in our source
> e2e - add undo and redo coverage, was fixed in upstream

- packages/camel-catalog/kaoto-camel-catalog-maven-plugin/src/main/java/io/kaoto/camelcatalog/CamelYamlDslSchemaProcessor.java
- packages/camel-catalog/kaoto-camel-catalog-maven-plugin/src/main/java/io/kaoto/camelcatalog/KaotoCamelCatalogMojo.java
@igarashitm please can you check if we can really remove these parts now that we are on Camel 4.4 ?
> Remove warnings

- packages/ui/src/components/Form/dataFormat/DataFormatEditor.test.tsx
- packages/ui/src/components/Visualization/Canvas/Canvas.test.tsx
- packages/ui/src/components/Visualization/Canvas/CanvasForm.test.tsx
clean useless logs, which make jest test logs unreadable
> jest - clean up noise from test logs

- packages/ui/src/models/camel/camel-route-resource.test.ts
- packages/ui/src/models/visualization/flows/camel-route-visual-entity.test.ts
- packages/ui/src/models/visualization/flows/camel-route-visual-entity.ts
> fix: Rendering incomplete routes using from as top-level element 

- packages/camel-catalog/kaoto-camel-catalog-maven-plugin/src/main/java/io/kaoto/camelcatalog/CamelCatalogProcessor.java
Currently, entity properties are written in alphabetical order.
This commit, use the Camel Catalog to write the properties using its order in the `entities.json` file.
> feat(entities): Sort entity properties using the Camel Catalog

- packages/ui/src/models/camel/kamelet-resource.ts
- packages/ui/src/models/visualization/flows/kamelet-visual-entity.test.ts
- packages/ui/src/models/visualization/flows/kamelet-visual-entity.ts
Fixes #902 partially!
Note: This PR doesn't fix any bug listed in #902 but It lays the foundation for it!
> Fix_902: Name issues with Kamelet and Routes

- packages/ui/src/models/visualization/flows/camel-rest-configuration-visual-entity.test.ts
relates to [969](https://github.com/KaotoIO/kaoto-next/issues/969#issuecomment-2012567296)
> enabe RestConfigurationVisualEntity tests

- packages/ui-tests/stories/canvas/CanvasSideBar.stories.tsx
- packages/ui/src/components/Visualization/Canvas/CanvasForm.test.tsx
- packages/ui/src/components/Visualization/Canvas/CanvasForm.tsx
- packages/ui/src/components/Visualization/Canvas/__snapshots__/CanvasForm.test.tsx.snap
- packages/ui/src/components/Visualization/ContextToolbar/Flows/FlowsList.test.tsx
- packages/ui/src/components/Visualization/ContextToolbar/Flows/FlowsList.tsx
- packages/ui/src/models/visualization/flows/abstract-camel-visual-entity.ts
- packages/ui/src/models/visualization/flows/kamelet-visual-entity.ts
- packages/ui/src/models/visualization/flows/support/flows-visibility.test.ts
- packages/ui/src/models/visualization/flows/support/flows-visibility.ts
This PR is meant to fix #902 completely!
> fix(902): Route and Kamelet container name issue

- .github/workflows/release-pipeline.yml
- package.json
- packages/camel-catalog/package.json
- packages/ui-tests/package.json
- packages/ui/package.json
Release 2.0.0-TP3.1, this will be the first `@kaoto/kaoto` release
> chore(release): 2.0.0-TP3.1

- packages/ui/src/models/visualization/flows/support/camel-component-default.service.test.ts
- packages/ui/src/models/visualization/flows/support/camel-component-default.service.ts
Fixes: #867
Start with setHeader, setProperty, setVariable, setBody and filter
> fix: Use Simple as default selection for expression

- package.json
- packages/camel-catalog/package.json
- packages/ui-tests/package.json
- packages/ui/package.json
> chore(release): 2.0.0-RC1

- packages/camel-catalog/kaoto-camel-catalog-maven-plugin/pom.xml
- packages/camel-catalog/src/json-schema-to-typescript.mts
- packages/ui/src/models/camel-catalog-index.ts
- packages/ui/src/utils/catalog-schema-loader.test.ts
- packages/ui/src/utils/catalog-schema-loader.ts
fix: https://github.com/KaotoIO/kaoto/issues/5
> chore(CamelCatalog): Add Catalog index typings

- packages/ui/src/components/Visualization/ContextToolbar/Flows/FlowsMenu.scss
- packages/ui/src/components/Visualization/ContextToolbar/Flows/FlowsMenu.test.tsx
- packages/ui/src/components/Visualization/ContextToolbar/Flows/FlowsMenu.tsx
- packages/ui/src/components/Visualization/Custom/CustomGroup.tsx
- packages/ui/src/components/Visualization/Custom/CustomNode.tsx
- packages/ui/src/utils/truncate-label.tsx
Fixes #789
The changes can be test here: https://shivamg640.github.io/kaoto/
> fix: Limiting the length of Node/Group/FlowsId(FlowMenu) labels

- packages/ui/src/components/Form/CustomAutoField.tsx
fixes https://github.com/KaotoIO/kaoto/issues/1099
> fix(1099) - Use LongTextField for query fields

- packages/ui-tests/cypress/e2e/designer/specialCamelRoutes/rootOnException.cy.ts
- packages/ui-tests/cypress/e2e/designer/specialCamelRoutes/rootRestConfiguration.cy.ts
- packages/ui-tests/cypress/e2e/designer/specialStepConfiguration/expressionStepConfig.cy.ts
- packages/ui-tests/cypress/support/cypress.d.ts
- packages/ui-tests/cypress/support/next-commands/design.ts
e2e coverage for https://github.com/KaotoIO/kaoto/issues/562
> Add e2e coverage for Rest Configuration

- packages/ui-tests/cypress/e2e/designer/rootContainerConfig/rootContainersConf.cy.ts
- packages/ui-tests/cypress/fixtures/flows/pipe/basic.yaml
- packages/ui-tests/cypress/support/next-commands/metadata.ts
e2e for https://github.com/KaotoIO/kaoto/issues/974 and https://github.com/KaotoIO/kaoto/issues/1031
> Add pipe root container and delete group e2e coverage

- packages/ui/src/utils/node-icon-resolver.ts
fixes https://github.com/KaotoIO/kaoto/issues/1139
> add default icon for the Kamelet root container instead of question mark

- packages/ui-tests/stories/canvas/Aggregate.stories.tsx
- packages/ui-tests/stories/canvas/CanvasSideBar.stories.tsx
- packages/ui-tests/stories/catalog/PropertiesModal.stories.tsx
- packages/ui/src/models/visualization/index.ts
fixes https://github.com/KaotoIO/kaoto/issues/862
> Add aggregate EIP story to storybook

- packages/ui-tests/cypress/e2e/designer/settings/aboutPage.cy.ts
- packages/ui-tests/cypress/e2e/designer/specialStepConfiguration/expressionStepConfig.cy.ts
- packages/ui-tests/cypress/support/cypress.d.ts
- packages/ui-tests/cypress/support/next-commands/default.ts
e2e coverage for about modal and enabling previously skipped expression step test, after fix for https://github.com/KaotoIO/kaoto/issues/904
> e2e - about modal and expression step config

- packages/ui-tests/cypress/e2e/componentCatalog.cy.ts
- packages/ui/src/components/Catalog/CatalogFilter.tsx
fixes https://github.com/KaotoIO/kaoto/issues/1075
https://github.com/KaotoIO/kaoto/assets/4180208/ab2d90cd-bfca-4c90-96f5-15d0fa16a2da
> fix(1075): hover on Layout buttons of catalog modal

- packages/ui-tests/cypress/support/next-commands/design.ts
- packages/ui/src/components/Form/CustomAutoFields.tsx
- packages/ui/src/components/Form/customField/CustomExpandableSection.tsx
- packages/ui/src/components/Form/customField/CustomNestField.tsx
- packages/ui/src/components/Visualization/Canvas/CanvasForm.scss
- packages/ui/src/components/Visualization/Canvas/CanvasForm.tsx
- packages/ui/src/components/Visualization/Canvas/CanvasSideBar.tsx
- packages/ui/src/components/Visualization/Canvas/__snapshots__/CanvasForm.test.tsx.snap
- packages/ui/src/providers/filtered-field.provider.test.tsx
- packages/ui/src/providers/filtered-field.provider.tsx
- packages/ui/src/providers/index.ts
Added Filter parameters feature in the Canvas Form. Fixes #701 
Check here: https://shivamg640.github.io/kaoto/
> feat(form): Filter parameters in the Canvas Form

- packages/ui/src/multiplying-architecture/KaotoBridge.tsx
Relates to: https://github.com/KaotoIO/kaoto/pull/1211#issuecomment-2195024703
> fix(vscode): Add missing ReloadProvider

- packages/ui/src/components/Visualization/Canvas/__snapshots__/Canvas.test.tsx.snap
- packages/ui/src/components/Visualization/Canvas/canvas.service.test.ts
- packages/ui/src/components/Visualization/Canvas/canvas.service.ts
This PR removes animation form the edges.
> fix(canvas): Remove animation from edges

- packages/ui/src/models/settings/localstorage-settings-adapter.test.ts
- packages/ui/src/models/settings/settings.model.ts
- packages/ui/src/models/visualization/base-visual-entity.ts
- packages/ui/src/models/visualization/flows/abstract-camel-visual-entity.ts
- packages/ui/src/models/visualization/flows/camel-route-visual-entity.test.ts
- packages/ui/src/models/visualization/flows/support/camel-component-schema.service.test.ts
- packages/ui/src/models/visualization/flows/support/camel-component-schema.service.ts
- packages/ui/src/models/visualization/visualization-node.test.ts
- packages/ui/src/models/visualization/visualization-node.ts
relates: https://issues.redhat.com/browse/KTO-441
follow up: https://github.com/KaotoIO/kaoto/pull/1221
> chore(Canvas): Use `enum` for NodeLabel setting

- packages/catalog-generator/pom.xml
- packages/catalog-generator/src/main/java/io/kaoto/camelcatalog/Main.java
- packages/catalog-generator/src/main/java/io/kaoto/camelcatalog/commands/GenerateCommandOptions.java
- packages/catalog-generator/src/test/java/io/kaoto/camelcatalog/MainTest.java
- packages/catalog-generator/src/test/java/io/kaoto/camelcatalog/commands/GenerateCommandOptionsTest.java
The first batch for @kaoto/camel-catalog tests
fix: https://github.com/KaotoIO/kaoto/issues/1250
> chore(test): Add tests for @kaoto/camel-catalog

- packages/ui/src/components/Visualization/ContextToolbar/ContextToolbar.scss
- packages/ui/src/components/Visualization/ContextToolbar/ContextToolbar.tsx
- packages/ui/src/components/Visualization/ContextToolbar/Flows/FlowsMenu.scss
- packages/ui/src/components/Visualization/ContextToolbar/Flows/FlowsMenu.tsx
fixes https://github.com/KaotoIO/kaoto/issues/1297
Toolbar menu wrapping:
https://github.com/user-attachments/assets/fd8b7c5b-a24b-4aba-9919-62d3e9667d65
> fix(1297): toolbar menu wrapping in small window

- packages/ui-tests/stories/navigation/Navigation.stories.tsx
- packages/ui/src/layout/Navigation.test.tsx
- packages/ui/src/layout/Navigation.tsx
- packages/ui/src/layout/Shell.scss
- packages/ui/src/layout/__snapshots__/Navigation.test.tsx.snap
- packages/ui/src/layout/navigation.models.ts
- packages/ui/src/testing-api.ts
fix: https://github.com/KaotoIO/kaoto/issues/1444
> fix(Navigation): Remove items unrelated to current schema

- .github/workflows/build-lint-test.yml
- packages/ui/package.json
- packages/ui/vite.config.js
- yarn.lock
> fix(codecov): Report for base commits

- .github/workflows/build-lint-test.yml
- packages/ui/package.json
- packages/ui/vite.config.js
- yarn.lock
The issue seems to be that commits are published to a fork instead of the main repository
Reverts KaotoIO/kaoto#1521
> Revert "fix(codecov): Report for base commits"

- packages/catalog-generator/src/main/java/io/kaoto/camelcatalog/generator/CatalogGenerator.java
fix(https://github.com/KaotoIO/kaoto/issues/1472)
> fix(1472): sort kamelets alphabetically in the catalog

- packages/ui/src/models/visualization/flows/support/camel-component-default.service.test.ts
- packages/ui/src/models/visualization/flows/support/camel-component-default.service.ts
fixes https://github.com/KaotoIO/kaoto/issues/1541
> fix(1541): Provide a template for removeHeaders EIP

- packages/ui/package.json
- yarn.lock
This version reverts the change about inserting the array elements at the beginning of the array (https://github.com/KaotoIO/kaoto/issues/1102) but brings other fixes:
* fix: https://github.com/KaotoIO/kaoto/issues/1438
* fix: https://github.com/KaotoIO/kaoto/issues/1439
> chore(ConfigForm): Update uniforms-patternfly

- packages/ui/src/components/Visualization/ContextToolbar/DSLSelector/DSLSelectorToggle/DSLSelectorToggle.test.tsx
fixes https://github.com/KaotoIO/kaoto/issues/1623
> fix(1623): Unexpected logs for DSLSelectorToggle.test.tsx

- packages/ui/src/components/Visualization/Custom/Group/CustomGroupExpanded.tsx
fix: https://github.com/KaotoIO/kaoto/issues/1631
> fix(Canvas): Increase hoverOut timing for Groups

- packages/ui/src/components/Form/customField/PasswordField.tsx
fixes https://github.com/KaotoIO/kaoto/issues/1627
> fix(1627): Unexpected logs for PasswordField.test.tsx

- packages/catalog-generator/scripts/build-catalogs.mjs
> adding the latest RH provided Camel Quarkus to the catalog (3.15.0.redhat-00007)

- packages/catalog-generator/scripts/build-catalogs.mjs
> Align Camel Quarkus catalog 3.8.x (3.8.4) to 4.8.4

- packages/catalog-generator/scripts/build-catalogs.mjs
> Upgrade Camel Main and Spring Boot catalog from 4.8.1 to 4.8.2

- packages/ui/src/components/Visualization/Custom/hooks/delete-step.hook.tsx
- packages/ui/src/components/Visualization/Custom/hooks/replace-step.hook.tsx
> Fix: Deleting the empty container node with placeholder node asks for confirmation

- packages/ui/src/assets/settingsSchema.json
Detected in: https://github.com/KaotoIO/vscode-kaoto/pull/756
> fix(settings): Fix typo

- packages/ui/src/components/Visualization/ContextToolbar/DSLSelector/DSLSelectorToggle/DSLSelectorToggle.tsx
- packages/ui/src/components/Visualization/ContextToolbar/Flows/FlowsMenu.tsx
- packages/ui/src/components/Visualization/ContextToolbar/NewEntity/NewEntity.scss
- packages/ui/src/components/Visualization/ContextToolbar/NewEntity/NewEntity.tsx
- packages/ui/src/components/Visualization/EmptyState/FlowType/FlowTypeSelector.tsx
fix: https://github.com/KaotoIO/kaoto/issues/1947
fix: https://github.com/KaotoIO/kaoto/issues/1964
fix: https://github.com/KaotoIO/kaoto/issues/1943
> fix: Post patternfly v6 update

- packages/ui/src/components/Visualization/Canvas/FormV2/fields/AnyOfField.tsx
- packages/ui/src/components/Visualization/Canvas/FormV2/fields/EnumField.tsx
- packages/ui/src/components/Visualization/Canvas/FormV2/fields/ObjectField/ObjectField.tsx
- packages/ui/src/components/Visualization/Canvas/FormV2/fields/ObjectField/ObjectFieldGrouping.tsx
- packages/ui/src/components/Visualization/Canvas/FormV2/fields/ObjectField/ObjectFieldInner.tsx
- packages/ui/src/stubs/timer.component.schema.ts
- packages/ui/src/utils/camel-case-to-space.ts
- packages/ui/src/utils/capitalize-string.test.ts
- packages/ui/src/utils/capitalize-string.ts
- packages/ui/src/utils/get-field-groups.test.ts
- packages/ui/src/utils/get-field-groups.ts
- packages/ui/src/utils/get-tagged-field-from-string.test.ts
- packages/ui/src/utils/get-tagged-field-from-string.ts
> feat(Form): Add property filtering and grouping

- packages/ui/src/components/Visualization/Canvas/FormV2/fields/PropertiesField/KeyValue.tsx
- packages/ui/src/components/Visualization/Canvas/FormV2/fields/PropertiesField/PropertiesField.tsx
- packages/ui/src/components/Visualization/Canvas/FormV2/providers/FormComponentFactoryProvider.test.tsx
- packages/ui/src/components/Visualization/Canvas/FormV2/providers/FormComponentFactoryProvider.tsx
> feat(Form): Add PropertiesField component

- packages/ui/src/components/Visualization/Canvas/FormV2/fields/TextAreaField.tsx
- packages/ui/src/components/Visualization/Canvas/FormV2/providers/FormComponentFactoryProvider.tsx
> feat(Form): Add TextAreaField

- packages/catalog-generator/src/main/java/io/kaoto/camelcatalog/generators/CamelCatalogSchemaEnhancer.java
- packages/catalog-generator/src/main/java/io/kaoto/camelcatalog/generators/CamelYAMLSchemaReader.java
- packages/catalog-generator/src/main/java/io/kaoto/camelcatalog/generators/ComponentGenerator.java
- packages/catalog-generator/src/main/java/io/kaoto/camelcatalog/generators/EIPGenerator.java
- packages/catalog-generator/src/test/java/io/kaoto/camelcatalog/generator/CamelCatalogProcessorTest.java
- packages/catalog-generator/src/test/java/io/kaoto/camelcatalog/generators/CamelCatalogSchemaEnhancerTest.java
- packages/catalog-generator/src/test/java/io/kaoto/camelcatalog/generators/CamelYAMLSchemaReaderTest.java
- packages/catalog-generator/src/test/java/io/kaoto/camelcatalog/generators/ComponentGeneratorTest.java
- packages/catalog-generator/src/test/java/io/kaoto/camelcatalog/generators/EIPGeneratorTest.java
> Fix(Catalog): Added Schema details to EIPS and Components

- packages/catalog-generator/src/main/java/io/kaoto/camelcatalog/generator/Util.java
- packages/catalog-generator/src/main/java/io/kaoto/camelcatalog/generators/CamelCatalogSchemaEnhancer.java
- packages/catalog-generator/src/main/java/io/kaoto/camelcatalog/generators/CamelYAMLSchemaReader.java
- packages/catalog-generator/src/main/java/io/kaoto/camelcatalog/generators/EIPGenerator.java
- packages/catalog-generator/src/main/java/io/kaoto/camelcatalog/generators/SchemaPropertyFilter.java
- packages/catalog-generator/src/test/java/io/kaoto/camelcatalog/generators/CamelYAMLSchemaReaderTest.java
- packages/catalog-generator/src/test/java/io/kaoto/camelcatalog/generators/EIPGeneratorTest.java
> Fix(Catalog): Added Rest Definitions to Patterns catalog

- packages/ui/src/models/visualization/flows/support/camel-component-schema.service.ts
> fix(Canvas): base canBeDisabled functionality in the Processor catalog

- packages/ui/src/camel-utils/camel-to-tile.adapter.test.ts
- packages/ui/src/camel-utils/camel-to-tile.adapter.ts
- packages/ui/src/components/PropertiesModal/PropertiesModal.tsx
- packages/ui/src/components/Visualization/Canvas/FormV2/fields/PropertiesField/PropertiesField.tsx
- packages/ui/src/models/visualization/flows/abstract-camel-visual-entity.ts
- packages/ui/src/models/visualization/flows/camel-error-handler-visual-entity.ts
- packages/ui/src/models/visualization/flows/camel-intercept-from-visual-entity.ts
- packages/ui/src/models/visualization/flows/camel-intercept-send-to-endpoint-visual-entity.ts
- packages/ui/src/models/visualization/flows/camel-intercept-visual-entity.ts
- packages/ui/src/models/visualization/flows/camel-on-completion-visual-entity.ts
- packages/ui/src/models/visualization/flows/camel-on-exception-visual-entity.ts
- packages/ui/src/models/visualization/flows/camel-rest-configuration-visual-entity.ts
- packages/ui/src/models/visualization/flows/camel-rest-visual-entity.ts
- packages/ui/src/models/visualization/flows/camel-route-configuration-visual-entity.ts
- packages/ui/src/models/visualization/flows/pipe-visual-entity.ts
- packages/ui/src/models/visualization/flows/support/camel-component-default.service.test.ts
- packages/ui/src/models/visualization/flows/support/camel-component-default.service.ts
- packages/ui/src/models/visualization/flows/support/camel-component-filter.service.ts
- packages/ui/src/providers/catalog-tiles.provider.test.tsx
- packages/ui/src/providers/catalog-tiles.provider.tsx
- packages/ui/src/utils/node-icon-resolver.ts
> chore(Canvas): Add routeConfiguration branches

- packages/ui/src/components/Visualization/Canvas/FormV2/fields/BeanField.tsx
- packages/ui/src/components/Visualization/Canvas/FormV2/providers/FormComponentFactoryProvider.tsx
- packages/ui/src/components/typeahead/Typeahead.tsx
- packages/ui/src/components/typeahead/Typeahead.types.tsx
Part of https://github.com/KaotoIO/kaoto/pull/1939
> feat(Form): support BeanField

- packages/ui/src/components/Form/NoFieldFound.tsx
- packages/ui/src/components/Visualization/Canvas/FormV2/KaotoForm.scss
- packages/ui/src/components/Visualization/Canvas/FormV2/KaotoForm.tsx
> Fix(CanvasForm): Render NoFieldFound when form is empty

- packages/ui/src/components/KeyValue/KeyValue.test.tsx
- packages/ui/src/components/KeyValue/KeyValue.tsx
- packages/ui/src/components/Visualization/Canvas/FormV2/KaotoForm.tsx
- packages/ui/src/components/Visualization/Canvas/FormV2/fields/ArrayField/ArrayField.test.tsx
- packages/ui/src/components/Visualization/Canvas/FormV2/fields/ArrayField/ArrayField.tsx
- packages/ui/src/components/Visualization/Canvas/FormV2/fields/ArrayField/ArrayFieldWrapper.test.tsx
- packages/ui/src/components/Visualization/Canvas/FormV2/fields/ArrayField/ArrayFieldWrapper.tsx
- packages/ui/src/components/Visualization/Canvas/FormV2/fields/BeanField.tsx
- packages/ui/src/components/Visualization/Canvas/FormV2/fields/EnumField.tsx
- packages/ui/src/components/Visualization/Canvas/FormV2/fields/ExpressionField/ExpressionFieldInner.tsx
- packages/ui/src/components/Visualization/Canvas/FormV2/fields/FieldWrapper.tsx
- packages/ui/src/components/Visualization/Canvas/FormV2/fields/ObjectField/ObjectField.tsx
- packages/ui/src/components/Visualization/Canvas/FormV2/fields/OneOfField/SchemaList.tsx
- packages/ui/src/components/Visualization/Canvas/FormV2/fields/PropertiesField/PropertiesField.tsx
- packages/ui/src/components/Visualization/Canvas/FormV2/testing/FieldTestProvider.tsx
This PR adds the first batch of unit tests for the new Kaoto form library
part of https://github.com/KaotoIO/kaoto/pull/1939
> chore(Tests): Add first batch of tests

- packages/ui/src/components/Visualization/Canvas/FormV2/fields/ArrayField/ArrayFieldWrapper.test.tsx
- packages/ui/src/components/Visualization/Canvas/FormV2/fields/AutoField.test.tsx
- packages/ui/src/components/Visualization/Canvas/FormV2/fields/AutoField.tsx
- packages/ui/src/components/Visualization/Canvas/FormV2/fields/ExpressionField/expression.service.test.ts
- packages/ui/src/components/Visualization/Canvas/FormV2/fields/FieldWrapper.test.tsx
- packages/ui/src/components/Visualization/Canvas/FormV2/fields/PasswordField.test.tsx
- packages/ui/src/components/Visualization/Canvas/FormV2/fields/PasswordField.tsx
- packages/ui/src/components/Visualization/Canvas/FormV2/fields/StringField.test.tsx
- packages/ui/src/components/Visualization/Canvas/FormV2/fields/StringField.tsx
- packages/ui/src/components/Visualization/Canvas/FormV2/fields/TextAreaField.test.tsx
- packages/ui/src/components/Visualization/Canvas/FormV2/fields/TextAreaField.tsx
- packages/ui/src/components/Visualization/Canvas/FormV2/fields/__snapshots__/AutoField.test.tsx.snap
- packages/ui/src/components/Visualization/Canvas/FormV2/fields/__snapshots__/DisabledField.test.tsx.snap
- packages/ui/src/components/Visualization/Canvas/FormV2/fields/__snapshots__/PasswordField.test.tsx.snap
- packages/ui/src/components/Visualization/Canvas/FormV2/fields/__snapshots__/StringField.test.tsx.snap
- packages/ui/src/components/Visualization/Canvas/FormV2/fields/__snapshots__/TextAreaField.test.tsx.snap
- packages/ui/src/components/Visualization/Canvas/FormV2/providers/FormComponentFactoryProvider.test.tsx
- packages/ui/src/components/Visualization/Canvas/FormV2/providers/ModelProvider.test.tsx
- packages/ui/src/components/Visualization/Canvas/FormV2/providers/SchemaDefinitionsProvider.test.tsx
- packages/ui/src/components/Visualization/Canvas/FormV2/providers/SchemaProvider.test.tsx
- packages/ui/src/hooks/schema-bridge.hook.test.tsx
- packages/ui/src/models/visualization/flows/nodes/root-node-mapper.test.ts
> chore(Tests): Add second batch of tests

- packages/catalog-generator/src/main/java/io/kaoto/camelcatalog/generators/CamelCatalogSchemaEnhancer.java
- packages/catalog-generator/src/test/java/io/kaoto/camelcatalog/generator/CamelCatalogProcessorTest.java
> Fix(Catalog): Bean format field needs type as string

- packages/ui/src/components/Visualization/Canvas/FormV2/fields/ExpressionField/ExpressionField.test.tsx
- packages/ui/src/components/Visualization/Canvas/FormV2/fields/ExpressionField/ExpressionField.tsx
- packages/ui/src/components/Visualization/Canvas/FormV2/fields/ExpressionField/__snapshots__/ExpressionField.test.tsx.snap
- packages/ui/src/stubs/expression-definition-schema.ts
> Fix: Set empty objects to undefined while updating the form model

- packages/ui/src/components/typeahead/Typeahead.tsx
> Fix: Typeahead Field related changes

- packages/ui/src/components/Visualization/Canvas/FormV2/fields/AutoField.test.tsx
- packages/ui/src/components/Visualization/Canvas/FormV2/fields/AutoField.tsx
- packages/ui/src/components/Visualization/Canvas/FormV2/fields/BeanField.test.tsx
- packages/ui/src/components/Visualization/Canvas/FormV2/fields/ObjectField/AnyOfField.test.tsx
- packages/ui/src/components/Visualization/Canvas/FormV2/fields/ObjectField/GroupFields.tsx
- packages/ui/src/components/Visualization/Canvas/FormV2/fields/ObjectField/ObjectField.tsx
- packages/ui/src/components/Visualization/Canvas/FormV2/fields/ObjectField/ObjectFieldGrouping.test.tsx
- packages/ui/src/components/Visualization/Canvas/FormV2/fields/ObjectField/ObjectFieldGrouping.tsx
- packages/ui/src/components/Visualization/Canvas/FormV2/fields/ObjectField/ObjectFieldInner.test.tsx
- packages/ui/src/components/Visualization/Canvas/FormV2/fields/ObjectField/ObjectFieldInner.tsx
- packages/ui/src/components/Visualization/Canvas/FormV2/fields/ObjectField/__snapshots__/AnyOfField.test.tsx.snap
- packages/ui/src/components/Visualization/Canvas/FormV2/fields/ObjectField/__snapshots__/ObjectFieldInner.test.tsx.snap
- packages/ui/src/components/Visualization/Canvas/FormV2/fields/PasswordField.test.tsx
- packages/ui/src/components/Visualization/Canvas/FormV2/fields/StringField.test.tsx
- packages/ui/src/components/Visualization/Canvas/FormV2/fields/TextAreaField.test.tsx
Show nested required fields from non-required array parent
| --- | --- |
| ![image](https://github.com/user-attachments/assets/42a09fa9-aba1-42ae-bd0b-9152f099e18e) | ![image](https://github.com/user-attachments/assets/639cc050-e559-4713-a02c-ce35e3c2b82b) |
part of #1939
> fix(Form): Show required fields from non-required parent array

- packages/ui/src/components/Visualization/Canvas/FormV2/providers/FormComponentFactoryProvider.test.tsx
- packages/ui/src/components/Visualization/Canvas/FormV2/providers/FormComponentFactoryProvider.tsx
part of #1939 
relates: https://github.com/KaotoIO/kaoto/issues/2028
> feat(Form): Use TextAreaField for Script property

- packages/ui-tests/cypress/e2e/designer/catalogs/userSpecifiedCatalog.cy.ts
- packages/ui-tests/cypress/e2e/designer/settings/switchDescriptionId.cy.ts
- packages/ui-tests/cypress/support/cypress.d.ts
- packages/ui-tests/cypress/support/next-commands/metadata.ts
- packages/ui/src/components/Settings/SettingsForm.tsx
- packages/ui/src/components/Settings/__snapshots__/SettingsForm.test.tsx.snap
- packages/ui/src/components/Visualization/Canvas/Form/CanvasFormBody.tsx
- packages/ui/src/components/Visualization/Canvas/Form/Tests/FormTest.tsx
- packages/ui/src/components/Visualization/Canvas/FormV2/KaotoForm.tsx
- packages/ui/src/components/Visualization/Canvas/FormV2/testing/FieldTestProvider.tsx
> chore(Form): Use KaotoForm in Settings

- packages/ui-tests/stories/canvas/Aggregate.stories.tsx
- packages/ui-tests/stories/canvas/CanvasSideBar.stories.tsx
part of https://github.com/KaotoIO/kaoto/pull/1939
> chore(Form): update aggregate story

- packages/ui-tests/stories/canvas/Marshal.stories.tsx
- packages/ui-tests/stories/canvas/Resequence.stories.tsx
- packages/ui-tests/stories/canvas/Saga.stories.tsx
- packages/ui-tests/stories/canvas/SetHeader.stories.tsx
- packages/ui-tests/stories/canvas/Tokenizer.stories.tsx
part of https://github.com/KaotoIO/kaoto/pull/1939
> feat(Form): add storybook stories for complex fields

- README.md
- devfile.yaml
- packages/ui/vite.config.js
added devfile.yaml to project
How to test? (OpenShift DevSpaces)
[![Open](https://img.shields.io/static/v1?label=Open%20in&message=Developer%20Sandbox&logo=eclipseche&color=FDB940&labelColor=525C86)](https://workspaces.openshift.com/#https://github.com/maximilianoPizarro/kaoto/tree/feature/devfile?storageType=ephemeral)
From your Workspaces started, run the tasks from devfile, confirm the port to expose and open in browser:
optional: podman mode
Only run "tasks start-with-docker"
> feature/devfile add devfile.yaml for OpenShift DevSpaces

- packages/catalog-generator/src/main/java/io/kaoto/camelcatalog/generator/CamelCatalogProcessor.java
- packages/catalog-generator/src/main/java/io/kaoto/camelcatalog/generators/EntityGenerator.java
- packages/catalog-generator/src/main/java/io/kaoto/camelcatalog/generators/K8sSchemaReader.java
- packages/catalog-generator/src/test/java/io/kaoto/camelcatalog/generator/CamelCatalogProcessorTest.java
- packages/catalog-generator/src/test/java/io/kaoto/camelcatalog/generators/EntityGeneratorTest.java
- packages/catalog-generator/src/test/resources/kubernetes-api-v1-openapi.json
- packages/ui/src/pages/Metadata/MetadataPage.tsx
- packages/ui/src/pages/PipeErrorHandler/PipeErrorHandlerPage.tsx
Fixes #2072 partially
Changes in this PR only moves the ObjectMeta and PipeErrorHandler to Entities-catalog.
Later we need to remove the Schema store related code from the project.
> Fix(Catalog): Removing Schema store dependency

- packages/ui-tests/cypress/e2e/designer/settings/aboutPage.cy.ts
- packages/ui/src/components/About/About.tsx
- packages/ui/src/global.d.ts
- packages/ui/src/layout/KaotoAboutModal.tsx
- packages/ui/src/multiplying-architecture/KaotoEditor.tsx
- packages/ui/src/multiplying-architecture/KaotoEditorRouter.tsx
- packages/ui/src/pages/About/AboutPage.scss
- packages/ui/src/pages/About/AboutPage.tsx
- packages/ui/src/pages/About/index.ts
- packages/ui/src/pages/About/router-exports.tsx
- packages/ui/src/router/links.models.ts
- packages/ui/vite.config.js
fixes https://github.com/KaotoIO/kaoto/issues/997
Screenshot of the new tab in VSCode:
requires: https://github.com/KaotoIO/vscode-kaoto/pull/829
> fix(997): About tab in Kaoto Editor

- packages/ui/src/components/Visualization/ContextToolbar/Flows/FlowsList.tsx
fix https://github.com/KaotoIO/kaoto/issues/1946
> fix(1946): Delete title in route dropdown menu is cropped

- packages/ui/src/components/Visualization/Canvas/FormV2/fields/BeanField.test.tsx
- packages/ui/src/components/Visualization/ContextToolbar/ExportDocument/ExportDocumentPreviewModal.tsx
- packages/ui/src/services/documentation.service.test.ts
- packages/ui/src/services/documentation.service.ts
> fix: Retrieve entities from CamelResource but not from EntitiesContext.entities

- packages/ui-tests/cypress/e2e/designer/routeDocumentation/exportRouteDocumentation.cy.ts
e2e reproducer for https://github.com/KaotoIO/kaoto/issues/2093
> e2e: reproducer for issue #2093

- packages/ui/src/components/Visualization/Canvas/FormV2/fields/ExpressionField/expression.service.ts
- packages/ui/src/models/visualization/flows/support/validators/model-validation.service.test.ts
- packages/ui/src/models/visualization/flows/support/validators/model-validation.service.ts
> Fix(Canvas): Configure warning validations to use parsed expressions model

- packages/ui/src/components/View/SourceTargetView.tsx
> fix(DataMapper): Move state update to useEffect()

- packages/ui/src/components/Visualization/ContextToolbar/Flows/FlowsList.scss
- packages/ui/src/components/Visualization/ContextToolbar/Flows/FlowsList.tsx
fix: #2140 
https://github.com/user-attachments/assets/982ff01f-8c24-4474-95a6-da5f1987dc12
> fix(FlowsList): set overflow to scrollbars to appear in the FlowsList

- packages/ui-tests/cypress/fixtures/metadata/errorHandlerSchema.json
- packages/ui-tests/stories/kaotoForm/Metadata.stories.tsx
- packages/ui-tests/stories/kaotoForm/PipeErrorHandler.stories.tsx
- packages/ui/src/components/Visualization/Canvas/index.ts
- packages/ui/src/pages/Metadata/index.ts
- packages/ui/src/pages/PipeErrorHandler/index.ts
- packages/ui/src/public-api.ts
fix https://github.com/KaotoIO/kaoto/issues/2165
> storybook: Add storybook pages for PipeErrorHandler and Metadata

- packages/ui/src/models/visualization/flows/support/flows-visibility.test.ts
- packages/ui/src/models/visualization/flows/support/flows-visibility.ts
> fix(VisibleFlowsReducer): disable first flow always visible

- packages/ui-tests/cypress/e2e/designer/multiflow/multiFlowDesigner.cy.ts
- packages/ui-tests/cypress/support/next-commands/default.ts
- packages/ui-tests/stories/canvas/ContextToolbar.stories.tsx
- packages/ui/src/components/Visualization/ContextToolbar/IntegrationTypeSelector/ChangeIntegrationTypeModal/ChangeIntegrationTypeModal.test.tsx
- packages/ui/src/components/Visualization/ContextToolbar/IntegrationTypeSelector/ChangeIntegrationTypeModal/ChangeIntegrationTypeModal.tsx
- packages/ui/src/components/Visualization/ContextToolbar/IntegrationTypeSelector/IntegrationTypeSelector.test.tsx
- packages/ui/src/components/Visualization/ContextToolbar/IntegrationTypeSelector/IntegrationTypeSelector.tsx
- packages/ui/src/components/Visualization/ContextToolbar/IntegrationTypeSelector/IntegrationTypeSelectorToggle/IntegrationTypeSelectorToggle.test.tsx
- packages/ui/src/components/Visualization/ContextToolbar/IntegrationTypeSelector/IntegrationTypeSelectorToggle/IntegrationTypeSelectorToggle.tsx
- packages/ui/src/components/Visualization/ContextToolbar/index.ts
- packages/ui/src/pages/Design/router-exports.tsx
fixes https://github.com/KaotoIO/kaoto/issues/1098
> fix(#1098): Rename DSL concept to Integration type

- packages/ui/src/components/Visualization/Canvas/FormV2/fields/AutoField.test.tsx
- packages/ui/src/components/Visualization/Canvas/FormV2/fields/AutoField.tsx
Fixes #2218 
```yaml
- route:
id: route-4567
from:
id: from-3042
uri: timer
parameters:
fixedRate: true
includeMetadata: true
period: "1000"
timerName: template
steps: []
```
| --- | --- |
| ![image](https://github.com/user-attachments/assets/a5e40c2a-a524-4b81-b98b-bcacabcdbe69) | ![image](https://github.com/user-attachments/assets/6c66b960-6695-45e8-98b4-72518b8540a8) |
> Fix(form): Ensure updated primitive fields are displayed in the Modified tab

- packages/ui-tests/cypress/e2e/designer/sidepanelConfig/stepRename.cy.ts
e2e for https://github.com/KaotoIO/kaoto/issues/2197
> e2e(#2197): test the sync between the canvas nodes and form changes

- packages/ui/src/layout/TopBar.scss
- packages/ui/src/layout/TopBar.tsx
Make Logo centered: 
Before
After:
> fix(TopBar): Center the logo

- packages/ui-tests/cypress/e2e/designer/basicNodeActions/stepDisable.cy.ts
reproducer for https://github.com/KaotoIO/kaoto/issues/2218
> e2e(#2218): reproducer for "primitive form-fields not reflected in modified tab"

- packages/ui-tests/cypress/fixtures/iconsRouteMock.json
- packages/ui-tests/stories/canvas/Canvas.stories.tsx
storybook for https://github.com/KaotoIO/kaoto/issues/2215
> storybook(#2215): Azure-related icons seems small

- packages/ui-tests/cypress/e2e/designer/rootContainerConfig/visibilityProviderConf.cy.ts
- packages/ui-tests/cypress/fixtures/flows/camelRoute/threeRoutes.yaml
- packages/ui-tests/cypress/support/cypress.d.ts
- packages/ui-tests/cypress/support/next-commands/default.ts
e2e for https://github.com/KaotoIO/kaoto/issues/2229
> e2e(#2229): Visibility provider

- packages/ui-tests/cypress/e2e/codeEditor/multiFlowEditor.cy.ts
- packages/ui-tests/cypress/e2e/designer/multiflow/multiFlowDesigner.cy.ts
- packages/ui-tests/cypress/e2e/designer/rootContainerConfig/rootContainersConf.cy.ts
- packages/ui-tests/cypress/e2e/designer/rootContainerConfig/visibilityProviderConf.cy.ts
- packages/ui-tests/cypress/e2e/designer/routeDocumentation/exportRouteDocumentation.cy.ts
- packages/ui-tests/cypress/support/cypress.d.ts
- packages/ui-tests/cypress/support/next-commands/default.ts
- packages/ui/src/models/visualization/flows/support/flows-visibility.test.ts
- packages/ui/src/providers/visible-flows.provider.tsx
- packages/ui/src/utils/init-visible-flows.test.ts
- packages/ui/src/utils/init-visible-flows.ts
> Fix(Canvas): Ensure all routes are visible when starting Kaoto

- packages/ui-tests/cypress/e2e/designer/settings/switchColorScheme.cy.ts
- packages/ui-tests/cypress/support/cypress.d.ts
- packages/ui-tests/cypress/support/next-commands/design.ts
- packages/ui/src/App.tsx
- packages/ui/src/models/local-storage-keys.ts
- packages/ui/src/router.tsx
> Fix(Settings): Switching the Color scheme should not require the page  refresh

- packages/ui-tests/cypress/e2e/designer/multiflow/multiFlowDesigner.cy.ts
- packages/ui-tests/cypress/e2e/designer/rootContainerConfig/visibilityProviderConf.cy.ts
- packages/ui/src/components/Visualization/ContextToolbar/NewEntity/NewEntity.tsx
> Fix(canvas): Keep current visibility when adding a new entity to the canvas

- packages/catalog-generator/pom.xml
- packages/catalog-generator/src/test/java/io/kaoto/camelcatalog/generator/CamelCatalogProcessorTest.java
- packages/catalog-generator/src/test/java/io/kaoto/camelcatalog/generators/EIPGeneratorTest.java
- packages/catalog-generator/src/test/java/io/kaoto/camelcatalog/generators/EntityGeneratorTest.java
* Camel 4.11.0
* Camel Spring Boot 4.11.0
* Camel extensions for Quarkus 3.20.0
* Camel Kamelets 4.11.0
fix: https://github.com/KaotoIO/kaoto/issues/2266
> chore(Catalog): Update embedded Camel version

- packages/ui/package.json
- packages/ui/src/multiplying-architecture/KaotoEditorApp.test.tsx
- yarn.lock
fix: https://github.com/KaotoIO/kaoto/issues/2022
> chore(VSCode): Update @kie-tools-core deps

- packages/ui-tests/cypress/e2e/designer/multiflow/deleteMultiFlow.cy.ts
e2e for https://github.com/KaotoIO/kaoto/pull/2260
> e2e(#2260): Allow to delete filtered/all routes at once

- packages/ui/src/components/Visualization/Canvas/Form/CanvasForm.scss
Fixes #2053
Changes in this PR looks like this:
> Fix(Form): Add spacing between form border and body content

- packages/ui-tests/cypress/support/next-commands/sourceCode.ts
fixes: https://github.com/KaotoIO/kaoto/issues/2278
> fix(#2278): Sporadic e2e failure on xmlSupport/basicXml.cy.ts

- packages/ui/src/models/visualization/flows/support/camel-component-schema.service.ts
> feat: parse string defined components

- packages/ui/src/components/Document/actions/AttachSchemaButton.test.tsx
- packages/ui/src/components/Document/actions/AttachSchemaButton.tsx
Fixes: https://github.com/KaotoIO/kaoto/issues/2429
Following up https://github.com/KaotoIO/kaoto/pull/2427#discussion_r2258534974
https://github.com/user-attachments/assets/a9c3e1c4-8de0-4c21-8a9b-45d15aab7bea
> fix(DataMapper): Avoid attaching JSON schema to the source body

- packages/ui/src/components/Visualization/Canvas/Form/suggestions/suggestions/properties.suggestions.test.ts
- packages/ui/src/components/Visualization/Canvas/Form/suggestions/suggestions/properties.suggestions.ts
Coming from: https://github.com/KaotoIO/vscode-kaoto/pull/995
> feat(Suggestions): Wire application.properties suggestions provider

- packages/ui-tests/package.json
- packages/ui/package.json
- packages/ui/scripts/get-camel-catalog-files.mjs
- packages/ui/src/models/visualization/flows/support/__snapshots__/camel-component-schema.service.test.ts.snap
- packages/ui/src/models/visualization/flows/support/camel-component-schema.service.test.ts
- packages/ui/src/utils/catalog-schema-loader.test.ts
- packages/ui/src/utils/catalog-schema-loader.ts
- packages/ui/vite.config.mjs
- yarn.lock
fix: https://github.com/KaotoIO/kaoto/issues/2283
> feat(UI): Add XML IO Schema

- packages/ui/src/components/Visualization/Canvas/StepToolbar/StepToolbar.tsx
- packages/ui/src/components/Visualization/Canvas/__snapshots__/Canvas.test.tsx.snap
- packages/ui/src/components/Visualization/Custom/ContextMenu/ItemDuplicateStep.test.tsx
- packages/ui/src/components/Visualization/Custom/ContextMenu/ItemDuplicateStep.tsx
- packages/ui/src/components/Visualization/Custom/ContextMenu/NodeContextMenu.test.tsx
- packages/ui/src/components/Visualization/Custom/ContextMenu/NodeContextMenu.tsx
- packages/ui/src/components/Visualization/Custom/ContextMenu/__snapshots__/ItemDuplicateStep.test.tsx.snap
- packages/ui/src/components/Visualization/Custom/hooks/duplicate-step.hook.test.tsx
- packages/ui/src/components/Visualization/Custom/hooks/duplicate-step.hook.tsx
- packages/ui/src/models/camel/camel-resource.ts
- packages/ui/src/models/camel/camel-route-resource.test.ts
- packages/ui/src/models/camel/camel-route-resource.ts
- packages/ui/src/models/visualization/flows/camel-error-handler-visual-entity.test.ts
- packages/ui/src/models/visualization/flows/camel-error-handler-visual-entity.ts
- packages/ui/src/models/visualization/flows/camel-rest-configuration-visual-entity.test.ts
- packages/ui/src/models/visualization/flows/camel-rest-configuration-visual-entity.ts
> feat(duplicate-nodes):  Duplicate steps/container on the canvas

- packages/ui/src/providers/datamapper.provider.test.tsx
- packages/ui/src/providers/datamapper.provider.tsx
Fixes: https://github.com/KaotoIO/kaoto/issues/2478
> fix(DataMapper): Fails to restore JSON mappings in VS Code

- packages/ui-tests/package.json
- packages/ui/package.json
- yarn.lock
fix: https://github.com/KaotoIO/kaoto/issues/2501
> fix(form): Update @kaoto/forms

- packages/ui-tests/cypress/e2e/designer/basicNodeActions/stepCopy.cy.ts
- packages/ui-tests/cypress/e2e/designer/basicNodeActions/stepPaste.cy.ts
- packages/ui-tests/cypress/fixtures/flows/camelRoute/complexMultiFlow.yaml
- packages/ui-tests/cypress/fixtures/flows/camelRoute/routeConfigurationAndIntercept.yaml
- packages/ui-tests/cypress/support/cypress.d.ts
- packages/ui-tests/cypress/support/next-commands/default.ts
- packages/ui-tests/cypress/support/next-commands/design.ts
> E2E: Add E2E for Copy-Paste feature

- packages/ui/src/components/XPath/XPathEditorModal.test.tsx
- packages/ui/src/components/XPath/XPathEditorModal.tsx
> Datamapper(#2397): Enable help and warning popover in Xpath editor

- packages/ui-tests/cypress/e2e/designer/DnD/dragAndDrop.cy.ts
- packages/ui-tests/cypress/fixtures/flows/camelRoute/multiflowDnD.yaml
- packages/ui-tests/cypress/support/cypress.d.ts
- packages/ui-tests/cypress/support/next-commands/design.ts
- packages/ui-tests/package.json
- packages/ui/src/components/Visualization/Custom/Node/CustomNode.tsx
- yarn.lock
fixes https://github.com/KaotoIO/kaoto/issues/2458
> e2e(D&D) : Add E2E for nodes drag-and-drop

- packages/ui/src/providers/datamapper.provider.test.tsx
- packages/ui/src/providers/datamapper.provider.tsx
> Fix(#2575): Parameter renaming produces an invalid xslt

- packages/ui/src/providers/datamapper.provider.test.tsx
- packages/ui/src/providers/datamapper.provider.tsx
Fixes: https://github.com/KaotoIO/kaoto/issues/2611
> fix(DataMapper): Re-opening to-JSON mapping in vscode breaks the XSLT
